### ISSUE TITLE
Attendee - Event Page - Favorite Event

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#100]
## Background 
A user should be able to Favorite and event. See [video](https://vimeo.com/290056954) at 15 second mark.

## Scenario: A user favorites an event from the Event page
- [ ] Then I select the favorite(star) button
- [ ] Then the star is highlighted in color

**Comment by brittanygay** [comment]
Pulling this in to work on the active state styling

**Comment by brittanygay** [comment]
Styles as pushed up on my branch and approved. 

@daybreaker this is now ready for you to add functionality. More info in my PR here: https://github.com/revelrylabs/bn-mobile-react/pull/109  and the branch is called `100-favorite-active-state`

Let me know if you need anything else from me!

**Comment by brittanygay** [comment]
Pulling this in to finish up the last styling edit

**Comment by brittanygay** [comment]
Once updates are deployed this will be ready for QA @Mcscott142
