### ISSUE TITLE
Attendee - Discover Page - Favorite Event

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#101]
## Background 
A user should be able to Favorite and event. See [video](https://vimeo.com/290056954) at 15 second mark.

## Scenario: A user favorites an event from the Discover page
- [ ] When I select the favorite(star) button
- [ ] Then the star is highlighted in color

**Comment by brittanygay** [comment]
The styles for the smaller favorite icon has been reviewed and merged. More info and screenshots here: https://github.com/revelrylabs/bn-mobile-react/pull/110

This is now ready for a dev to pick up once we add this to a sprint commitment.
