### ISSUE TITLE
Attendee - Checkout - Purchase Tickets

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#103]
## Background
The checkout page will allow users to select the Qty of tickets they want plus their payment type. See video [here](https://vimeo.com/290056954) for reference.

## Scenario: A user purchases tickets
- [ ] When select +/- on Qty 
- [ ] Then my ticket qty goes up/down
- [ ] Then I see the following sections under the ticket quantity:
  - [ ] Artist name, date and location
  - [ ] Payment section (which directs to `Change Payment Type`)
  - [ ] Subtotal and Fees
  - [ ] Total Price
  - [ ] `Purchase Ticket` button (covered in #108)

Screenshot of mockup:
![checkout](https://user-images.githubusercontent.com/14582709/46317574-1652e680-c599-11e8-9d2e-4752de2a314d.jpg)

**Comment by brittanygay** [comment]
Mcscott142 I'veI updated the AC to include the other sections on the screen that need to be stubbed out.

**Comment by brittanygay** [comment]
Pulling this in to work on next

**Comment by brittanygay** [comment]
Putting this down to check out #124 first

**Comment by brittanygay** [comment]
PR has been reviewed and merged. This will now be ready for QA once updates are deployed.
