### ISSUE TITLE
Attendee - Checkout - Change Payment Type

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#104]
## Background
A user should be able to change their payment type from Checkout. See video [here](https://vimeo.com/290056954) for reference.

## Scenario: A user selects a payment option
- [ ] When I click my payment option
- [ ] Then I am directed to a change payment screen
- [ ] When I change my payment
- [ ] Then I am directed back to the checkout

**Comment by brittanygay** [comment]
@daybreaker I think I'm going to need you to set up a new screen before I can pick this up :)

**Comment by brittanygay** [comment]
Pulling this in next to work on stubbing the screen out

**Comment by brittanygay** [comment]
I finished up styling updates for #99 earlier today, now moving back onto this ticket to finish stubbing out styles

**Comment by brittanygay** [comment]
**Update**:
I'm more than halfway done with the styling of this screen. Planning on finishing this up this morning.

**Comment by brittanygay** [comment]
Styles are in place with the exception of the CheckBox component. Passing this ticket over to @daybreaker to take a look. More info here: https://github.com/revelrylabs/bn-mobile-react/pull/121

@daybreaker let me know if you'd like to pair on this! The branch name is `104-change-payment-type`

**Comment by brittanygay** [comment]
PR has been approved and merged. This is now ready for QA once updates are deployed.

**Comment by Mcscott142** [comment]
Closed but opened a bug round this.
