### ISSUE TITLE
Get Colin Access to push builds

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#105]
- [x] He needs Apple developer team invite
- [ ] Add'tl things as they come up

**Comment by Mcscott142** [comment]
I think I have all the access that I need. Just have to troubelshoot the set up. Having issues with certificates when building via Expo. Relevant Links:
- https://blog.expo.io/automating-standalone-expo-app-builds-and-deployments-with-fastlane-exp-and-exptool-9b2f5ad0a2cd
- https://forums.expo.io/t/exp-fetch-ios-certs-exp-build-ios/7322
- I have final script to use and necessary ENV vars but not posting it on ticket.

**Comment by thomasknoll** [comment]
@jwietelmann ^^

**Comment by jwietelmann** [comment]
errrrr @nick? I am bad at this.

**Comment by Mcscott142** [comment]
Will get this worked out this week with Brad back.

**Comment by Mcscott142** [comment]
Closing this with #172 on the board.
