### ISSUE TITLE
Attendee - Checkout/My Tickets - My ticket Animation upon ticket purchase

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#108]
## Background
After a user purchases a ticket they are directed back to their `My Tickets` page. They should see their new purchase loaded here. See animation in 0:45 mark of [video](https://vimeo.com/291552558)

## Scenario: A user purchases a new ticket
- [ ] When I select purchase tickets
- [ ] Then I am directed to `My Tickets`
- [ ] And I see the animation with my new ticket

**Comment by brittanygay** [comment]
@daybreaker I think I'll need your help directing the `Purchase Tickets` button (which hasn't been stubbed out yet) to direct to the `My Tickets` screen (which already exists).

I can take a stab at it and see if I can hook it up, because I normally can set them up properly with normal React buttons, but not sure about React Native.

**Comment by daybreaker** [comment]
Have a branch called `link-to-tickets` that will link to the MyTickets page when we click on Purchase Tickets. I couldnt get any fancy state stuff set up to say "We have a new ticket" vs "We're just doing a normal visit to this tab", so I guess just make the first ticket animate, and I'll figure out the rest later.

@Mcscott142  I'm going to need to get some kind of state management going soon, like unstated (Joel said we're moving away from redux). We're hitting a point where internal state and sample objects arent going to cut it.

I'm going to work on that tomorrow

**Comment by brittanygay** [comment]
Pulling this in to work on the animation. @daybreaker I'll let you know if I need any help!

**Comment by brittanygay** [comment]
@Mcscott142 I just updated the AC with the newest Vimeo video

**Comment by brittanygay** [comment]
PR has been reviewed and merged. Once updates are deployed this will be ready for QA
