### ISSUE TITLE
Attendee - Events Page - Update Styling for Get Tickets section

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#115]
## Background
We need to update the Styling on the Get Tickets section on the event page. 

## Scenario: A user visits the event page
- [ ] When I visit an event page
- [ ] Then I see that the `Get Tickets`button has been updated with new styles. 

Mock:
![event details](https://user-images.githubusercontent.com/6877299/45775274-e3ae0300-bc14-11e8-9acf-0834b97b5e9b.png)

**Comment by brittanygay** [comment]
Pulling this in to work on today

**Comment by brittanygay** [comment]
Style updates are now complete. More info and screenshots here: https://github.com/revelrylabs/bn-mobile-react/pull/117

Once updates are deployed this will be ready for QA.
