### ISSUE TITLE
location alignment on Discover Page

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#119]
## Background
Having Location changes has thrown the location/logo/drop icon alignment off again.

![image from ios 2](https://user-images.githubusercontent.com/6877299/46079165-f7e58900-c15b-11e8-8983-c94ef1cd3b48.jpg)

**Comment by brittanygay** [comment]
Pulling this in first to knock out

**Comment by brittanygay** [comment]
PR has been reviewed and merged. More info and screenshots here: https://github.com/revelrylabs/bn-mobile-react/pull/133

Once updates are deployed this will be ready for QA.
