### ISSUE TITLE
Doorperson - Event - View Event

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#128]
## Background
When an Event Manager opens their event, they will be able to see statistics and information related to that event and it's ticket sales. This ticket does not cover the visual graphs.

## Scenario: Event Manager Selects an Event from their Management list
- [ ] When I select an Event from the list of events I'm managing
- [ ] Then I see 
	- [ ] Total Tickets sold or accounted for / Total Tickets Available  
	- [ ] Breakdown of Listed vs Ticketed guests
	- [ ] An option to Scan tickets
	- [ ] A preview of the lists for this event
	- [ ] A Preview of the users managing this event

Mock: 
![dropbox_-_r2_-_simplify_your_life](https://user-images.githubusercontent.com/6877299/46376876-c6d5ee80-c65c-11e8-9a2a-f2ee7a980ac1.png)

**Comment by Mcscott142** [comment]
AC updated, marked SCORE

**Comment by Mcscott142** [comment]
Updated, moved to Up Next.

**Comment by bryanjos** [comment]
How do I get List and User data?

**Comment by bryanjos** [comment]
Looking around, I don't see the appropriate data available. So I'm putting this back and adding the blocked label

**Comment by brittanygay** [comment]
I'm also keeping this on my radar, will need a design pass for sure.

**Comment by jwietelmann** [comment]
@Krakaw Do you have any suggested API endpoints for this? (Do they exist?)

**Comment by Krakaw** [comment]
@jwietelmann It will probably be a combination of 2 queries to get everything you want.
`server.events.dashboard` https://big-neon.github.io/bn-api-node/classes/_resources_events_.eventsresource.html#dashboard to get the stats (the return type in the docs is incorrect)
```json
{
  "event": {
    "id": "036fd68d-ace9-47a1-8b1d-2cd0531840de",
    "name": "Hold Allocation Test",
    "organization_id": "c501a664-2673-47ac-98dc-3156dda3bff5",
    "venue": {
      "id": "22028151-e1a3-4d55-80f3-ae7f411c596a",
      "name": "SA Venue",
      "timezone": "Africa/Johannesburg"
    },
    "created_at": "2019-02-20T07:52:28.922334",
    "event_start": "2019-02-19T10:00:00",
    "door_time": "2019-02-19T09:00:00",
    "status": "Published",
    "promo_image_url": "https://i.scdn.co/image/30178636b1a28ab76de5a4a4599cc9a5dd866735",
    "additional_info": null,
    "top_line_info": null,
    "age_limit": 21,
    "cancelled_at": null,
    "min_ticket_price": 100,
    "max_ticket_price": 100,
    "publish_date": "2019-02-20T07:52:32.439",
    "on_sale": "2019-02-01T10:30:00",
    "total_tickets": 30,
    "sold_unreserved": 2,
    "sold_held": 6,
    "tickets_open": 8,
    "tickets_held": 20,
    "tickets_redeemed": 0,
    "sales_total_in_cents": 800,
    "ticket_types": [
      {
        "event_id": "036fd68d-ace9-47a1-8b1d-2cd0531840de",
        "name": "General Admission",
        "min_price": 100,
        "max_price": 100,
        "total": 10,
        "sold_unreserved": 2,
        "sold_held": 0,
        "open": 8,
        "held": 0,
        "redeemed": 0,
        "sales_total_in_cents": 200
      },
      {
        "event_id": "036fd68d-ace9-47a1-8b1d-2cd0531840de",
        "name": "Full Hold Allocation",
        "min_price": 100,
        "max_price": 100,
        "total": 20,
        "sold_unreserved": 0,
        "sold_held": 6,
        "open": 0,
        "held": 20,
        "redeemed": 0,
        "sales_total_in_cents": 600
      }
    ],
    "is_external": false,
    "external_url": null,
    "override_status": null,
    "localized_times": {
      "event_start": "Tue, 19 Feb 2019 12:00:00 +0200",
      "event_end": "Fri,  1 Mar 2019 12:00:00 +0200",
      "door_time": "Tue, 19 Feb 2019 11:00:00 +0200"
    },
    "event_type": "Music"
  },
  "day_stats": [
    {
      "date": "2019-02-11",
      "revenue_in_cents": 0,
      "ticket_sales": 0
    },
    {
      "date": "2019-02-12",
      "revenue_in_cents": 0,
      "ticket_sales": 0
    },
    {
      "date": "2019-02-13",
      "revenue_in_cents": 0,
      "ticket_sales": 0
    },
    {
      "date": "2019-02-14",
      "revenue_in_cents": 0,
      "ticket_sales": 0
    },
    {
      "date": "2019-02-15",
      "revenue_in_cents": 0,
      "ticket_sales": 0
    },
    {
      "date": "2019-02-16",
      "revenue_in_cents": 0,
      "ticket_sales": 0
    },
    {
      "date": "2019-02-17",
      "revenue_in_cents": 0,
      "ticket_sales": 0
    },
    {
      "date": "2019-02-18",
      "revenue_in_cents": 0,
      "ticket_sales": 0
    },
    {
      "date": "2019-02-19",
      "revenue_in_cents": 0,
      "ticket_sales": 0
    },
    {
      "date": "2019-02-20",
      "revenue_in_cents": 500,
      "ticket_sales": 5
    },
    {
      "date": "2019-02-21",
      "revenue_in_cents": 0,
      "ticket_sales": 0
    },
    {
      "date": "2019-02-22",
      "revenue_in_cents": 0,
      "ticket_sales": 0
    },
    {
      "date": "2019-02-23",
      "revenue_in_cents": 300,
      "ticket_sales": 3
    },
    {
      "date": "2019-02-24",
      "revenue_in_cents": 0,
      "ticket_sales": 0
    },
    {
      "date": "2019-02-25",
      "revenue_in_cents": 0,
      "ticket_sales": 0
    },
    {
      "date": "2019-02-26",
      "revenue_in_cents": 0,
      "ticket_sales": 0
    },
    {
      "date": "2019-02-27",
      "revenue_in_cents": 0,
      "ticket_sales": 0
    },
    {
      "date": "2019-02-28",
      "revenue_in_cents": 0,
      "ticket_sales": 0
    },
    {
      "date": "2019-03-01",
      "revenue_in_cents": 0,
      "ticket_sales": 0
    },
    {
      "date": "2019-03-02",
      "revenue_in_cents": 0,
      "ticket_sales": 0
    },
    {
      "date": "2019-03-03",
      "revenue_in_cents": 0,
      "ticket_sales": 0
    },
    {
      "date": "2019-03-04",
      "revenue_in_cents": 0,
      "ticket_sales": 0
    },
    {
      "date": "2019-03-05",
      "revenue_in_cents": 0,
      "ticket_sales": 0
    },
    {
      "date": "2019-03-06",
      "revenue_in_cents": 0,
      "ticket_sales": 0
    },
    {
      "date": "2019-03-07",
      "revenue_in_cents": 0,
      "ticket_sales": 0
    },
    {
      "date": "2019-03-08",
      "revenue_in_cents": 0,
      "ticket_sales": 0
    },
    {
      "date": "2019-03-09",
      "revenue_in_cents": 0,
      "ticket_sales": 0
    },
    {
      "date": "2019-03-10",
      "revenue_in_cents": 0,
      "ticket_sales": 0
    },
    {
      "date": "2019-03-11",
      "revenue_in_cents": 0,
      "ticket_sales": 0
    },
    {
      "date": "2019-03-12",
      "revenue_in_cents": 0,
      "ticket_sales": 0
    }
  ]
}
```
and `server.events.holds.index` https://big-neon.github.io/bn-api-node/classes/_resources_namespaced_event_holds_.eventholdsresource.html#index

**Comment by bryanjos** [comment]
Looking at the screenshot, what data from the API matches up with what is shown in the screenshot?

**Comment by Mcscott142** [comment]
@bryanjos is that not the return from `server.events.dashboard`? I have no idea, just asking. Maybe following these links will lead you to the answer if nobody responds shortly. 

https://big-neon.github.io/bn-api-node/classes/_resources_events_.eventsresource.html#dashboard

https://github.com/big-neon/bn-api-node/blob/36e8577/src/resources/events.ts#L138

**Comment by brittanygay** [comment]
Jumping on this for a design pass

**Comment by brittanygay** [comment]
I just pushed up my edits, screenshots and more info here: https://github.com/revelrylabs/bn-mobile-react/pull/607#issuecomment-472109172

Passing back to @jwietelmann to finish up!

**Comment by Krakaw** [comment]
![image](https://user-images.githubusercontent.com/41575888/54228779-8b90f300-450b-11e9-9232-bb338f5e43a2.png)
There isn't an endpoint for this data currently.

**Comment by bryanjos** [comment]
What about the Lists parts?

<img width="402" alt="Screen Shot 2019-03-12 at 2 22 43 PM" src="https://user-images.githubusercontent.com/1257573/54229471-5320f300-44d2-11e9-9575-b5df266331c3.png">

**Comment by zmelamed** [comment]
Sorry mentioned this in Slack... Lists and Users should be ignored for now from an implementation perspective, Can move the UI forward so we have those components but we're holding on those features.

From slack:
This feature/view was created a long time ago and thus we'll phase it and quickly iterate because a lot is outdated.

The stats at the top for the purpose of the doorman night of the event really should be showing total checked in vs total sold and total open vs total sold... “how many people do we have left to check in?” .. “how many more people can we sell tix to?”... so this is what I’m thinking about. At the end of the day all the UI that’s there will be utilized, and the data comes from the same place, just thinking about how we organize the data in a value adding way

**Comment by jwietelmann** [comment]
![File.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53b5aa8a7953d2fd0f72338d/125516c66e82c728ace21e0d46ce9d9626c0cfeb9ffbb049a15ee4d6730472717f50f52d27d1e729eb1522045f5f4ffe49585f46fbf99b37b4f46d2ede0356b49b381d66cc2f10abb2831aba03be228f4d82b3bb8e4fd2a5.jpg)

We don't have more design time this week, so I added a little X of Y redeemed thing under the scan button, and I'm going to say that probably satisfies all currently-expressed needs until we circle back to do better. Moving to QA.
