### ISSUE TITLE
Attendee - Checkout / API - Ticket Type Selection

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#140]
## Background
This issue is for connecting the Ticket types through the API and selecting them in the App. 

## Scenario: A user selects a ticket type to purchase
- [ ] When I select `Get Tickets`
- [ ] Then I am able to select a Ticket Type pulled from the API
- [ ] And I can continue to the next step of the checkout process

**Comment by Mcscott142** [comment]
AC updated. Other checkout flows captured in #263 and #264

**Comment by daybreaker** [comment]
To test, you can view the name of the ticket type selected on the following checkout details page.  Price isnt being carried over yet (part of an upcoming ticket)

**Comment by Mcscott142** [comment]
I can confirm that the Ticket types are pulling from the API. I think we may have lost a transition/animation once you select `get tickets`. For reference: https://vimeo.com/291552558. @brittanygay Is that something you may be able to look into or is that a Brad thing?

**Comment by brittanygay** [comment]
@Mcscott142 I think this is something we may both have to look into since we are adding another animation.
