### ISSUE TITLE
Designer - Checkout Design Updates

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#159]
## Background
We need to make a few design tweaks to get current with the final production mocks. This tickets is just a checklist for those things.

- [ ] ~When you arrive at this view the scrollable area should auto rise up to the top to expose more of the summary form (can go all the way to 10px from the bottom of the back arrow to make sure you can see the whole view)~
- [x] When the tickets are above 1, the minus button (-) should take an active state (pink)
- [x] Increase size of (+) (-) buttons to 1.25x their current size (should end up at 50px I believe)
- [x] Fix padding on Checkout and Ticket Selection headers

via @zmelamed 
<img width="1406" alt="ios_app__zach_-_dev_prep__sketch 2" src="https://user-images.githubusercontent.com/6877299/46614255-f8c2d700-cada-11e8-9fcc-b842458b5aff.png">

**Comment by brittanygay** [comment]
Going to pull this in to start on these updates. I may have to put back into the backlog for @daybreaker to finish up when he gets time (or whenever we pull this ticket into the next sprint)

**Comment by brittanygay** [comment]
I pushed up a branch to get the third edit merged, but I will need help from @daybreaker to get the other two items set up. 

After doing some research, I found a few links that could help us with the animated auto rise:

https://github.com/oblador/react-native-animatable
we could use the `slideInUp` animation (or something similar from expo)

https://docs.expo.io/versions/latest/react-native/animations
Expo docs (since I think we need to use these instead)

**Comment by brittanygay** [comment]
I've also put in a fix for the Checkout and Ticket Selection header padding issue

**Comment by brittanygay** [comment]
**Update**:
I'm getting close to getting the component working. I'm using the Pose library, which also seems like a good library to use for future animations. 

It looks like this Transition setup is the way to go: https://popmotion.io/pose/api/native-transition/#{{0}

I'm gonna give it one more shot tomorrow morning, but won't waste too much more time. I'll pass over to @daybreaker if I have any problems so we can get this finished up.

**Comment by Mcscott142** [comment]
@brittanygay All is done except the first checkbox here correct?

**Comment by brittanygay** [comment]
@Mcscott142 I think the AC was checked off incorrectly: the only thing that's left is the auto rise of the scrollable area that @daybreaker was going to look into to see if it was an easy win

**Comment by Mcscott142** [comment]
If @chas-mcmahon has any time left, maybe y'all can pair on that. @brittanygay

**Comment by daybreaker** [comment]
It isnt really even required... Its a nice-to-have.

Maybe we should split it off into a new ticket with the note that its in the `159-style-issues` branch.

**Comment by Mcscott142** [comment]
Moved first AC into https://github.com/revelrylabs/bn-mobile-react/issues/266. Moving this to QA.
