### ISSUE TITLE
Login Page - Replace Image

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#163]
## Background
The Background image on the login page looks grainy. Let's replace it with a higher res image. 

## Scenario: Replace Image on Login
- [ ] When I log in to Big Neon
- [ ]  Then the background image is clear

**Comment by Mcscott142** [comment]
Need new image to replace.

**Comment by Mcscott142** [comment]
Discussed yesterday. We can find a suitable image for background, for now, that looks less grainy. :raised_hands: . Will leave that up to @brittanygay . Unblocking.

**Comment by brittanygay** [comment]
Pulling this in to knock out

**Comment by brittanygay** [comment]
Image has been approved and replaced. Ready for QA once updates are deployed
