### ISSUE TITLE
Change Endpoint out

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#164]
From Keith via Slack:

>Keith [12:27 AM]
Morning guys, 2 quick changes, the new endpoint is at https://staging.bigneon.com/api that’s going to be stable now. As well as the new version of bn-api-node@0.2.0, the big change in this version is all the index endpoints return the same interface {data:[], paging: {}}

- [ ] Change out endpoint if needed
- [ ] Make any changes needed regarding updated  bn-api-node@0.2.0

**Comment by daybreaker** [comment]
@Mcscott142 - I tested locally and got a 201 response with the new endpoint. The only real way to QA it right now is to register a new user and be redirected to the login screen with no error
