### ISSUE TITLE
Designer - Ticket Wallet - Stop Header Scroll

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#165]
## Background
We have a request to stop the Header from Scrolling up in the app. 

## Scenario: Designer updates Scroll functionality
- [ ] The header should not scroll up when scrolling

via @zmelamed 
<img width="1639" alt="ios_app__zach_-_dev_prep__sketch 3" src="https://user-images.githubusercontent.com/6877299/46614286-109a5b00-cadb-11e8-9a25-ebb097a76405.png">

**Comment by brittanygay** [comment]
Picking this up next to see what all I can do with setting this up

**Comment by zmelamed** [comment]
@brittanygay with this one, the only thing that should scroll in the new design is the ticket content area (the header and tabs should stay fixed with the tickets scrolling under them)

**Comment by brittanygay** [comment]
@daybreaker I looked into this and I think you're right, this is more of a back-end thing. Putting this back down so you can take a look when you get to it

**Comment by daybreaker** [comment]
actually turned out to be a sort of front end thing. So assigning to @brittanygay to review.

**Comment by zmelamed** [comment]
Per my previous comment, the tabs should not scroll, they should stay fixed to the header, only the ticket area should scroll

**Comment by daybreaker** [comment]
My bad - @brittanygay - I have a new branch that makes the tabs static too, but it needs some style work:  165-tabs

**Comment by brittanygay** [comment]
@daybreaker I just pushed up my edits for the styling bugs. Assigning back to you to finish up!

**Comment by daybreaker** [comment]
It looks like the pink underline for the active tab is like 1px above the bottom of the container its in?  If you scroll a ticket up, you can see a small grey line beneath the pink active border, and the ticket.

**Comment by brittanygay** [comment]
@daybreaker I just pushed up a fix for the border overlay bug. Here are screenshots of how it looks now:

<img width="327" alt="screen shot 2018-10-25 at 2 42 43 pm" src="https://user-images.githubusercontent.com/14582709/47526152-89800d80-d864-11e8-823c-c7ab2e41e64d.png">
![simulator screen shot - iphone x - 2018-10-25 at 14 41 47](https://user-images.githubusercontent.com/14582709/47526153-89800d80-d864-11e8-8c8f-e308dc4ece28.png)
