### ISSUE TITLE
Designer - Ticket Wallet - Update Tabs and Header

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#166]
## Background 
Updates to Ticket Wallet. 

## Scenario: Designer updates page
- [ ] The tabs and header should be updated to match the spec’d version 

via @zmelamed 
<img width="1639" alt="ios_app__zach_-_dev_prep__sketch 3" src="https://user-images.githubusercontent.com/6877299/46614286-109a5b00-cadb-11e8-9a25-ebb097a76405.png">

**Comment by brittanygay** [comment]
Going to pull this in next to update the styling

**Comment by brittanygay** [comment]
My PR is out here: https://github.com/revelrylabs/bn-mobile-react/pull/191

Assigning to @daybreaker to check out the items I listed in my PR

**Comment by brittanygay** [comment]
Updates are merged. This will be ready for QA once deployment is made.
