### ISSUE TITLE
Developer - Event - Show Page

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#171]
_depends on #167_
## Background
We need to start wiring these screens up. This is for pulling actual Event data from the API on the Event show page. 

## Scenario: A user selects an event from the Discover page
- [ ] When I select an Event from the Discover page
- [ ] Then I am directed to the Show page
- [ ] And all the information I see if pulled from the Big Neon API

**Comment by brittanygay** [comment]
I don't think there is any new design around this, but let me know @daybreaker. Once we pull in actual data I may need to clean a few things up

**Comment by daybreaker** [comment]
We'll still need an "Interested" interface with an array of avatar URLs in it.

Also, as of right now, we might need to eject from Expo to embed You Tube videos or stream songs from Spotify. There are no Expo libraries for that yet. This would also mean replacing any of the existing Expo libraries we're using. There may be a workaround for YT videos using WebViews. But, also, if there's an alternate video host that provides direct video links, the Expo `<Video>` component can use those (just YT seems to be an issue). 

@zmelamed  I also dont know what "top line info" is vs "additional info". Is there an ETA on better sample event data? I can make up my own for the mocker, but knowing what real data will look like will be better

**Comment by zmelamed** [comment]
re videos: remove all the videos, spotify, and social content from those views for now and break them out to separate issues in the icebox.
re avatars: same thing, separate this out to a different issue. remove that block for now which is how it should be treated if it doesn't exist anyways).
Re: top line info, there is a top_line_info property thats part of the event interface, this goes above the event name if it exists, otherwise that should be hidden from the view.  re: Additional info, there is an `additional_info` property of the event interface. that is the event description.

**Comment by daybreaker** [comment]
@zmelamed 

Ah, so top_line_info is like the "Presented by Pepsi, and whoever else" line.

I'll fix that - I was using organization name in there.

Is there anywhere in the Event page mockup where we would display an Organization name?

**Comment by zmelamed** [comment]
Correct, and no, just the venue info (the organizations own the venues but aren't displayed in the UI)

**Comment by zmelamed** [comment]
Feel free to break these out to other tickets if needed, but some feedback now that I've seen the event detail page with a different data set:

- The line below the I'm Interested and Share Event buttons should be hidden if there is no list of avatars present
- The line below Event Description should be hidden if there is nothing below it
- Just noticed something i _think_ is incorrect based on the list view of events vs the detail view. The title of the cards under the event image on the explore view should be the event name, not the artist name.


I'm also going to reassess the layout of the top of the card (topline, event name, date badge) now that I can visualize what it looks like with a sparse amount of data... positioning of things look unintentional at the moment--that'll come in another issue though
