### ISSUE TITLE
Attendee - Event Page - Add Price above Get Tickets

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#174]
## Background 
We need to add the ticket price from the latest Mocks above the Get Tickets button. 

## Scenario: A user looks at an event
- [ ] When I view and Event page
- [ ] Then I see the ticket price range above `Get Tickets`

### Mock
<img width="374" alt="big_neon" src="https://user-images.githubusercontent.com/6877299/47443751-aa6c3400-d77a-11e8-9818-05f54cc28344.png">

**Comment by brittanygay** [comment]
Picking this up to work

**Comment by brittanygay** [comment]
Updates are now complete. This will be ready for QA after the next deployment.
