### ISSUE TITLE
Account Profile - Make full inputs Selectable

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#175]
## Background 
Only a small portion of the input is selectable when entering/editing account information. The whole field should cause the keyboard to open for inputs.

**Comment by brittanygay** [comment]
Edits have been merged. This will be ready for QA on the next deployment.

**A few things to break out into separate bug tickets @Mcscott142 and @zmelamed :**
1. The inputs don't actually save when you change anything (placeholders are always there). I see the mocks are updated to include a Save button so I'm assuming we will be creating a new ticket for these updates (check out latest screenshots here: https://github.com/revelrylabs/bn-mobile-react/pull/207)

2. Billing Information screen needs to be updated with same styles and full width selectable inputs (create new ticket)

**Comment by brittanygay** [comment]
I broke #2 out into it's own ticket (#211)

We still need clarification on where to move forward with #1
