### ISSUE TITLE
Doorman - Scanner - Open Scanner

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#196]
## Background 
The doorman needs the ability to Scan barcodes/tickets to the events. Once they select an Event from their Event list, they should be directed to a Scanner where they can check in guests. 

This has been implemented in the web app: https://github.com/big-neon/bn-front-door

## Scenario: A Doorman opens the scanner for an Event
- [ ] When I select an Event in my Event List
- [ ] Then I see a view from the scanner
- [ ] And the Check-In Mode
- [ ] And the Last person scanned if someone had been previously scanned

### Mocks: 

Video of Flow: https://vimeo.com/298395671

Looking for the Barcode:
<img width="337" alt="big_neon" src="https://user-images.githubusercontent.com/6877299/47917249-dc665000-de76-11e8-89e5-344d68c2ec64.png">

**Comment by brittanygay** [comment]
@chas-mcmahon I think you'll need to set up a new view for this before I can stub out any styles :)

**Comment by chas-mcmahon** [comment]
@brittanygay I'm still working on dev environment setup, but if I'm not done by tomorrow morning, let's just pair on your computer to work through setting up the new view. I can always finish my env setup later.

**Comment by brittanygay** [comment]
Pairing with @chas-mcmahon now to get the screen set up!

**Comment by daybreaker** [comment]
I have the bar code scanner showing up, and the api code in place. Just havent connected the two yet.

**Comment by brittanygay** [comment]
Thanks @daybreaker! Hopping back on this to finish up the styling

**Comment by brittanygay** [comment]
@daybreaker I just finished up my styling edits and pushed them up. Now I'll pass over to @chas-mcmahon to finish anything else up that Brad mentioned.
