### ISSUE TITLE
Doorman - Scanner - Scan a Valid Ticket Manual Check In

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#197]
## Background
Once a ticket is scanned and the guest is checked in the Doorman should receive a ticket valid message and have the ability to check that guest in. This ticket is for a single guest check in. There will be a slightly different flow for guests with multiple tickets. 

Some example scanner code here: https://github.com/big-neon/bn-front-door. The UI is different but this is a working scanner connected to the API. 

## Scenario: A doorman scans a valid ticket
- [ ] Given the scan results in a valid ticket
- [ ] Then I see that ticket is valid
- [ ] And I see that guests details
- [ ] And a way to Complete that guests Check-in

## Scenario: A Doorman completes the Guest Check-In
- [ ] When I select "Complete Check-in"
- [ ] Then I am directed back to my scanner

### Mock
<img width="340" alt="big_neon" src="https://user-images.githubusercontent.com/6877299/47436793-d385c800-d76c-11e8-9ed9-cc7a9d1ec0a7.png">

**Comment by Mcscott142** [comment]
Leaving this as a draft for now. Have some questions for @zmelamed on the Scanner/Check-In flow. Will discuss during ticket writing/approval today 10-42-18. 

- Manual Scan? That's just selecting a name from a guest list and pressing complete check-in? Not actually scanning anything. 
- Scan - Doorman just scans and guest is checked in or still has to hit complete check-in? 
- Are we scanning separate barcodes per ticket? Or  1 Barcode = mutiple tickets but a guest can xfer them making a new barcode? 
- We've got a couple different mocks for guest check in. Assuming we should use the the first but want to make sure. Or maybe I'm not understanding the difference in these screens. 

<img width="338" alt="big_neon" src="https://user-images.githubusercontent.com/6877299/47443118-4b59ef80-d779-11e8-95c9-4fe8ee768c8d.png">

and 

<img width="335" alt="big_neon" src="https://user-images.githubusercontent.com/6877299/47443173-69bfeb00-d779-11e8-8ff2-82e1c1667377.png">

**Comment by Mcscott142** [comment]
There will be a simplified flow per @zmelamed. We should use the below screenshot. I do still have one question remaining from above comment

>Scan - Doorman just scans and guest is checked in or still has to hit complete check-in? 

![mvp-scan-list-mocks](https://user-images.githubusercontent.com/6877299/47446231-6b40e180-d780-11e8-81e6-7a1c2c037851.png)

**Comment by zmelamed** [comment]
So there are 2 checkin "modes", If the Auto-checkin is active it should auto checkin as soon as it's scanned. Show the success state for 3 seconds, and then switch right back into scan mode. If the auto-checkin mode is not active it will require them to click Complete checkin after scanning. 

I need to update the scan view so you can see the auto-checkin active and auto checkin inactive states more clearly.

There is a 3rd state that the scanner views can take, and that's when someone enters the events scanner view before the doortime for that event has been reached (when the event isn't yet "live"). In that state they can scan tix and search the list to get more info but they won't be able to check-in guests.

**Comment by brittanygay** [comment]
There is still a lot of the UI that needs to be stubbed out for these screens, but I will most likely need to pair with a dev/get these screens set up before I can style them.

**Comment by jwietelmann** [comment]
Continuing work on this unless I hear that something else suddenly bumped its priority.

**Comment by brittanygay** [comment]
@jwietelmann let me know if/when this will need a design pass!

**Comment by jwietelmann** [comment]
Still hitting this with a hammer. It just requires a lot of breaking up of older code and a lot of re-testing.

**Comment by jwietelmann** [comment]
There are a bunch of tickets upcoming that will help clean this up, but it works and looks okay as is.

**Comment by jwietelmann** [comment]
shipped and awaiting QA
