### ISSUE TITLE
Doorman - Events - Event list has no way to return to account

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#199]
## Background
Once a Doorman user enters that area there is currently no way to back out to the Account Profile Again. For consistency's sake, I think we should use the same back functionality as the rest of the Application. 

Mock w/ missing back functionality (My Events screen). 
![mvp-scan-list-mocks](https://user-images.githubusercontent.com/6877299/47445097-ab529500-d77d-11e8-89d6-ed5a37595181.png)

**Comment by brittanygay** [comment]
I think we need some clarification from @zmelamed on this one: I would suggest to keep the same back functionality, but I wanted to run it by you before implementing anything new.

**Comment by zmelamed** [comment]
Keep this ticket open, but what has already been implemented is good enough as we move through the other tickets. Thanks, i've passed this along to our designer as well
