### ISSUE TITLE
Doorman - Scanner - Scan an already redeemed ticket

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#201]
## Background
When a ticket has already been scanned, the Doorman scanning the ticket should receive a specific message that the ticket has been used. 

## Scenario: A doorman scans an already redeemed ticket
- [ ] When I scan a ticket that has already been scanned or checked in
- [ ] Then I see that ticket has already been redeemed

### Mock
<img width="295" alt="mvp-scan-list-mocks_png" src="https://user-images.githubusercontent.com/6877299/47446647-4d27b100-d781-11e8-851f-bf098788eaa7.png">

**Comment by Mcscott142** [comment]
Marking as Blocked, see https://github.com/revelrylabs/bn-mobile-react/issues/238#issuecomment-442079042

**Comment by jwietelmann** [comment]
Unblocked by comment on #238.

**Comment by Mcscott142** [comment]
Pushed back from QA. See comment on https://github.com/revelrylabs/bn-mobile-react/issues/238#issuecomment-443224446

**Comment by Mcscott142** [comment]
The valid ticket scans are good to go. I'm still not getting the `Already Redeemed` message on an already scanned ticket, I get `We found an Issue` so leaving this one pushed back.

**Comment by Mcscott142** [comment]
@jwietelmann FYI, this problem may be based on the API return, see comment above. If that is the case once you dig in, just mark blocked.
