### ISSUE TITLE
Doorman - Scanner - Guest List

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#202]
## Background 
A doorman should be able to manually check in guests if there are problems with a scanner or other circumstances. This is for viewing the list of guests only. 

## Scenario: A doorman pull up the full guestlist
- [ ] When I select All Guests
- [ ] Then I see a list of all guests attending my event

## Scenario: A doorman selects a guest from the guest list
- [ ] When I choose a Guest from the guest list
- [ ] Then I can see their ticket details and check them in manually like in #203 

### Mock
<img width="302" alt="mvp-scan-list-mocks_png_and_big_neon" src="https://user-images.githubusercontent.com/6877299/47447372-f3c08180-d782-11e8-8af6-0a234cc3abeb.png">

**Comment by Mcscott142** [comment]
@zmelamed What is the preferred way to get to the Guest checklist, should the doorman be able to access it directly from the scanner screen?(assuming that's possible) or Do we need to implement the intermediary screen after selecting doorman -> event -> new screen -> Scan tickets view guestlist?

**Comment by zmelamed** [comment]
There are designs to have it viewed directly through the scanner view, there should be a tab at the bottom of the view the can be tapped to pull up the guest list.

**Comment by zmelamed** [comment]
I can't seem to scroll to see the full view, it seems to have a fixed height and I can't scroll all the way to the bottom of the list
