### ISSUE TITLE
Doorman - Scanner - Manual Check In

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#203]
## Background 
A doorman wants the ability to manually check in guests by bringing up their ticket details then selecting to manually check them in. 

## Scenario: A Doorman scans a ticket for a manual check-in
Given I have toggled my Check-In Mode to manual
- [ ] When I scan a ticket
- [ ] Then I see the details of that guest and ticket
- [ ] And I can complete the check-in by selecting `Complete Check-In` button

### Mock
<img width="674" alt="mvp-scan-list-mocks_png_and_big_neon" src="https://user-images.githubusercontent.com/6877299/47524919-99e2b900-d861-11e8-8acc-a2677b99031e.png">

**Comment by Mcscott142** [comment]
Unblocking. AC is good to go.

**Comment by jwietelmann** [comment]
Blocked on https://github.com/big-neon/bn-api/issues/913

**Comment by jwietelmann** [comment]
To be clear about where this is at: You can do everything up to and in including pressing the check-in button. The button just doesn't actually check people in yet because of the aforementioned API bug.

**Comment by jwietelmann** [comment]
@Krakaw I'm not sure if we're doing something wrong, but I'm still not getting `redeem_key` in the guest list API response. It's also missing from the user's ticket QR codes now, and I can't scan a user in either. (That's probably not a new problem. This is the first time I've tried to do QR checkin since I reported the guest list problem.)

**Comment by Krakaw** [comment]
@jwietelmann What event are you trying to get the guest list for? I will investigate.

**Comment by jwietelmann** [comment]
@Krakaw I've been using Flo Rida to test some manual check-in styling stuff.

**Comment by Krakaw** [comment]
@jwietelmann It is based on the door time, the event was only set to start on the 31st. I've adjusted the start time to now so that it shows the redeem keys.

**Comment by jwietelmann** [comment]
Got it. Thanks! Good to go here I think. On to UAT.
