### ISSUE TITLE
Ticket Carousel - Left Edge Getting Cut Off

### ISSUE THREAD

**Issue by brittanygay** [revelrylabs/bn-mobile-react#209]
The left edge of the ticket carousel is getting cut off, but not the right side. We need to look into this issue and put in a fix.

![img_6287](https://user-images.githubusercontent.com/14582709/47461471-7eff3e80-d7a6-11e8-8bbd-0b5fac6d6711.JPG)

**Comment by brittanygay** [comment]
Pulling this in to work on next

**Comment by zmelamed** [comment]
FYI, i was poking around, it seems like moving  

    `paddingHorizontal: globalPadding`

from a `modalContainer` style to `slideWrapper` in ticketWalletStyles largely solves for this. the whole view seems to be taking on padding and hiding. it... other issues that need ot be resolved when you do that. but seems like that's the cause

**Comment by brittanygay** [comment]
Thanks @zmelamed! I literally just found that solution too. Cleaning up the close button issue and then I should be done with this bug ticket
