### ISSUE TITLE
Doorman Event List - Left Edge of Cards Cutting Off

### ISSUE THREAD

**Issue by brittanygay** [revelrylabs/bn-mobile-react#210]
The left edge of the Cards on the Doorman Event List screen is getting cut off. 

The left edge of those cells are chopped off by a few pixels, so it has this sharp corner on the radius instead of just being fully rounded.

![img_6286](https://user-images.githubusercontent.com/14582709/47461757-34ca8d00-d7a7-11e8-9fb9-cfcec00fcf52.jpg)

**Comment by brittanygay** [comment]
I found a good reference to resolve this issue here: https://github.com/facebook/react-native/issues/13760

**Comment by Mcscott142** [comment]
Moving to UAT
