### ISSUE TITLE
Account - Billing Info - Make Full Inputs Selectable

### ISSUE THREAD

**Issue by brittanygay** [revelrylabs/bn-mobile-react#211]
Broken out from #175

The Billing Info TextInputs need updated styles to reflect the changes that were done on the Account Profile screen. 

The TextInputs also need to be fully selectable like the updated Account Profile inputs.

**Comment by brittanygay** [comment]
Pulling this in next

**Comment by brittanygay** [comment]
Updates are merged, this will be ready for QA once deployed

**Comment by Mcscott142** [comment]
I know it wasn't in a Mock or anything but it's very hard to differentiate between the CC number field and the expiration date. It looks like just one feild on the screen. Going to make a ticket for that.
