### ISSUE TITLE
Click Hot this week Event Image from Discover Page

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#215]
## Background
Clicking an Event's Image from the Discover page doesn't take me to that event. Only clocking the Name of the Event directs me to the Show page. 

## Scenario: A user clicks the Event photo
- [ ] When I select an Event Photo under Hot this week
- [ ] Then I am directed to the show page

**Comment by brittanygay** [comment]
I think I might be able to knock this one out, but if not I'll assign over to @daybreaker

**Comment by brittanygay** [comment]
Bug fix is merged. This will be ready once updates are deployed.
