### ISSUE TITLE
Ticket Holder - My Tickets / Ticket Transfer - Choose Transfer option

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#220]
_dependent on #218_
## Background 
A user should be able to select the method for Transferring their ticket, whether it is SMS, email or QR Code scan. 

## Scenario: A User selects tickets to transfer
- [ ] When a user selects their tickets to transfer
- [ ] Then they are given options to transfer those tickets

### Mock
<img width="338" alt="big_neon" src="https://user-images.githubusercontent.com/6877299/47678586-2ce85f80-db90-11e8-9497-d77d9bd9f53c.png">

**Comment by bryanjos** [comment]
@Krakaw could you explain what the `emailOrPhone` parameter for sending tickets can contain and how to know if the user wants to send via email or sms?

**Comment by Krakaw** [comment]
It can contain a valid email address or phone number. If we have the email address as a user on the system we will directly transfer the tickets to them with no delay. Otherwise we send them an email or an SMS with the link to create an account and receive their tickets.

**Comment by bryanjos** [comment]
@Krakaw Got it. Looking at the functionality that exists, a user can:

- Enter an email or phone number of the person to send a ticket to
- Scan a QR code and the email of the person to transfer to shows up in the email/phone text box

Given that and given that this ticket is 6 months old, I'm wondering if things changed at some point and if this ticket should still be worked?

**Comment by iamjoshfrank** [comment]
Moving back to `Icebox` and labeling `blocked` until we get an answer.

**Comment by Krakaw** [comment]
I think we have put this method of sharing on hold for the moment, the backend sends either an SMS or an Email, so the users cannot share via native sharing at the moment.

@zmelamed is this something we will want to happen in the future?
