### ISSUE TITLE
Ticket Holder - My Tickets / Transfer Tickets - Email Transfer

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#221]
## Background
A user should be able to email transfer a ticket to another user for an event. 

## Scenario: A user chooses to email a ticket transfer
- [ ] When I select email from ticket transfer
- [ ] Then my email application opens with a link to accept my transfer

### Mock
<img width="320" alt="big_neon" src="https://user-images.githubusercontent.com/6877299/47679012-29a1a380-db91-11e8-939e-fff40b8e22f1.png">

**Comment by bryanjos** [comment]
@Krakaw how do we create the url used in the email mock up above? Also is this still relevant?

**Comment by Krakaw** [comment]
See #220
