### ISSUE TITLE
Attendee - My Tickets / Transfer Tickets - Ticket Transfer Notification

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#223]
## Background 
As a user who has downloaded Big Neon, when someone initiates a Ticket Transfer to me then I should be notified and able to accept that transfer. 

## Scenario: A user initiates a Ticket Transfer to me
- [ ] Given I have downloaded the Big Neon Application
- [ ] When another user initiates a Ticket Transfer to me
- [ ] Then I receive a notification

### Mock
<img width="339" alt="big_neon" src="https://user-images.githubusercontent.com/6877299/47680001-aafa3580-db93-11e8-9212-e99a740b9863.png">

**Comment by bryanjos** [comment]
The notification has to come from the server. Then we can act on it from the app

**Comment by Krakaw** [comment]
There is a notification that comes through for ticket transfers.

**Comment by bryanjos** [comment]
This as shown in the acceptance criteria is already completed. Moving to UAT
