### ISSUE TITLE
Attendee - Venue - Venue Show Page

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#229]
## Background
When a user navigates through the Application, they should be able to select a Venue and see details of that Venue. Including Location, a Description and upcoming Events. 

## Scenario: A user selects a Venue from an Event Page
- [ ] When I select the Venue from an Even page
- [ ] Then I am directed to an Event Show Page
- [ ] And I see the information represented in the Mock below

### Mock
<img width="171" alt="big_neon" src="https://user-images.githubusercontent.com/6877299/47739943-94f87d80-dc44-11e8-8658-0fd575b601da.png">

**Comment by brittanygay** [comment]
Pulling this in to start stubbing out. I believe I can set up this new screen now that Chas has given me an overview of how to set them up. I'll holler if I come across any issues.

**Comment by brittanygay** [comment]
**Update**:
@chas-mcmahon and I paired to get the new screen set up for the Venue Show page, and I'm almost done stubbing out the content. I plan to finish this up tomorrow.

**Comment by brittanygay** [comment]
**Update**:
I stubbed out styles for the Venue Show page. Passing over to a developer to set up the Upcoming API section.
