### ISSUE TITLE
Truncate Titles on Event Discover Screen

### ISSUE THREAD

**Issue by brittanygay** [revelrylabs/bn-mobile-react#230]
We need to truncate the main artist title and location info on the Event Discovery screen in instances where it might exceed 1 line.

<img width="361" alt="screen shot 2018-10-30 at 4 00 52 pm" src="https://user-images.githubusercontent.com/14582709/47750386-4d322000-dc5d-11e8-81d5-d6fa8af4847f.png">

**Comment by brittanygay** [comment]
Working on this next until #218 is ready for me to pick up

**Comment by brittanygay** [comment]
@zmelamed I ran into a UI issue here: if the name of the venue is too long, we can truncate it but there's an issue with how the date is sitting to the right of the location info. Because of instances like this, I would suggest we re-arrange how this line is laid out. 

If we do have to keep it this way, I think there's a plugin we can use to truncate a certain number of characters that I can look into.

<img width="340" alt="screen shot 2018-10-31 at 10 45 48 am" src="https://user-images.githubusercontent.com/14582709/47800716-d6e3fb00-dcfa-11e8-9f04-13d9462eb8a6.png">

**Comment by Mcscott142** [comment]
related to #189 I assume. Just wanted to connect them via comment.

**Comment by brittanygay** [comment]
Marking as blocked until @zmelamed has a chance to answer the UI question above.
