### ISSUE TITLE
Mobile Infrastructure - Automatically deploy test app on PR merge to develop

### ISSUE THREAD

**Issue by jwietelmann** [revelrylabs/bn-mobile-react#235]
Mobile testing deploys seem to be getting in the way of having tickets smoothly move from This Sprint -> UAT. We should get back to being able to automatically give updates to testers.

**Comment by jwietelmann** [comment]
Assigning to Nick/Aline to discuss why this matters and should get priority

**Comment by bryanjos** [comment]
This is done. Closing
