### ISSUE TITLE
Attendee - My Tickets - Empty States

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#252]
## Background
This may already be implemented, I'm not 100% sure. When there are no tickets in the ticket wallet there should be a message letting the user know this. 

## Scenario: I visit my ticket wallet with no tickets
- [ ] When I am on my Ticket Wallet Upcoming/Past/Transfers
- [ ] And there are no tickets in one or any of those areas
- [ ] Then I see the empty states like in the mocks below

### Mocks
Upcoming
![big_neon](https://user-images.githubusercontent.com/6877299/48153847-d3b5b580-e28c-11e8-857e-8a233d483c2d.png)

Past
![big_neon](https://user-images.githubusercontent.com/6877299/48153885-e62fef00-e28c-11e8-8a3d-b192678b4c3e.png)

Transferred
![big_neon](https://user-images.githubusercontent.com/6877299/48153923-fb0c8280-e28c-11e8-9460-09dcce0e8740.png)

**Comment by brittanygay** [comment]
Pulling this in to start working next

**Comment by brittanygay** [comment]
Updates have been approved and merged. This will be ready for QA after the next deploy

**Comment by Mcscott142** [comment]
Blocked on QA until #281 is complete.
