### ISSUE TITLE
Attendee - My Tickets - Transferred Tickets

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#254]
## Background 
When I transfer a ticket, I want to see a history of those transactions with some detail

## Scenario: A user transfers a ticket and navigates to My Tickets
- [ ] When I select Transferred 
- [ ] Then I see a list of tickets that I have transferred

### Mock 
![big_neon](https://user-images.githubusercontent.com/6877299/48157893-8cccbd80-e296-11e8-8897-384a4cd8e465.png)

**Comment by bryanjos** [comment]
@Krakaw @zmelamed Is there an api call to get a user's transfered tickets? I'm not seeing one when looking through the docs and I don't see them coming through from the tickets endpoint

**Comment by Krakaw** [comment]
We are currently busy with exposing an endpoint to view the user's previous (completed) transfers. However if the person receiving the ticket has not accepted them yet then `pending_transfer` will be true.
