### ISSUE TITLE
Attendee - Checkout / API - Payment Selection

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#263]
## Background
This issue for the user selecting their payment type if they have multiple on their account. If this is an issue for some reason then we can have the user only set up one payment type for now. 

# Scenario: A user selects a Payment Type
Given I have added selected a Ticket Type
- [ ] When I am directed to the checkout screen
- [ ] Then I can select a payment type tied to my user account
- [ ] And I can continue to the next step in the checkout flow

**Comment by daybreaker** [comment]
I'm generating an API Token from the bn-web app locally, and passing them in to the mobile app.  I need to get a PR in for those changes before the PR for this ticket can go through, though

**Comment by daybreaker** [comment]
Oh, also, right now there's only one payment type: Stripe.

I saved the old payment mockup for reference when we eject and add more payment types.

**Comment by jwietelmann** [comment]
Brad says there's something here to do with extra security that was placed on the staging site that is currently breaking this.

**Comment by daybreaker** [comment]
Ugh, yeah. Keith had whitelisted the Revelry IP, but thats not going to help for testing from outside of Revelry is it? We might have to go back to basic auth

**Comment by Mcscott142** [comment]
Working for me. Moving to UAT.

**Comment by Mcscott142** [comment]
Scratch that, moving this one back to catch error when CC info is not filled out. 

Reproduction Steps:
1) Enter only CC number
2) Submit form
3) Hangs up with an Authorizing message

We should either disable the button if all fields are not filled in, or catch the error then reload screen with an alert.

**Comment by daybreaker** [comment]
Joel - is it not sending back a postMessage on validation error? 

Anyways, we'll probably need to be the ones to fix that by pulling down big-neon/bn-web and adding it, since we added the embdedded form.

**Comment by jwietelmann** [comment]
i got a `postMessage` for "the card is invalid" once but i experienced the hanging app thing a bunch of times, and in every case a `postMessage` never arrived.

**Comment by jwietelmann** [comment]
blocked until this is merged: https://github.com/big-neon/bn-web/pull/494
