### ISSUE TITLE
Attendee - Checkout / API - Purchase Ticket

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#264]
## Background
Ticket for integrating stripe and actually purchasing tickets to an event. This will include some design work even though the screens are there. We want to clean up/slim down the payment selections/process

Related Links via @zmelamed
https://stripe.com/elements
https://stripe.com/docs/stripe-js
https://github.com/stripe/react-stripe-elements

## Scenario: A user purchases tickets
Given I have added selected a payment option
- [ ] When I complete a purchase
- [ ] Then my card is charged
- [ ] And I see my tickets in the ticket wallet

**Comment by daybreaker** [comment]
Currently have a cart object being created, have tickets being added, quantity can be updated, fees are being shows, stripe token is stored...

Tomorrow I just need to get it to submit the cart as an order!

**Comment by Mcscott142** [comment]
Able to purchase the tickets. Created a couple of other issues around completing the Checkout flow. #325 and #311. Moving this one to UAT.
