### ISSUE TITLE
My Tickets - Initial Ticket not showing in View on Load

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#280]
When navigating to My Tickets and then selecting an Event, the first ticket does not show on initial load. 

Reproduction Steps
1) Select My Tickets
2) Select an Event
3) Only the background is showing
4) Swipe to View other tickets
5) The Ticket w/ QR code then comes into view

**Comment by jwietelmann** [comment]
Found the probable cause: https://github.com/archriss/react-native-snap-carousel/issues/238

Going to try the `triggerRenderingHack` method as a solution: https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#available-methods

**Comment by jwietelmann** [comment]
`triggerRenderingHack` didn't seem to work :/

**Comment by jwietelmann** [comment]
`removeClippedSubviews={false}` works!
