### ISSUE TITLE
Migrate App to Big Neon owned Accounts

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#290]
## Background
We need to set migrate the application over to the Big Neon owned Google Play and Apple Accounts.

Google Play looks like you have to contact support: https://support.google.com/googleplay/android-developer/answer/6230247?hl=en

App Store Connect seems straightforward but I(@Mcscott142) don't have the right access. 
- http://giacomoballi.com/itunes-connect-app-transfer-to-another-account/#.W_xYtpNKhTY
- https://support.google.com/googleplay/android-developer/contact/appt

ToDo
- [ ] Transfer iTunes Connect app to Big Neon
- [ ] Transfer Google Play app to Big Neon
- [ ] Add Brad, Brittany and Colin as testers in iTunes connect
- [ ] Add Brad, Brittany and Colin as testers in Google Play Store

**Comment by Mcscott142** [comment]
@zmelamed Can you provide us with the Developer account info for the transfer? For iTunes connect we need the Apple ID and Team ID. For Google Play we need an email address and transaction ID. More details [here](https://support.google.com/googleplay/android-developer/contact/appt)

**Comment by zmelamed** [comment]
Is there an account I can just invite to both as admins to do whatever is required?

**Comment by Mcscott142** [comment]
@zmelamed You should be able to add us both colin@revelry.co and daybreaker@gmail.com to your organization for itunes connect and google play store as admins. I'm not sure we'll have access to that transaction id for the google app xfer but we can see once we get logged in. 

@daybreaker, that's ^ the email you use for the stores right?

**Comment by Mcscott142** [comment]
@daybreaker How do we want to do this? Straight up transfer what we have? Set up a new pipeline to a new app with the original bn-mobile-react repo? Trying to think of the easiest transition.

**Comment by daybreaker** [comment]
I think we should continue developing on our fork, and do PRs into big-neon/bn-mobile-react often. Then they can set up deployments from big-neon/bn-mobile-react#master to those stores.

I'm not sure of the best way for us to set up deploys. There's nothing really to "transfer". [I'm using a script](https://github.com/revelrylabs/bn-mobile-react/blob/develop/deploy) that just runs some expo and fastlane commands, tied in to my local keychain for credentials. 

If they want us, as admins, to set up Google and Apple Store things, then thats basically just re-doing everything I did to set up ours, except trying to find a way to do Apple Store with shared credentials instead (maybe by setting up a generic user account in the Apple Store combined with fastlane match)

**Comment by zmelamed** [comment]
We can hop on a call to discuss this, we don't have someone on our team that would be able to hop in and set up deployments and the release pipeline, we'll need to lean on you guys to help us with that so you should have received admin invites, or tell us exactly what to do and I can do it, but that may be harder than just doing it.

**Comment by daybreaker** [comment]
Have a deploy_staging script that builds the app using the staging Release Channel, and pushes to the alpha track in Google, and the Apple Connect Store.

Next steps:

- Write up the steps for Keith and Zach to follow to see if they can get the deploy to work.
- Pair with @jwietelmann to get env-specific config vars working

**Comment by Krakaw** [comment]
Connects to big-neon/bn-api#620

**Comment by daybreaker** [comment]
Should we move this to QA, and make the Multi-User deploy, and Env-specific config vars their own tickets?

**Comment by Mcscott142** [comment]
Broken out https://github.com/revelrylabs/bn-mobile-react/issues/338
