### ISSUE TITLE
Account / Billing Information - Remove Venmo Option

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#301]
## Background 
We need to hide the Venmo option for payment in the App. For this first run, we'll only be using Stripe as a payment. 

## Scenario: A user adds a payment option
- [ ] When I select Billing from within my account
- [ ] Then I do not see an option for a Venmo payment method

**Comment by brittanygay** [comment]
I'm going to pull this in to see if I can properly remove the payment option.
