### ISSUE TITLE
My Tickets / Ticket - Remove Wallet and Transfer Options

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#302]
## Background 
Transferring tickets and adding them to the Apple/Google Wallets will not be ready for the initial launch. We need to remove them.

## Scenario: A user views their ticket
- [ ] When I look at my ticket 
- [ ] Then I do not see
  - [ ] Add to Wallet
  - [ ] Transfer Ticket

**Comment by Mcscott142** [comment]
I'm not sure if this is as simple as hiding those options or will require some design tweaks. Marked it 2 points, feel free to change whoever picks this up.

**Comment by brittanygay** [comment]
Going to pick this up because it most likely requires a few design tweaks upon removal.

**Comment by brittanygay** [comment]
Updates are approved and merged. Ready for QA after next deploy
