### ISSUE TITLE
Links to terms of use and privacy policy

### ISSUE THREAD

**Issue by zmelamed** [revelrylabs/bn-mobile-react#314]
## Background
When creating an account there us mention of the Big Neon Privacy Policy and Terms of Service. We need to link that to the actual Big Neon Privacy policy

>All mention of privacy policy should link to https://www.bigneon.com/privacy.html
>All mention of terms of use should link to https://www.bigneon.com/terms.html

## Scenario: A user selects `Get Started` to create an account
Given I have selected Get Started
- [ ] When I click on `Terms of Service`
- [ ] Then I am directed to or shown the content from https://www.bigneon.com/terms.html
- [ ] When I click `Privacy Policy` 
- [ ] Then I am directed to or shown the content from https://www.bigneon.com/privacy.html

**Comment by Mcscott142** [comment]
Updated AC, @zmelamed Those links are 404, is that 100% where they will be located? or are they just incorrect links? Blocking for now, we can implement with those links but want to make sure they are the correct ones before proceeding.

**Comment by zmelamed** [comment]
Yep, those will be going live this week along with our coming soon page.
You can add those even though they're currently 404ing.
