### ISSUE TITLE
Attendee - Event Detail - Share Event

### ISSUE THREAD

**Issue by zmelamed** [revelrylabs/bn-mobile-react#315]
## Background
Users need the ability to share an Event via the normal app methods. 

Expor Share docs: https://docs.expo.io/versions/latest/react-native/share

Message to share: 
>Check this out, [Event Title] is at [Venue Name]. Tickets are on Big Neon. [link to Big Neon event page]
url:  [link to Big Neon event page]
title: [Event Title] at [Venue Name]
subject: [Event Title] at [Venue Name]
dialogTitle: [Event Title] at [Venue Name]

## Scenario: A user shares an Event
Given I am on the Event Detail page
- [ ] When I select `Share Event`
- [ ] Then I am able to share my event
- [ ] And it includes the message from the Description

**Comment by zmelamed** [comment]
Did you mean to comment and move #317?

**Comment by brittanygay** [comment]
Oops! Picked up the wrong ticket. Thanks for catching that!
