### ISSUE TITLE
Attendee - Venue - Directions to Venue

### ISSUE THREAD

**Issue by zmelamed** [revelrylabs/bn-mobile-react#316]
## Background
Instead of linking to the venue detail, for now we'll link the Venue name to the native app for directions. 

possible solution - NPM package for Maps: https://www.npmjs.com/package/react-native-open-maps

## Scenario: A user views their ticket
Given I have selected the detail for one of my tickets
- [ ] When I select `Get Directions`
- [ ] Then my native Map opens with directions to the Venue

## Scenario: A user views an Event
Given I have opened the detail for an Event
- [ ] When I select Venue name
- [ ] Then my native Map opens with directions to the Venue

**Comment by Mcscott142** [comment]
Updated AC, marked SCORE
