### ISSUE TITLE
Attendee - Event Detail - Activate I'm Interested button

### ISSUE THREAD

**Issue by zmelamed** [revelrylabs/bn-mobile-react#317]
## Background
The `I'm Interested` button on Event detail needs to be functional, whether it is selected on the Event Detail or from the Explore page.

## Scenario:  A user selects I'm interested on Event Detail
- [ ] When I select `I'm Interested`
- [ ] Then that button has a style change letting the user know it has been marked. 

## Scenario: A User selects I'm interested on Explore page
Given I have selected the interested start icon on the Explore page
- [ ] When I navigate to that Event Detail
- [ ] Then the `I'm Interested` button is already activated with the style change

**Comment by brittanygay** [comment]
Adding styles for this now and then passing over to @daybreaker to activate

**Comment by Mcscott142** [comment]
Updated description. I should point out that we don't currently have anywhere to actually view a user's "interested" events.

**Comment by zmelamed** [comment]
There won't be a way to view events you're interested in. Indicating that
you're interested in an event will activate relevant notifications (such as
an event status change, or when an event is almost sold out), a friend
being interested in the event, etc. Though we're not setup with all of
those features, or user feedback to indicate that is what they're opting
into, we want to be able to start building the backend infrastructure
around it which is why it's valuable we have it in the builds. I did
consider removing this, but we had already implemented it on event pages
when it was in the top right of the page, and it exists on the explore
page, so it seems like it should be low cost versus removing it and then
having to add it back in.

**Comment by daybreaker** [comment]
blocked right now on the index page, since user_is_interested field isnt coming back in the event response. Issue: https://github.com/big-neon/bn-api/issues/669

The individual event show page works though.

**Comment by daybreaker** [comment]
Looks like they have a PR in for this, so hopefully tomorrow we can move this over to QA

**Comment by Mcscott142** [comment]
I think this should be unblocked via https://github.com/big-neon/bn-api/issues/669
