### ISSUE TITLE
Externally ticketed events should link to the external url in a web view

### ISSUE THREAD

**Issue by zmelamed** [revelrylabs/bn-mobile-react#318]
Some events will be listed on the platform, but ticketed externally. There will be an is_external attribute and external_url attribute sent back with the event object once this issues is complete: https://github.com/big-neon/bn-api-node/issues/241

For any event that is externally ticketed, the action should say "Get Tickets via Web" and open a browser to the link provided.

No prices should be listed

**Comment by Krakaw** [comment]
Waiting on big-neon/bn-api#632 and big-neon/bn-api-node#244 to be merged

**Comment by zmelamed** [comment]
This is live and unblocked

**Comment by Mcscott142** [comment]
Unable to create or edit an Event to be externally ticketed in order to test.

**Comment by Mcscott142** [comment]
Blocked, it looks like externally ticketed events are still requiring a ticket type and qty so it throws an error message when publishing.

![2018-12-19 09 57 33](https://user-images.githubusercontent.com/6877299/50231528-9f95e000-0374-11e9-9e9f-3eb1628ca8b0.gif)

cc @zmelamed @Krakaw

**Comment by Krakaw** [comment]
Thanks! I'll sort that out now.

**Comment by Krakaw** [comment]
Fixed in big-neon/bn-web#770

**Comment by Mcscott142** [comment]
Unblocking and moving over to QA to test.

**Comment by Mcscott142** [comment]
Ok, this never got worked because of the external events. Moving back to up next. Test Event Cardi B @ Lavo Nightclub for external ticket.
