### ISSUE TITLE
Attendee - Ticket Detail - Screen Clean Up

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#324]
## Background
Since we're not using Avatars on the first go-round we should remove the placeholder Avatar on the Ticket detail screen. 

## Scenario: A user selects their ticket to view  details
- [x] When I view one of my tickets details 
- [x] Then I do not see a mock avatar
- [x] And the Ticket details with QR code fits within the screen

![image from ios](https://user-images.githubusercontent.com/6877299/49394238-f3f45b00-f6f8-11e8-9d7b-f8c91c18d933.png)

**Comment by brittanygay** [comment]
Pulling this in to start on

**Comment by brittanygay** [comment]
Updates are now complete. This will be ready for QA after the next deploy
