### ISSUE TITLE
Pixel 1 Android 9, App crashes on load

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#352]
Critical: Device info: Pixel 1 Android 9 crashing on open

**Comment by Mcscott142** [comment]
Colin to round up this phone.

**Comment by jwietelmann** [comment]
I have a data point to add. CJ ran it on a Pixel 1 through the Expo app like you would during development. (I was asking her if she could dump the error stack for us.) ...It didn't crash. So either we accidentally fixed the issue already, or it only happens with a productionish build.

**Comment by daybreaker** [comment]
hoorayyyyyy  :-/

**Comment by Krakaw** [comment]
I got the following bug after installing from the play store. The screen flickered white a few times, then bluescreened.
![Screenshot_20181213-103745.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b735e86838044001143579e/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cc781476206455f37827d1b66af3006b1300051bff054a5556f9ab8f2fa0e03b74de0d0fead8385f74c76f19acb88018bf13a632c91edbe2e3d7158abd7f37ed998e46341f001c8df95434a99a4dcb5efe59ac.jpg)
![Screenshot_20181213-110423.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b735e86838044001143579e/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cc781476206455f27b24d7b06af3006b1300051bff054a5556f9ab8f2fa0e03b74de0d0fead8385f74c76f19acb88018bf13a632c91edbe2e3d7158abd7f37ed998e46341f001c8df95434a99148cd5af359ac.jpg)

**Comment by Krakaw** [comment]
`npm install --save get-own-property-symbols`
In https://github.com/revelrylabs/bn-mobile-react/blob/7caab471993d9b904792cc38243f84c4878caff5/src/constants/Server.js#L1 
Add `require('get-own-property-symbols');` on line one.

**Comment by zmelamed** [comment]
^ Is this proven to resolve the crash @Krakaw? Can we get that built and pushed to google play @daybreaker

**Comment by jwietelmann** [comment]
(I'll make the change now so we can see if it works once built.)

**Comment by jwietelmann** [comment]
change is made. needs a build to be tested.

**Comment by Krakaw** [comment]
We compiled it and tested on a few devices and it solved the crash on all of those devices. So if the crash is related, then yup. I can upload the build we used if you'd like?

**Comment by daybreaker** [comment]
Had to fix another issue with Proxy. Should be good to go now

(@jwietelmann  anywhere we use Proxy, we need to import 'proxy-polyfill' for android)

**Comment by CjS77** [comment]
🍾 
1.0.8 Works on my Pixel 1 with Android 9.

**Comment by Mcscott142** [comment]
Before build, tested w/ Galaxy S6 Edge Android 5.1.1 and it was crashing. After build The app loads and works. Updating the Android version and running through process again.
