### ISSUE TITLE
Attendee - Checkout / Payment Option - Improve Credit Card form

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#356]
## Background
Combining #354,#355 and this one. 

When entering in CC info, the user is forced to manually choose each field as they fill out CC info. It would be an improvement if the cursor jumped to the next fields after finishing an input. 

There is some bugginess around moving the cursor. 

The form itself takes a while to load, we need a Loading indicator so the user knows there is nothing wrong in the application. 

## Scenario: A user selects Payment and fills in CC info 
- [ ] When I select `Payment` in the checkout flow
- [ ] Then I see a loading indicator until the Web form is open

- [ ] When I finish typing in my Credit Card number 
- [ ] Then the cursor moves to Exp date without me having to select the field (same w/ CVC and Zip

- [ ] When I manually move the cursor inside the field
- [ ] Then I can still delete and add inputs to the form

**Comment by brittanygay** [comment]
@daybreaker let me know if there's any design assistance needed when you get to this. Thanks!

**Comment by jwietelmann** [comment]
I'm going to do the loading indicator (which is on the mobile side) and then put this back for the cursor (which is probably on the web side).

**Comment by jwietelmann** [comment]
Pull request for spinner is open. Cursor still needs addressing.

**Comment by daybreaker** [comment]
Current status: rebuilding Stripe form using individual Stripe Elements for each field instead of the main StripeCard element that has all fields. I tried to find ways to turn off the autoadvance in the existing form, but couldnt find one.

**Comment by jwietelmann** [comment]
👍 That does seem like the right move here for getting enough control to address the annoyances.

**Comment by daybreaker** [comment]
Using individual Stripe Elements is almost worse.

You cant use the keyboard's up and down arrows to switch between form fields for some reason, and also when you click on a new field after finishing one, it closes the keyboard and you have to re-open it again. Been fighting with this almost all day. 

We may have to deal with the original way it was, and eject sooner rather than later for native payments.

**Comment by daybreaker** [comment]
Nope, that was at the end of day monday and i was off yesterday. 

We knew WebView would be a temporary option anyway.

**Comment by Mcscott142** [comment]
Blocked until we Eject, leaving this open for now but we'll probably write up new tickets around Expo-less checkout options.
