### ISSUE TITLE
Event Sharing - Duplicate URL's created on iPhone

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#360]
When sharing an event via iOS, the URL is duplicated in the message. 

![file 4](https://user-images.githubusercontent.com/6877299/49754000-a0df5280-fc7a-11e8-9eb7-9010c6cc2a5c.jpg)

**Comment by jwietelmann** [comment]
@Mcscott142 So this is just on the iPhone? Is is specific to Messages or does it happen this way when shared to other things? (I'm not sure how much control we're going to have other this, and I'm worried if we remove the URL from the text, the URL will stop showing on Android and in other apps.)

**Comment by Mcscott142** [comment]
@jwietelmann This is iOS specific but not only to messages. It duplicates when sharing via email, slack etc. 

The sharing works correctly on Android, URL shows only once. 

@daybreaker Didn't you have a theory behind this?

**Comment by daybreaker** [comment]
my theory was about a different key, but I think its this:

```
message: `Check this out, ${event.name} is at ${event.venue.name}. Tickets are on Big Neon. ${url}`,
url,
```

I bet the share auto-appends the url to the end, but we're also doing it manually

**Comment by jwietelmann** [comment]
That's enough for me to go on, thanks. Getting started on this one.
