### ISSUE TITLE
Doorman - Scanner - Add Chimes for scanning

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#363]
## Background
When a ticket is scanned the Doorman should hear a Chime that lets him know whether the scan was successful or not. 

## Scenario: Doorman scans a Valid ticket
- [ ] When I scan a ticket
- [ ] Then I hear a sound that lets me know the scan was successful

## Scenario: Doorman scans an invalid ticket
- [ ] When I scan a ticket
- [ ] Then I hear a sound that lets me know the scan was not successful

**Comment by jwietelmann** [comment]
doing initial investigation

**Comment by jwietelmann** [comment]
putting this back. making a different one for vibration.

**Comment by jwietelmann** [comment]
This was an idea that came from my head, and then someone brought up vibration and I just did that. Makes more sense than sound in a noisy venue. Closing this.
