### ISSUE TITLE
Developer - Ticket QR Code - Adjust Brightness on tickets

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#364]
## Background
When Scanning a ticket in dim lighting it can be difficult to see. There may be a way to make the Ticket QR codes themselves adjust the brightness level on the screen. 

Scenario: A user opens a ticket QR code
- [ ] When I open my ticket QR code
- [ ] Then the screen brightness goes to max

**Comment by jwietelmann** [comment]
doing initial investigation
