### ISSUE TITLE
`trim` fields prior to validation

### ISSUE THREAD

**Issue by CjS77** [revelrylabs/bn-mobile-react#365]
Creating new accounts. 
Android adds a space automatically when autocompleting.. it looks like this causes account creation to fail (with cryptic validation error) rather than just `trimming` and getting on with it

**Comment by jwietelmann** [comment]
I'm going to make the API proxy object auto-trim string fields so we don't have to go all over the app trimming strings in forms.

**Comment by jwietelmann** [comment]
Changed my mind. Overengineered. Better to let the programmer just use a utility function when updating data from user input, which we don't do in that many places right now.

**Comment by Mcscott142** [comment]
Working for me on when Autocompleting during Sign On
