### ISSUE TITLE
Validation failed is not a helpful error

### ISSUE THREAD

**Issue by CjS77** [revelrylabs/bn-mobile-react#366]
On the account creation screen, bad input just pops up a "Validation error" alert without indicating where/what the issue is. This is a really bad first time UX :(

**Comment by daybreaker** [comment]
I think this is all we get back from the API - we're just displaying the error it sends back.

**Comment by CjS77** [comment]
hmmm. We should try and improve that then. #365 will reduce error rate though

**Comment by zmelamed** [comment]
I have quite a bit of spec around onboarding including error messaging and states that we'll tackle all at once. But yes #365 should get some attention as a critical issue.
