### ISSUE TITLE
Event  information showing null in text

### ISSUE THREAD

**Issue by SWvheerden** [revelrylabs/bn-mobile-react#385]
Event: Event Going 
Time and location: Wednesday, December 12, 2018
Doors 12:00 PM null - Show 12:00 PM null

**Comment by SWvheerden** [comment]
![image](https://user-images.githubusercontent.com/2579813/49921312-d623b480-feb5-11e8-91e5-7058a468c8ff.png)

**Comment by jwietelmann** [comment]
`null` is showing as `EST` for me on this same event
