### ISSUE TITLE
event_time not door_time should be used to figure out sorting and display date

### ISSUE THREAD

**Issue by zmelamed** [revelrylabs/bn-mobile-react#388]
The displayed day of the event should always be the `event_start` date. Appears that the Explore view, Ticket wallet (both the date in the ui and determining if it's past or upcoming), and the time/location section of the event detail page are using the `door_time` date/time stamp to figure out the date of the show to display but should be using the the `event_start` timestamp date.

**Comment by Mcscott142** [comment]
Is _event_start_ not the _door_time_? When creating an event on stage, there is no Event time to fill in. Just Door Time, Show Time, and Set Times for acts.

**Comment by jwietelmann** [comment]
Show Time is `event_start`, I think? Anyway, for the purposes of this ticket, ignore sorting. We have a ticket for the sorting and an API blocker. Just make sure that anything that isn't explicitly about when the doors open is showing the event_start in the UI instead of the door_time.

**Comment by Mcscott142** [comment]
:thumbs_up:, working in that regard. Closing this.
