### ISSUE TITLE
User - Rapid Increase or Decrease of Ticket Count Pops up multiple alerts

### ISSUE THREAD

**Issue by mhlangagc** [revelrylabs/bn-mobile-react#389]
When the quantity of tickets is increase or decreased rapidly an error alert follows up.

![img_3078](https://user-images.githubusercontent.com/5164871/49941090-21f05100-feea-11e8-8bcf-7ac27df4473a.PNG)

**Comment by jwietelmann** [comment]
The error message is now better.

**Comment by Mcscott142** [comment]
When rapidly changing QTY, I'm getting `Alert Unknown error`. 

Keeping this open for a better error message. Opening a new issue for point 2 in comment  here: https://github.com/revelrylabs/bn-mobile-react/issues/389#issuecomment-447375967

**Comment by jwietelmann** [comment]
They keep changing the error format in the API. I can't hit a constantly moving target. Calling this blocked until we confirm the new quantity error is stable.
