### ISSUE TITLE
Attendee - Home/Explore Page - Explore Events

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#39]
## Background
For the initial run, we are not connecting to the Big Neon Database, API or using any real data. All of these screens are essentially "Live Mocks" without real functionality. 

The Homepage needs a list of events for users to explore, links for navigation and way to set/change their location. For this run we won't even have the user login, it will be a single user with dummy profile data, events, and tickets. 

Latest Mocks are kept in the sketch file in this [folder](https://www.dropbox.com/sh/gt7c74ndhk7me5w/AADIxnNPe39Xbq3HJUCXfb9xa?dl=0). Please doublecheck that this screen has not changed before working ticket. Latest screens are in the production ready tab. 

## Scenario: A user is directed to the Homepage
- [x] When I open the App from my smartphone
- [x] Then I am directed to the Homepage
- [x] And I see:
	- [x] Different Events to Explore
	- [x] A place to set or change my location

## Mocks
![ios_app_-_dev_version_sketch](https://user-images.githubusercontent.com/6877299/43805159-556ccc92-9a64-11e8-9a30-26d0968859e3.png)

**Comment by brittanygay** [comment]
Picking this up to work on next

**Comment by brittanygay** [comment]
**Update**:
I'm a little more than halfway done stubbing this screen out. I just finished up the slideshow section, and tomorrow I plan on finishing up the "Upcoming" section. 

Once this is all complete, I'll post screenshots once I create my PR and then I plan on picking up #41 next.

**Comment by Mcscott142** [comment]
Capturing Slack convo feedback from Zach. 

<img width="831" alt="slack_-_revelers" src="https://user-images.githubusercontent.com/6877299/44038041-74aa33e4-9edb-11e8-908f-95151cf7bd99.png">

**Comment by Mcscott142** [comment]
Blocking until we get a testflight app up. (But I will check it locally also).

**Comment by brittanygay** [comment]
@Mcscott142 I have updates coming in my next PR for #41 for the following:
1. tweaked typography and icons throughout the Explore page (font is now set up)
2. Updated the search bar to include icon
3. Navbars will be updated

The only thing we don't have set up yet to show the client is the splash screen, which will be covered in #54 later this week.

Once my PR is merged, this screen will be at a good point to show through TestFlight. I'll update once more so we can get this ticket unblocked.

**Comment by zekewell** [comment]
This passes on iphone.

**Comment by iamjoshfrank** [comment]
passes on android.
