### ISSUE TITLE
Checkout - Incorrect/Failed Credit Card info Causes a non-descript error and the app gets stuck in "Loader state"

### ISSUE THREAD

**Issue by zmelamed** [revelrylabs/bn-mobile-react#394]
Attendee Checkout - Incorrect/Failed Credit Card info Causes a nondescript error and the app gets stuck in "Loader state" in the ticket wallet.

1. Add tickets to cart
2. Add a real credit card number with incorrect cvc number
3. (allows you to add card)
4. Click "Purchase Tickets" to complete purchase
5. A generic error message appears, user gets dropped into ticket wallet, loader spinner blocks the view

Expected behavior:

Error message should inform the user what part of the purchase was erroneous, and leave them in the order summary view to update the information and try to complete the purchase again.

@Krakaw @daybreaker I imagine this may need to be a joint effort?

**Comment by daybreaker** [comment]
In terms of telling them what part was erroneous, all we can do on our end really is display the error message that comes back from the API

As for getting stuck with the spinner on the view, we need to work on our error catching/handling for this part.

**Comment by jwietelmann** [comment]
2 cents: I'm curious what the "generic" error message is. Stripe is likely not going to tell you specifically that the card number or CVC or expiration date was wrong because that would be bad infosec practice.

**Comment by zmelamed** [comment]
I think step 1, though, is making sure that with any error on that final purchase step, we keep them in the summary view to update quantity or change payment method if they want to rather than booting them or trapping them. So maybe there are two separate issues that can be broken out here. Unless the stripe api is delivering us all the info we need to handle this appropriately, and it can all be done through the app and doesn't require @Krakaw and the backend team
