### ISSUE TITLE
App ver 1.0.8, Android 8.1.0, crash on Moto 5Gs

### ISSUE THREAD

**Issue by CjS77** [revelrylabs/bn-mobile-react#396]
App version: 1.0.8
Android ver: 8.1.0
Device: Moto 5Gs

Problem:
App installs, and opens to login screen.

Pressing either login or sign up button crashes app. 

![screenshot_20181214-074550](https://user-images.githubusercontent.com/7573551/49985642-5bba6980-ff75-11e8-9879-5a49c4f0d6d6.png)

**Comment by jwietelmann** [comment]
There might be some clues in here: https://github.com/facebook/react-native/issues/17530

**Comment by jwietelmann** [comment]
*Extremely* helpful comment that seems very promising. I would try this first, as we are definitely using the problematic `underlineColorAndroid` prop in several places: https://github.com/facebook/react-native/issues/17530#issuecomment-416367184

**Comment by jwietelmann** [comment]
Calling my shot: I'm going to remove `underlineColorAndroid` and deal with the style consequences (underlines on inputs) unless they really, really look bad. (Going to have Colin give me impressions after I create a branch.)

**Comment by Mcscott142** [comment]
Convo on this topic in this thread https://revelry-public.slack.com/archives/CC1659FUZ/p1545070906015900. 

>we all, including @Zachary Melamed, understand that any attempt to change the underline color will likely result in the same crash bug, and we're okay with proceeding with a default-colored input underline as a way to get rid of this crash.

>jwietelmann [1 day ago]
the other remaining option is to eject the expo app and handle this in `styles.xml`

>jwietelmann [1 day ago]
if we're cool to pursue the "just leave the default colored underline in there on android" approach, then we'll need brittany to make that decision look prettier.

The 2 options laid out, 1) Eject from Expo and handle in `styles.xml` 2) Leave the default colored lines in and make the styles not look so bad. 

Screenshots live in the PR: https://github.com/revelrylabs/bn-mobile-react/pull/415

cc @zmelamed @daybreaker
