### ISSUE TITLE
Android: exiting Ticket show/QR screen turns brightness all the way down

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#398]
Samsung Galaxy S6 Edge, Android 5.1.1. Does not Happen on iPhone (tested with 6S).

Repro Steps:
1) Open a Barcode/Ticket (The screen brightness goes up)
2) Exit ticket back to the app
3) Screen brightness turns very low, lower than initially opening the ticket

**Comment by jwietelmann** [comment]
Calling my shot and turning the feature completely off for now.
