### ISSUE TITLE
Developer - Analytics - Segment.io

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#406]
## Background 
We're going to use segment.io for analytics, to begin with. This will provide some visibility for the Apps performance, help us improve user experience, uncovering bugs, allow Big Neon to track business-specific events.

We should be able to hook it up using with the Keys @zmelamed provided us. Poke @Mcscott142 when picking up this ticket and he'll DM the keys. 

Docs: https://segment.com/docs/config-api/

## Scenario: A developer hooks up segment.io
- [ ] When I am given the keys
- [ ] Then I follow the documentation on segment.io to hook in analytics

**Comment by Mcscott142** [comment]
@zmelamed I think we need to get some more specifics laid out for this. Like which metrics are we wanting specifically and also need any credentials Big Neon has for Segment. 

Link: https://segment.com/docs/spec/

**Comment by Mcscott142** [comment]
Bump on this one @zmelamed.

**Comment by Mcscott142** [comment]
@zmelamed To shoot over segment creds and we'll turn it on, once those are in hand. 

Then we can figure out the tracking we want to add.

**Comment by Mcscott142** [comment]
Updated AC, I have keys. Moving to `Up Next`

**Comment by zmelamed** [comment]
This is pretty straight forward to just get it initialized it looks like: https://docs.expo.io/versions/latest/sdk/segment
```
import { Segment } from 'expo';
Segment.initialize({ androidWriteKey, iosWriteKey })
```
I have separate keys for staging and production that I've sent @Mcscott142 

I'd like to get a build with it initialized to see what mobile tracking we get turn key... then we'll dive deeper into identity and event tracking.
