### ISSUE TITLE
User - Onboarding - Improve Sign Up Experience 

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#408]
## Background

Improve Onboarding experience by breaking up the form fields and adding in screen transitions. Eventually, we'll add in enabling notifications and adding an optional profile picture.  

We'll follow the flow from the video at the url quoted below. For now, we'll skip the Notifications(#409) and the Profile Picture (#418). 
> Onboarding/First time user experience improvements (https://www.dropbox.com/s/jiflvjizeywykd5/Sign_in_28_11_2018_only_popup.mp4?dl=0)

## Scenario: A user signs up for Big Neon
Given I have opened the Big Neon App
- [ ] When I select `Get Started`
- [ ] Then I see the screen transition
- [ ] And I am able to enter in my email and password
- [ ] When I select `Let's do this`
- [ ] Then I see another screen transition
- [ ] And I'm able to enter my First and Last Name
- [ ] When I select `That's me. Let's find some shows`
- [ ] Then I am taken to the Explore page

**Comment by jwietelmann** [comment]
This seems semi-redundant to some other tickets that already had work done. Need to evaluate current behavior against these AC and figure out what's still missing.

**Comment by jwietelmann** [comment]
I checked the AC against what we already shipped in other tickets. This is done.
