### ISSUE TITLE
User - Onboarding - Enabling Push Notifications

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#409]
_depends on #408_ 

## Background
Enable push notifications during the onboarding process. 

>User - Enabling Push Notifications (Expo Notification, enable at the end of onboarding (https://www.dropbox.com/s/zxqds2jc3l1cvua/Signup_Notifications_10_12_2018.mp4?dl=0) 

## Scenario: A user signs up for Big Neon
Given I have started the Onboarding process and gone through the name screen
- [ ] When I select `Turn Notifications On`
- [ ] Then I get the Prompt to allow or don't allow push notification
- [ ] When I select an option
- [ ] Then I am taken to the Explore page

**Comment by Mcscott142** [comment]
Updated AC, marked `SCORE`. I think we'll need some design work on this one.

**Comment by jwietelmann** [comment]
I can get started on the basics of this, but we shouldn't enable it until we can at the very least send the push token to the API. (Ideally, there would also be an actual push notification we could test against.)

**Comment by daybreaker** [comment]
Also, when referring to the docs, make sure youre looking at sdk31 docs. I think it changed some Notification field names from sdk27

**Comment by Krakaw** [comment]
https://big-neon.github.io/bn-api-node/classes/_resources_namespaced_user_device_tokens_.userdevicetokensresource.html

**Comment by Mcscott142** [comment]
@jwietelmann Can we get a status update on this one? See the last comment, does that unblock PR #435 or is there work left to be done there?

**Comment by jwietelmann** [comment]
There's still work to be done, but what's left is not huge.

**Comment by jwietelmann** [comment]
Ran into a problem: https://github.com/big-neon/bn-api/issues/896

**Comment by Krakaw** [comment]
It was a permission issue on the DB which has been resolved.

**Comment by jwietelmann** [comment]
*TESTING NOTES*: if testing in development, you must be logged into expo on your local CLI and the expo app. to log into expo CLI, run `npm run expo -- login`

**Comment by Mcscott142** [comment]
Works on iOS, need software updates on my android device before passing.
