### ISSUE TITLE
Attendee - Navigation - Navigation Bar

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#41]
## Background
The navigation bar should include a link to the Home/Discover page, the user's ticket wallet and their profile. At this point, I don't think we need an actual login screen since we aren't going to connect to a database. 

Latest Mocks are kept in the sketch file in this [folder](https://www.dropbox.com/sh/gt7c74ndhk7me5w/AADIxnNPe39Xbq3HJUCXfb9xa?dl=0). Please doublecheck that this screen has not changed before working ticket. Latest screens are in the production ready tab. 

## Scenario: A User opens the App
- [x] When I open the app from my device
- [x] The I see a Navigation bar with
	- [x] Explore (homepage) icon
	- [x] My Wallet Icon
	- [x] My Account icon

Mock:

![image](https://user-images.githubusercontent.com/6877299/43805228-9668c3fe-9a64-11e8-8517-f8fdd8fa2f68.png)

![ios_app_-_dev_version_sketch](https://user-images.githubusercontent.com/6877299/43805240-a63b4c16-9a64-11e8-8787-8848fd23a37f.png)

**Comment by brittanygay** [comment]
Pulling this in to work on now, branching off of my branch for #39 since it's still in review.

**Comment by brittanygay** [comment]
Assigned to @daybreaker to help look into two issues I had trouble with setting up in React Native. After that I plan on finishing up the styling and then this ticket will be ready for review.

PR with more information can be found here: https://github.com/revelrylabs/bn-mobile-react/pull/62

Once my PR is merged, I'll update this ticket once more.

**Comment by zekewell** [comment]
This Passes. 

Slightly confusing because the icons have different names than the AC, but works.

**Comment by iamjoshfrank** [comment]
Agreed. Updated the AC to reflect the "Homepage" is actually the Explore tab for discovery.

Closing.
