### ISSUE TITLE
Attendee - Checkout - Ticket Qty selected is greater than available tickets

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#414]
## Background 
We need a plan for the below comment.

>The counter lets you select a number of tickets that is not available. I'm not sure what the behavior should be yet for this. We should probably come up with a way to handle it that presumes the number of available tickets will change a lot while you're checking out?

Scenario: A user has selected a QTY of tickets that are not available
Given...
- [ ] When I am changing the QTY tickets
- [ ] Then I see an Updating message while the system check if that QTY is available

**Comment by Mcscott142** [comment]
Connected @jwietelmann 's PR, needs AC.

**Comment by jwietelmann** [comment]
blocked on either https://github.com/big-neon/bn-api/issues/800 or https://github.com/big-neon/bn-api/issues/804 getting done :(

**Comment by Mcscott142** [comment]
#800 is closed. Unblocking this one @jwietelmann

**Comment by Mcscott142** [comment]
Moving to UAT.
