### ISSUE TITLE
Attendee - Account  - Upload a Profile Picture

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#418]
## Background
A user needs the ability to add a Profile Picture. They can do this upon signing up for the App or later via their Account page. 

## Scenario: A user uploads profile pic on their Account page
Given I am logged into my Big Neon Account
- [ ] When I navigate to my Account Details
- [ ] Then I can upload a Profile Picture and save it

**Comment by jwietelmann** [comment]
saving this link for myself: https://cloudinary.com/documentation/upload_images#uploading_with_a_direct_call_to_the_api

**Comment by jwietelmann** [comment]
possible bad news: https://github.com/cloudinary/cloudinary_npm/issues/56

going to see if i can hand-code my way around needing this library

**Comment by jwietelmann** [comment]
I managed to hand-code cloudinary api requests with no problem. We're on our way here. Everything's good.

**Comment by Mcscott142** [comment]
Looks good, moving to UAT.
