### ISSUE TITLE
Attendee - Ticket Transfer - Initiate transfer via Phone or Email

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#420]
## Background 
The initial functionality for ticket transfers will just be transferring via a phone number or email. We'll implement QR codes and more bells and whistles later. 

Via Slack from @zmelamed 
>So ticket transfers does look pretty straight forward to send directly through the api. If we can easily access the address book (I have to imagine there's an expo plugin for that) you just need to run this:

Snippet from BN API:
```
 Bigneon()
            .tickets.transfer.send({
                ticket_ids: ticketIds,
                validity_period_in_seconds: 60 * 60 * 24, //TODO make this config based
                email_or_phone: emailOrCellphoneNumber
            })
            .then(response => {
                this.setState({ isSubmitting: false }, () => {
                    this.onClose();

                    notification.show({
                        message: "Ticket transfer link sent.",
                        variant: "success"
                    });
                });
            })
            .catch(error => {
                this.setState({ isSubmitting: false });
                console.error(error);
                notification.showFromErrorResponse({
                    error,
                    defaultMessage: "Send tickets via email or phone failed.",
                    variant: "error"
                });
            });
```

## Scenario: A user transfers a ticket via phone number or email
Given I am looking at my tickets
- [ ] When I select transfer ticket
- [ ] Then I can initiate a ticket transfer by entering a phone number or email

**Comment by daybreaker** [comment]
Looks easy in theory: https://docs.expo.io/versions/latest/sdk/contacts

I'll work on it today to see.

**Comment by daybreaker** [comment]
I have a branch `420-transfer-tix` that includes selecting tickets you want for transfer, as well as a bug fix for qr codes not showing up on just added tickets.

Since the transfer ticket window is a modal, and modals cant navigate, we might need to do the same content switching inside the modal that we did in the Event Ticket/Checkout path.

Because we're also going to need new screens in this same flow for 1) selecting who to send tickets to, and 2) confirming the # of tickets and recipient. (where the actual API call will be made)

**Comment by jwietelmann** [comment]
Filed this API issue for dealing with email/phone validation. I think it would be a bad idea for web and mobile teams to handle that independently of the API. https://github.com/big-neon/bn-api/issues/837

**Comment by Mcscott142** [comment]
See https://github.com/revelrylabs/bn-mobile-react/pull/427#issuecomment-451180464

**Comment by Krakaw** [comment]
https://github.com/big-neon/bn-api/pull/849

**Comment by Mcscott142** [comment]
Issues for this one have been resolved. Tested in Expo and Ticket xfers are working via the Web. Unblocking.

**Comment by Mcscott142** [comment]
Opened #439 for no email validation, moving to UAT.
