### ISSUE TITLE
Doorman - Scanner - Revisit Auto Adjust Brightness

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#423]
related to #364 

## Background
It would be useful to adjust the brightness when opening up a ticket to be scanned so the doorperson could get a scan in a low lit area. 

We worked this with #364 but reverted because of Android behaviour lowering brightness all the way down when closing the ticket.

## Scenario: A user opens a ticket with a barcode
- [ ] When I select my ticket
- [ ] And it brings up the barcode
- [ ] Then my Screen brightness increases for an easier scan

**Comment by Mcscott142** [comment]
Updated AC.

**Comment by bryanjos** [comment]
I'm just going to take the code from the previous PR, put it in and test it.

**Comment by bryanjos** [comment]
Testing on a Google Pixel, I could not get my initial brightness level which caused a crash. 

I made a PR enabling the brightness feature, but also adding in a default in case we cannot get the initial brightness
