### ISSUE TITLE
Attendee - Ticket Transfers - pending transfers

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#424]
## Background
Currently, the only status showing for a ticket is "Purchased" after initiating a ticket transfer. We need to flesh out what happens to a ticket when a transfer is initiated but not accepted.

**Comment by Krakaw** [comment]
https://github.com/big-neon/bn-api/pull/861

**Comment by Mcscott142** [comment]
Waiting on merge for https://github.com/big-neon/bn-api/pull/861

**Comment by jwietelmann** [comment]
This seems like a meta-ticket related to the work we already did. Probably should have been closed before. Closing now. The transfers tab is now showing the pending transfers.
