### ISSUE TITLE
Events - Temp fix for Timezones

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#428]
## Background 
Via @zmelamed in Slack:
>@Colin Scott @jwietelmann @Brad there are some issues we're working to resolve with the displaying dates/times of events properly across platforms/timezones. This is hi-pri and needs to be resolved and deployed asap to the mobile apps. Event times/dates should always be displayed in the timezone of the venue (not the timezone of the user viewing the event). @Keith and team are working through the system to make sure everything is sound and will provide instructions to make sure there is symmetry between the mobile and web representations of the events. In the short term as a patch we need to make sure that all events are being displayed as PST (as this is the only timezone we'll have events available for). We're working on returning the timezone per venue, so hardcoding the PST conversion will be a temporary solution until then.

>To test, the only event currently on production "Rent Control" should be displayed on the client side as Fri Jan 4 9:30 PM PST for the showtime (8:30 PM PST for the door time).

>We need to get a build pushed for review with at least the short term fix tomorrow as it's a blocker to us adding real events to the app.

>Here's the patch that was applied to the web app if you want to just use this solution for now: https://github.com/big-neon/bn-web/pull/854/files (edited) 

## Scenario: A user looks at an event
- [ ] When I open an events details
- [ ] Then I see the Doors and Show times are in PST

## Scenario: A user looks at `My Tickets`
- [ ] When I open an `My Tickets`
- [ ] Then I see the Doors and Show times are in PST for all of my Tickets

**Comment by Mcscott142** [comment]
These times are all out of whack. 

I create an Event (https://beta.bigneon.com/events/13798d62-28d9-475e-8426-24c8e11d3ed4) and set my `Set Time` for 10pm, `Showtime` for 8:00pm and `Door Time` for one hour before showtime. 

On the App I'm getting `Doors at 1:00am - Show at 2:00am`, on the web Event page I'm getting `Doors 5:00 PM - Show 6:00 PM`, and event edit shows my original inputs. 

When I create an event, what timezone is that using? If it's east coast then the App is pulling correctly. Either way all these times need to be showing PST and they are currently all different. 

cc @zmelamed @Krakaw @jwietelmann

**Comment by zmelamed** [comment]
The current working solution is to use moment-timezone (https://github.com/moment/moment-timezone/) and convert any of the event times to UTC and then convert to PST...
```
				const venueTimezone = "America/Los_Angeles"; //TODO: Replace with venue timezone from api once available
				const eventStartDateMoment = moment.utc(event_start);
				const eventDoorDateMoment = moment.utc(door_time);
				const displayEventStartDate = eventStartDateMoment.tz(venueTimezone).format(
					"dddd, MMMM Do YYYY"
				);
				const displayDoorTime = moment(eventDoorDateMoment).tz(venueTimezone).format("h:mm A z");
				const displayShowTime = moment(eventStartDateMoment).tz(venueTimezone).format("h:mm A z");
```

**Comment by jwietelmann** [comment]
What I'm doing on the mobile app is taking the date stamp and using `luxon` (successor to `moment`) to apply either the venue's timezone or `America/Los_Angeles` when the venue timezone is not set.

**Comment by zmelamed** [comment]
Ah, good move getting it prepped for the eventual venue timezones thanks. 

I don't know if it makes a difference with luxon but with moment i needed to do the conversion to UTC before the conversion to the timezone to get it to convert to the timezone properly.

**Comment by jwietelmann** [comment]
@zmelamed Yup! Same thing I just figured out and put in that PR ^
