### ISSUE TITLE
Attendee - Ticket Wallet - Single Ticket/Ticket Show

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#43]
## Background
When a user clicks on an event then the ticket(s) owned for that event come into full view and can be scrolled through.

Latest Mocks are kept in the sketch file in this [folder](https://www.dropbox.com/sh/gt7c74ndhk7me5w/AADIxnNPe39Xbq3HJUCXfb9xa?dl=0). Please doublecheck that this screen has not changed before working ticket. Latest screens are in the production ready tab. 

## Scenario: A user selects a ticket from their wallet
- [x] When I am directed to the ticket show page
- [x] Then I see
	- [x] Event title
	- [x] Event Date
	- [x] Link for directions
	- [x] Barcode for entry
	- [x] "Add to Apple Wallet" option
	- [x] Transfer ticket option
	- [x] Side Scrolling if multiple tickets to one event

## Mock

![ios_app_-_dev_version_sketch](https://user-images.githubusercontent.com/6877299/43805613-0ab37a1e-9a66-11e8-9777-2710898df388.png)

**Comment by brittanygay** [comment]
Pulling this in to work on today

**Comment by brittanygay** [comment]
@daybreaker completed all of the needed functionality. Pulling this back in to finish up

**Comment by zekewell** [comment]
Passes on iphone.

**Comment by iamjoshfrank** [comment]
Good on Android.
