### ISSUE TITLE
Android - Invalid DateTime

### ISSUE THREAD

**Issue by Krakaw** [revelrylabs/bn-mobile-react#433]
![image](https://user-images.githubusercontent.com/41575888/50772072-33ccd600-1295-11e9-80a1-7ca17d2c9126.png)
![image](https://user-images.githubusercontent.com/41575888/50772088-3f200180-1295-11e9-9754-188fd4507a8c.png)

**Comment by Mcscott142** [comment]
I'm not getting any error messages at all when I open the App locally via Expo. I just get `Invalid DateTime` in place of actual times everywhere it's supposed to show Door and showtimes. This only happens on Android devices. @daybreaker @jwietelmann

**Comment by daybreaker** [comment]
This is due to an outdated version of JSC on Expo < 31 which doesn't handle Intl timezone support used by luxon. Possible solution is to upgrade from Expo 27 to Expo 31.

**Comment by daybreaker** [comment]
Running into issues on the 28 -> 29 upgrade. I think it might be due to changes in the Splash Screen API. Android and iOS hang on "Downloading Javascript Bundle 100%" and never proceed to the splash screen animation. However, if you remove the splash screen code, it tries to render the main app (but fails on rendering fonts, because the splash screen is a cover for preloading fonts)

You can sometimes refresh the iOS app and it loads, and maybe 5% of the time you can trick the Android app into loading, but this is obviously not ideal.

**Comment by daybreaker** [comment]
Successfully on SDK 31, and apparently the upgraded JSC is still broken for luxon's setZone. Made a post in their help forum, but going to start the eject process to see how difficult it might be.

Other option might be to switch to moment instead of luxon, even though its a dead library.

**Comment by jwietelmann** [comment]
@daybreaker There's a package called `date-fns` that you might try?

**Comment by daybreaker** [comment]
I'll check it out, but I'm not optimistic:

> Dependency free IANA time zone support is implemented via the Intl API to keep actual time zone data out of code bundles. Modern browsers all support the necessary features, and for those that don't a polyfill can be used.

**Comment by zmelamed** [comment]
Hey guys, @Krakaw has added `localized_times` to the event payloads, so now they just need to be formatted

**Comment by daybreaker** [comment]
handling it on the api side is a way better solution that I shouldve suggested yesterday and I'm upset with myself that I didnt think of it :-P

**Comment by daybreaker** [comment]
I dont think we need to upgrade from 31 to 32 yet - the biggest addition there is interactive notifications from the lock screen, and geofencing if we ever want to do anything with that.

**Comment by daybreaker** [comment]
@Krakaw @zmelamed Is there any way to get the "PST" timezone portion converted to "-0700" or whatever it needs to be?

Luxon's fromISO and fromFormat parsers dont have a way to parse a text-based timezone, just the standard numerical offset notation.

**Comment by Krakaw** [comment]
https://github.com/big-neon/bn-api/pull/865

**Comment by daybreaker** [comment]
@Krakaw Does bn-node-api need to do anything to carry this change over? 

Still getting time strings in localized_times as "2020-12-12T04:00:00PST"

**Comment by Krakaw** [comment]
The PR with the change was merged in, i think maybe a later PR reverted it. I'll investigate and sort it out.

**Comment by Mcscott142** [comment]
@Krakaw any update on this one?

**Comment by Krakaw** [comment]
@Mcscott142 They have been updated. https://beta.bigneon.com/api/events

**Comment by Mcscott142** [comment]
cc @daybreaker ^

**Comment by daybreaker** [comment]
blocked @Krakaw @zmelamed 

Need same localized_time on ticket.index's ticket event object also.

**Comment by Krakaw** [comment]
https://github.com/big-neon/bn-api/pull/875

**Comment by Krakaw** [comment]
This has been merged in.
