### ISSUE TITLE
Ticket Transfer with no email

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#439]
When transferring a ticket without entering an email we get an error. It works with the email entered as it should. We should Alert the user to enter an email and also consider making that field stand out a bit more. 

1) Select My Tickets
2) Select Event/Ticket
3) Select Transfer Ticket
4) Choose Ticket
5) Hit Transfer X Tickets
6) Throws error

![fullscreen_1_15_19__3_28_pm](https://user-images.githubusercontent.com/6877299/51211276-a4e63c00-18da-11e9-94ac-acc90a2510d7.png)

Screen
<img width="305" alt="slack_-_revelers" src="https://user-images.githubusercontent.com/6877299/51215123-8e91ad80-18e5-11e9-82c4-eb8238bbd05a.png">

**Comment by jwietelmann** [comment]
FWIW the reason that we didn't handle the error is that the API didn't start throwing an error on bad/missing email until after we did the work. Before, it would silently fail and say it succeeded.
