### ISSUE TITLE
Update Bottom Nav Text Color

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#441]
The Bottom Nav Text color is coming over as light grey and not matching the mocks. 

Current:
<img width="742" alt="slack_-_revelers" src="https://user-images.githubusercontent.com/6877299/51256690-96943080-196b-11e9-8383-2f844da86769.png">

Mock:
<img width="641" alt="big_neon" src="https://user-images.githubusercontent.com/6877299/51256737-b4fa2c00-196b-11e9-93b6-ed2a72ef9a6d.png">

**Comment by Mcscott142** [comment]
@brittanygay Can you knock this quick one out today?

**Comment by brittanygay** [comment]
Pulling this in to start on

**Comment by brittanygay** [comment]
Updates are now merged. This will be ready for QA after the next deploy.
