### ISSUE TITLE
Transfer Improvements

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#444]
## Background
Catch all draft for @mcscott142 to update

> - While transferring via email appears to work, transferring via phone did not (assuming my phone number wasn't formed properly, but not sure cause it said it was successful)
> - If we're going to use system alert dialogs the title should never be "Alert" especially on a successful result
> - The flow should be: Select Tickets->Click "Transfer X Tickets"->Enter recipient info->Click Complete Transfer->Success Message (The button should not be active if no tix are selected, and the copy should be "No Tickets Selected" in a disabled state not "Transfer 0 tickets...") (edited)

**Comment by jwietelmann** [comment]
Re this...

> While transferring via email appears to work, transferring via phone did not 

See if transfer phone number works on web. I also had a problem with phone and just assumed that it didn't work on the API side, but maybe it's a format thing. Can't really know if it's our fault or not unless we either ask or see if web team figured it out.

Re: this...

> If we're going to use system alert dialogs the title should never be "Alert" especially on a successful result

Then make a ticket to change every alert in the app and say what its title should be. We've got a lot of these. Doesn't really make sense as a transfer enhancement.

Re: this...

> The flow should be...

I think we probably need design to weigh in.

**Comment by zmelamed** [comment]
I think it's in a good enough state right now, all that needs to be added is:
- Client side validation for the recipient info prior to enabling the transfer button
- The ticket that the "Transfer Ticket" button was clicked should be selected when you arrive at the transfer view
- A little work on the post transfer experience, it seems to take a few seconds for anything to happen after the success dialog is tapped, probably some ux improvement in order there
- I added the ticket id to the UI and on the simulator it breaks it to multiple lines properly but on the build it doesn't wrap the text to stay within the bound of the item in the scrollview
- And definitely cleaning up sloppy code where you see fit

**Comment by Mcscott142** [comment]
Think we're covered as far as the list in the last comments. Closing this one lieu of #452, #453, #455 and draft #456
