### ISSUE TITLE
Event Page - Interested button

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#449]
The Interested button is not functioning properly when on an Event page. It shows as highlighted if selected via Explore but the touch is not worikng on Event pages.

**Comment by Mcscott142** [comment]
This looks like it's working on 1.0.18 so maybe @zmelamed worked it in his PR?

**Comment by zmelamed** [comment]
Yeah that's working in the latest build, I didn't touch that code though, wasn't me.

**Comment by daybreaker** [comment]
I wonder if it was a bn-node-api issue that was fixed by upgrading to the latest bn-node-api version.

I felt like this had been working previously, so one of the older api versions may have broken it, then a newer version fixed it.

**Comment by Mcscott142** [comment]
Going to close this one out, will re-open if we run into the issue again.
