### ISSUE TITLE
Checkout - Purchase Ticket - Screen transitions

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#451]
Device: iPhone 8 

When tickets to an event are purchased and the Event falls further down in the `My Tickets` section list, then the user does not see the animation with those tickets populating the screen. 

Only if the event is the top listed event do you get the ticket animation.

**Comment by brittanygay** [comment]
I'm thinking if there's a way to do this design-wise, but maybe there's a way we can reverse the order of purchased tickets so they are listed top to bottom with most recently purchased at the top?

**Comment by brittanygay** [comment]
Picking this up to poke around and see if I can find a solution using styles

**Comment by brittanygay** [comment]
**Update**:
After looking into this and trying to figure out how to fix the order and reading up on some of the React Native Animation docs (https://facebook.github.io/react-native/docs/animated) I'm still unsure how to resolve the issue.

I think this is definitely bug for a developer. Putting this back into the backlog for now.

**Comment by jwietelmann** [comment]
Yeah this is definitely a job for an engineer. Either we should _just once_ pull the ticket out of the list and bring it to the top, or we should figure out a way to jump to the spot in the list where the ticket will show up.

**Comment by jwietelmann** [comment]
If we go with the jump-to-ticket option: https://facebook.github.io/react-native/docs/flatlist#scrolltoindex

**Comment by jwietelmann** [comment]
I have to put this back for the moment, but I think the right tactic here is: Refactor the tickets list into a `FlatList`. Get a ref to the `FlatList`. Whenever the `tickets` or `selectedTicket` prop changes, compute the index of the new selected ticket, and call the `scrollToIndex` on the `FlatList` ref.

**Comment by bryanjos** [comment]
I managed to change to the Flatlist and everything seems to be on par. I'm not just trying to get the list to scroll when a purchase happens

**Comment by bryanjos** [comment]
I've been fighting with React Native and references. I can't seem to get a reference to the FlatList. I tried to see if there was maybe a bug there and tried a ScrollView instead, but the same thing happened.

I think once I figure that out this will be close to done
