### ISSUE TITLE
Ticket Transfer - Email/Phone text out of view when entering info

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#452]
The first 3 to 4 characters are hidden from users view as they're being typed out during a transfer. 

1) Open My Tickets
2) Select a Ticket and Transfer Ticket
3) Begin entering recipient info
4) First 3-4 characters are cutt off from the view

**Comment by brittanygay** [comment]
This also looks like a possible design bug. I can look into this and #453 together

**Comment by brittanygay** [comment]
Pulling this in first, and tomorrow when I'm in the office I can also pull in #453 (since I need an Android from the office to test #453)

**Comment by brittanygay** [comment]
PR is now merged. This will be ready for QA after the next deploy
