### ISSUE TITLE
Use "status" to determine if a ticket is sold out, not ticket_pricing

### ISSUE THREAD

**Issue by zmelamed** [revelrylabs/bn-mobile-react#459]
If a ticket is sold out it will have an attribute `status` = `SoldOut` and should be labeled as sold out

If a ticket is `status`=`Published` and has `ticket_pricing` it should be shown, otherwise don't show the ticket type as an option.

**Comment by jwietelmann** [comment]
@zmelamed I'm going to write what I think you mean. Can you tell me if this is correct?

| `status` | has `ticket_pricing`? | show in ticket list? | label |
| ---------- | ---------- | ----------| ---------- |
| `Published` | no | no | |
| `Published` | yes | yes | `ticket_pricing.name` |
| `SoldOut` | * | yes | "Sold Out" |
| anything else | * | no | |

**Comment by jwietelmann** [comment]
Calling my shot and moving forward this way. If I'm wrong I'll just go back and fix it.

**Comment by zmelamed** [comment]
Yes, sorry for the delay, that looks correct. Thanks
