### ISSUE TITLE
Attendee - Homepage/Discover - Choose Location

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#46]
_related to #97_
## Background 
A user will want to select different cities to see what events are happening that area. 

Latest Mocks are kept in the sketch file in this [folder](https://www.dropbox.com/sh/gt7c74ndhk7me5w/AADIxnNPe39Xbq3HJUCXfb9xa?dl=0). Please doublecheck that this screen has not changed before working ticket. Latest screens are in the production ready tab. 

## Scenario: A User changes their location from the Homepage
- [ ] When I select the location drop-down in the corner of the homepage
- [ ] Then I am given suggested cities to change my location to 
- [ ] When I select a new Location (City)
- [ ] Then I can see it has changed in the top right of the Discover page

## Mock
![ios_app_-_dev_version_sketch](https://user-images.githubusercontent.com/6877299/43805746-9ac9894a-9a66-11e8-839a-b388869be9a1.png)

**Comment by brittanygay** [comment]
@daybreaker I may need you to set up a new screen before I can start working this

**Comment by daybreaker** [comment]
@brittanygay Using https://github.com/sohobloo/react-native-modal-dropdown which should have notes on how to style (hopefully?)

**Comment by brittanygay** [comment]
Thanks @daybreaker! Picking this up to start working

**Comment by brittanygay** [comment]
In order for me to be able to finish this ticket, I need some dev help on the following, CC @Mcscott142:

1. We need to write a function for `renderSeparator` to tell it to not use the default gray borders (I've tried a few things and couldn't get anything to work)

After double-checking this morning, everything else has been styled accordingly :) Hopefully we can knock out this last issue so we can move this ticket forward!

**Comment by brittanygay** [comment]
@Mcscott142 I pushed up my latest updates to `46-choose-location` if you want to hop on that branch and check it out.

**Comment by brittanygay** [comment]
@Mcscott142 I did forget one more thing: 

We do need to find a way to add in the description text "Where are you looking for events?" above the locations. I wasn't able to find the proper way to set this up, because if we stick it in the `locRowOption` function, it duplicates for each location row (see screenshot). Let me know if you want to pair on this/if this doesn't make sense!

<img width="277" alt="screen shot 2018-09-20 at 10 40 33 am" src="https://user-images.githubusercontent.com/14582709/45829941-a18ecb00-bcc1-11e8-8179-9b66986806f7.png">

**Comment by daybreaker** [comment]
@brittanygay would you be able to set the default styling for it to be invisible, and then just use a selector on the :first row object to then set that object to visible?

**Comment by brittanygay** [comment]
@daybreaker yeah let me see if I can hide it using styles. I saw that it was a function that we could easily implement so I wasn't sure what would be better!

**Comment by brittanygay** [comment]
@daybreaker let me see if I can do something of that sort, I don't think it will work though because we can't use selector classes in React Native stylesheets unfortunately :(

**Comment by daybreaker** [comment]
Ahhh didnt know you couldnt use selectors.

the `locRowOption` takes a `rowID`... I wonder if its an index where it just starts at 0 and increments for each row, so we could display it in the first row by doing `if rowID === 0`

**Comment by Mcscott142** [comment]
@brittanygay I added the part from https://github.com/revelrylabs/bn-mobile-react/issues/46#issuecomment-423231487 and pushed it up, the text needs styling. We may need to pair up on the  `renderSeparator` thing, I'm not sure what you need there.

**Comment by Mcscott142** [comment]
Nevermind, I got it. Think this is g2g @brittanygay. Changes pushed assigning to you.

**Comment by brittanygay** [comment]
@daybreaker and @Mcscott142 were able to finish up the functionality and small issues that I couldn't resolve. I just pulled down the branch and cleaned a few last things up.

PR has just been approved and merged. This will be ready for QA once updates are deployed.
