### ISSUE TITLE
Guest list - Give already-redeemed tickets a clear UI treatment so the doorman knows what's up

### ISSUE THREAD

**Issue by jwietelmann** [revelrylabs/bn-mobile-react#467]

**Comment by brittanygay** [comment]
Picking this up next and pairing with @jwietelmann so I can finish up the rest of the UI updates.

**Comment by brittanygay** [comment]
I just pushed up some design edits and commented with screenshots here: https://github.com/revelrylabs/bn-mobile-react/pull/468#issuecomment-459022627

Passing back to @jwietelmann to look over my last note, and possibly pairing to finish that up when he gets time.

**Comment by brittanygay** [comment]
**Update**:
I paired with @jwietelmann to finish up the last few items mentioned here: https://github.com/revelrylabs/bn-mobile-react/pull/468#issuecomment-459056207

This is now ready for review
