### ISSUE TITLE
Attendee - Explore - Search Events

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#47]
## Background 
A User needs the ability to search for events from the explore screen. 

## Scenario: A User selects the search bar to find a specific artist, game etc. 
- [ ] When I select the search bar from the explore screen
- [ ] And I begin to type an artists name
- [ ] Then I see 
	- [ ] Event Results

### Mock 
<details>
<summary>Regular Search Bar</summary>

<img width="328" alt="Big_Neon" src="https://user-images.githubusercontent.com/6877299/54374680-a10e3600-464d-11e9-847e-a1b8aab82df7.png">

</details>

## Scenario: A User selects the search bar but no results are found
- [ ] When I select the search bar from the explore screen
- [ ] And I begin to type an artists name
- [ ] And there are no results
- [ ] Then I see No results in the list

### Mock
<details>
<summary>Empty State</summary>

![big_neon](https://user-images.githubusercontent.com/6877299/48152039-7ae41e00-e288-11e8-9a70-2cd753ba9d6a.png)

</details>

**Comment by Mcscott142** [comment]
For actual searching. Consider pulling events based on timeframe, do all searches locally.

**Comment by Mcscott142** [comment]
Moved to `Up Next`

**Comment by bryanjos** [comment]
I personally think this is too big and should be interated on long term, but going to see how far I can take it.

What I mean is that Suggested Searches could be a story on its own

**Comment by Mcscott142** [comment]
Feel free to break it out as a Draft and I'll update when I get a chance.

**Comment by Mcscott142** [comment]
@bryanjos Screens are accurate, added one more for the regular explore view

**Comment by bryanjos** [comment]
A search bar existed once I reenabled it. Now to make it work

![Simulator Screen Shot - iPhone XR - 2019-03-14 at 11 56 28](https://user-images.githubusercontent.com/1257573/54376081-40342d00-4650-11e9-8ed6-1d55167b83d7.png)

**Comment by bryanjos** [comment]
Where I am at so far:
![Simulator Screen Shot - iPhone XR - 2019-03-14 at 12 31 51](https://user-images.githubusercontent.com/1257573/54378379-2f39ea80-4655-11e9-9029-7102a007bf65.png)

**Comment by bryanjos** [comment]
Split out Suggested Searches into #623

**Comment by bryanjos** [comment]
This just needs a review from @brittanygay before merging into develop.

**Comment by brittanygay** [comment]
Approved by me!
