### ISSUE TITLE
Android - Get GCM Token Failed

### ISSUE THREAD

**Issue by Krakaw** [revelrylabs/bn-mobile-react#474]
This was on a device
10:44
Unhandled promise rejection, [Error: Couldn't get GCM token for device]

Stack trace:
  node_modules/expo/build/logs/LogSerialization.js:145:14 in _captureConsoleStackTrace
  node_modules/expo/build/logs/LogSerialization.js:40:24 in Object.serializeLogDataAsync$
  node_modules/regenerator-runtime/runtime.js:62:39 in tryCatch
  node_modules/regenerator-runtime/runtime.js:288:21 in Generator.invoke [as _invoke]
  node_modules/regenerator-runtime/runtime.js:114:20 in Generator.prototype.(anonymous
  node_modules/regenerator-runtime/runtime.js:62:39 in tryCatch
  node_modules/regenerator-runtime/runtime.js:152:19 in invoke
  node_modules/regenerator-runtime/runtime.js:187:10 in <unknown>
  node_modules/metro/src/lib/polyfills/require.js:201:2 in new
  node_modules/regenerator-runtime/runtime.js:186:15 in callInvokeWithMethodAndArg

**Comment by jwietelmann** [comment]
@Krakaw Need some more context please. Was this tested on a build? Tested locally with Expo? Were you signed into Expo as `bigneon` on both the Expo app and the `expo` CLI?

**Comment by Krakaw** [comment]
This was tested locally on my device running Expo. I was not signed into Expo, I'm assuming that was the issue.

**Comment by jwietelmann** [comment]
Yeah, that's a limitation of Expo. I'm going to just close this. If it rears its head in an unexpected situation, we can file another issue.
