### ISSUE TITLE
Designer - Placeholder Image Purge

### ISSUE THREAD

**Issue by brittanygay** [revelrylabs/bn-mobile-react#475]
We need to go through the app to see which images are being used, and which ones were placeholders & which ones have been removed, then remove those that we don't need.

Once we go through the list, we then need to  update `assets/index.js`  to remove/add those items so the pre-fetching on app load is smoother.

**Comment by jwietelmann** [comment]
i'm closing this because it does not appear to significantly affect load times of anything. the extra assets aren't harming anything, and we might find that we want them as we re-enable the disabled parts of the UI anyway.
