### ISSUE TITLE
Checkout - Purchasing $0 tix throws error and fails - should not require credit card

### ISSUE THREAD

**Issue by zmelamed** [revelrylabs/bn-mobile-react#476]
After trying to purchase a $0 ticket and entering a payment method, an error is thrown and the app gets stuck with a loading modal in the wallet and no ticket gets added to the wallet.

If a cart has tickets and total is $0 a payment method should not be required to complete the ticket purchase.

**Comment by zmelamed** [comment]
@jwietelmann @daybreaker we need to knock this out and get it deployed within the next day.

There is an event on production right now with a free ticket that's happening this weekend and you can't get the ticket on mobile.

**Comment by jwietelmann** [comment]
Blocked on https://github.com/big-neon/bn-web/issues/1030

**Comment by jwietelmann** [comment]
I was able to test and deliver this change by pointing the API at production and then grabbing free tickets from an existing event.
