### ISSUE TITLE
Upgrade Expo to v32 in order to stop asking for Android READ_SMS permission

### ISSUE THREAD

**Issue by jwietelmann** [revelrylabs/bn-mobile-react#477]
Zach said in Slack: "Hey guys, sorry, I just realized version 1.0.18 never got properly released on android... did we intentionally add this "android.permission.READ_SMS" permission in the build? If so what for? It's requiring me to submit a permissions declaration form"

It seems that this problem is fixed in v32 of Expo (we are on v31).

https://forums.expo.io/t/removing-the-read-sms-permission-on-android-for-google-plays-new-policy/17220/24

The other suggested option was to set `permissions` for Android in `app.json` to `[]`, but I suspect that stops asking for _any_ permissions, and of course we need permissions for things. It seems less risky to upgrade Expo than to try to inventory every single permission we may need.

**Comment by jwietelmann** [comment]
Will require some big code changes around camera/QR scanner.

**Comment by zmelamed** [comment]
Why is that? More required than upgrading and adding `permissions`? Does upgrading break the camera/QR scanner?

**Comment by daybreaker** [comment]
I dont know about "big" code changes, but it'll require some. It might just be this: `The onBarCodeRead prop in Camera has been renamed to onBarCodeScanned` but I want to make sure it didnt change anything else about the bar code reader.

**Comment by zmelamed** [comment]
Gotcha, well we have until march 9th it appears to be properly permission'd before it becomes an issue with Google, so lets either get through this with a quick fix, or table it for right now

**Comment by zmelamed** [comment]
Looks like we may need to prioritize this
![Dashboard_-_Big_Neon_-_Google_Play_Console.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59934f6113749d001f2f5c80/125516c66e82c728ace21e0d46cc95892b808ca89ded800e9b7ff9931668227c273bee14578aec2fb3474431030e07c332070107a3a5dc39baa47c32d5065ebe957f5566c36f17a8bed418bb55eb248c46d0b6bc8b1ec8e83d27e08b9d532c5c5446dda0006ceacc09da52e44ae64754a1163666e770317a429518733e26.png)

**Comment by daybreaker** [comment]
There's an error in SDK 32 with postMessage which we use for the Stripe web form.  https://github.com/expo/expo/issues/3168

We can still fix this on SDK31 by setting `permissions: [<list of permissions we need>]`for android   https://forums.expo.io/t/removing-the-read-sms-permission-on-android-for-google-plays-new-policy/17220/40

If the Android app is being updated via OTA updates, maybe we should just wait for SDK 33 which will supposedly have the postMessage fix?

Or, I can try to get a list of all the Android permissions we'll need to add.

**Comment by Mcscott142** [comment]
What's your recommendation @daybreaker? Sounds like we should fix on SDK31 and wait for 33.

**Comment by daybreaker** [comment]
using the permissions array _might_ be ok, but I'm worried it will re-ask everyone for permissions who has already approved them, or that we'll miss something that needs permissions.

Those are just minor concerns, and we should probably do it this way, since there's no guarantee when SDK 33 will come out.
