### ISSUE TITLE
Attendee/Ticket Holder - Account - Account Page

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#48]
## Background
When a user logs in they will be able to view their Account and the different options such as editing their profile, setting billing info etc. 

Latest Mocks are kept in the sketch file in this [folder](https://www.dropbox.com/sh/gt7c74ndhk7me5w/AADIxnNPe39Xbq3HJUCXfb9xa?dl=0). Please doublecheck that this screen has not changed before working ticket. Latest screens are in the production ready tab. 

## Scenario: A user selects `Account` in the Nav Bar
- [ ] When I am directed to the Account page
- [ ] Then I see
	- [ ] My Profile Picture
	- [ ] My Name
	- [ ] Account QR Code
	- [ ] My email
	- [ ] Account Details
		- [ ] An link to edit my account
		- [ ] A Link to notification preferences
		- [ ] A link to Billing History
		- [ ] A Link to Order History

## Mocks

![ios_app_-_dev_version__1__sketch](https://user-images.githubusercontent.com/6877299/44347814-73b62c80-a45e-11e8-8895-6479a16fc8d3.png)

**Comment by Mcscott142** [comment]
Updated AC & added Mock.

**Comment by Mcscott142** [comment]
Updated w/ QR code addition

**Comment by brittanygay** [comment]
Pulling this in to work on next

**Comment by daybreaker** [comment]
Lots of android issues:

![screenshot_1535662086](https://user-images.githubusercontent.com/12603/44882661-dd61e200-ac79-11e8-9cd9-a8968cb0ddb9.png)

![screenshot_1535662082](https://user-images.githubusercontent.com/12603/44882666-e357c300-ac79-11e8-91e5-824f8050e272.png)

**Comment by iamjoshfrank** [comment]
Marking `blocked` for myself so that I can split out Android bug into separate issue.

**Comment by zekewell** [comment]
Other than the fact that there is no actual cover or profile photo, this passes on iphone because the placeholders are visable and the links present.

**Comment by iamjoshfrank** [comment]
Opened #84 for the Android bug. Closing.
