### ISSUE TITLE
Doorperson - Should only list upcoming events that the user has permissions to manage

### ISSUE THREAD

**Issue by zmelamed** [revelrylabs/bn-mobile-react#480]
Currently it's just re-listing all the events, there should be a special api endpoint available to pull just events the user has permission to view.

**Comment by jwietelmann** [comment]
@Krakaw What's the right API resource/endpoint for this?

**Comment by Krakaw** [comment]
https://big-neon.github.io/bn-api-node/classes/_resources_events_.eventsresource.html
`events.checkins`

**Comment by jwietelmann** [comment]
We lose some info this way, so I'm going to pause for a minute and see if this can't get done first: https://github.com/big-neon/bn-api/issues/958

**Comment by jwietelmann** [comment]
I'm going to mark this as blocked because it doesn't seem critical to ship before I get the above answer, and it might be a significantly smaller lift (with less potential for bugs and a better UI) depending on that answer. If we need to plow ahead anyway, we can, but it doesn't seem like we necessarily need to.

**Comment by zmelamed** [comment]
We do have more events from other venues, this is a hi priority item

**Comment by jwietelmann** [comment]
Since I haven't gotten any response on https://github.com/big-neon/bn-api/issues/958 I'm just going to rip the venue info out of our doorperson events list UI and plow ahead that way.

**Comment by jwietelmann** [comment]
Pull request is open. Documenting the gotchas:

The door person's event list now shows event name only. No venue name because the venue data isn't present in the API response, and no schedule because the API response doesn't have localized times in it.

**Comment by Mcscott142** [comment]
@jwietelmann or @zmelamed Is there another admin user that doesn't have access to every event that I can use to test with?

**Comment by Mcscott142** [comment]
Nevermind, I can add myself to a team. Disregard last comment ^

**Comment by zmelamed** [comment]
If you login to the beta environment on the web as the super admin, you can goto settings for any of the orgs and invite yourself (using a email you haven’t used) to any of the orgs

**Comment by Mcscott142** [comment]
Got it, sorry for the unnecessary ping. Moving to UAT.
