### ISSUE TITLE
Make App Only Payment form

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#482]
## Background 
We are currently sharing the CC form with the Web App and it is negatively affecting the Mobile App when changes are made. We should create a CC form for Mobile App only. 

- [ ] Make an App specific Credit Card Form

**Comment by zmelamed** [comment]
I believe @Krakaw and team are going to adjust this on the web app side so request from mobile are routed to an app only view, so you don't need to manage this

**Comment by Mcscott142** [comment]
Roger that.
