### ISSUE TITLE
Doorperson - More Specific Errors

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#483]
## Background
If anything goes wrong with a Tiket Scan sans already redeemed ticket then the user is just show `We Found and Issue`. 

It may be helpful if we show the actual error, like doors not open yet etc. 

## Scenario: A doorperson scans a ticket with a problem
- [ ] When I scan a problematic ticket
- [ ] Then I know the exact issue of that ticket

**Comment by jwietelmann** [comment]
I'll try to make the error from the server response pass through to the alert when something goes wrong besides the ticket being already-redeemed.

**Comment by jwietelmann** [comment]
need to test that _successful_ scans still behave before shipping this, and i don't want to break anything before friday night's live test happens

**Comment by jwietelmann** [comment]
Shipped this to QA yesterday. It now:

* Tells you when the QR code is malformed/invalid (the JSON parsing fails; you probably scanned a different kind of QR)
* Tells you when the ticket was already redeemed
* Tells you when the redeem key is missing, and suggests a workaround
* Gives you raw server error response messages when we get an unexpected other error

**Comment by Mcscott142** [comment]
Pushing this one back, a couple of issues happening:

1) When the Error message is "The guest may have pulled their tickets up before the doors..." message it displayed, it stays on the display even when the scanner is exited out of and re-rentered. You have to close the app and re-open to get it to go away.

2) Currently, I'm getting the same message ^ even if the ticket is valid. 

cc @jwietelmann

**Comment by Mcscott142** [comment]
Looks good! Moving to UAT.

**Comment by Mcscott142** [comment]
Checked stage build via TestFlight/Google Play and looks good to me.
