### ISSUE TITLE
Unable to Scroll Guest List

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#484]
When pulling up a Guest List for an event, the doorperson is unable to scroll to see all of the guest tickets.

**Comment by jwietelmann** [comment]
I would like @brittanygay to help with this. Willing to pair if she needs any eng help. I just personally hit a wall trying to figure out why ScrollView wouldn't scroll and suspect it's a flexbox layout thing.

**Comment by jwietelmann** [comment]
I created a pull request branch for Brittany to work off of. Basically, it makes scrolling work... except that there is some of the list cut off. Which I need help figuring out. https://github.com/revelrylabs/bn-mobile-react/pull/492

**Comment by jwietelmann** [comment]
Still waiting for some help on making those last 2-3 guests in the list not be cut off.

**Comment by brittanygay** [comment]
Pulling this in to work on

**Comment by brittanygay** [comment]
I was able to put in a fix for the issue. More info and screenshots here: https://github.com/revelrylabs/bn-mobile-react/pull/492#issuecomment-460748723

Passing back over to @jwietelmann to review.

**Comment by jwietelmann** [comment]
Will be ready for QA when PR is reviewed/merged.

**Comment by Mcscott142** [comment]
Looks good on both UAT and iOS. Moving to UAT.
