### ISSUE TITLE
Serve optimized cloudinary images to save data costs

### ISSUE THREAD

**Issue by Jasonvdb** [revelrylabs/bn-mobile-react#487]
bn-api currently returns `promo_image_url` which is the original uploaded image that can sometimes be around 4mb.

Because we're using cloudinary at the moment we can request a much smaller version which still looks fine on mobile.

bn-web has this helper function you can just copy which does the URL manipulation: 
https://github.com/big-neon/bn-web/blob/master/src/helpers/optimizedImageUrl.js

**Comment by jwietelmann** [comment]
Shipped to QA yesterday. Pulling low-quality optimized images for all Cloudinary URLs. For QA I suggest just making sure that you see all the remote image assets you expect to see.

**Comment by Mcscott142** [comment]
I see all expected images, moving to UAT
