### ISSUE TITLE
Doorperson - Blur and darken barcode scanner when feedback message is showing

### ISSUE THREAD

**Issue by zmelamed** [revelrylabs/bn-mobile-react#509]
After a scan the scan response should have transparent "frosted" dark background so you can easily read the response while it's on the screen.

![image](https://user-images.githubusercontent.com/456953/52740398-cdb82a80-2f87-11e9-83e5-4e7166c47379.png)

**Comment by brittanygay** [comment]
@jwietelmann it looks like you handled the blur overlay in your PR, but I wanted to double-check to see if this still needs any attention from me

**Comment by jwietelmann** [comment]
@brittanygay no help needed here; thanks!
