### ISSUE TITLE
Developer - Set up Typeface and Icon Set

### ISSUE THREAD

**Issue by brittanygay** [revelrylabs/bn-mobile-react#51]
## Background 
We need to finish setting up the Typeface and Icon Set for the app. 

All .ttf typeface styles have been added in `/assets/fonts/`.

After doing some quick research, I believe we can set up the iconset by installing a React component (ex: `react-native-vector-icons/MaterialIcons`)

## Scenario: Set up the following:
- [x] Typeface
- [x] Iconset (sync with @brittanygay on this, preferably Icomoon, Material Icons or FeatherIcons)

**Comment by brittanygay** [comment]
Assigning to @Mcscott142 to approve

**Comment by brittanygay** [comment]
I was able to easily pull in Material Icons and get that working @Mcscott142 if we want to update the AC and remove that criteria.

**Comment by Mcscott142** [comment]
Will just mark that piece as done.

**Comment by jwietelmann** [comment]
Pretty sure I did the typeface. Moving this to QA for @brittanygay to check on master.

**Comment by brittanygay** [comment]
Typeface is loading properly and looks like all of the font weights are working! Moving to UAT

**Comment by iamjoshfrank** [comment]
Typeface looks consistent on Android.

**Comment by zekewell** [comment]
Typeface looks consistent on iphone. passes
