### ISSUE TITLE
Ticket Wallet - If a ticket is upcoming and the redeem_key is not available don't show QR code

### ISSUE THREAD

**Issue by zmelamed** [revelrylabs/bn-mobile-react#510]
If a ticket is for an upcoming and there is not sufficient data for the ticket to be checked-in (ie. missing redeem_key) hide the QR code and add the copy:
"To protect you and your purchase against fraudulent activity the QR code used to grant access to the event will be hidden until closer to the event door time. 

Screenshots of this ticket may not be honored by the venue."
![image](https://user-images.githubusercontent.com/456953/52741281-db6eaf80-2f89-11e9-93d5-088a64785393.png)

**Comment by brittanygay** [comment]
I just pushed up some styling updates for the QR Code placeholder text. More info and screenshot here: https://github.com/revelrylabs/bn-mobile-react/pull/519#issuecomment-464911529

Assigning back to @daybreaker to finish up!
