### ISSUE TITLE
Guest List - No guests found message

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#514]
When there are no guests on the list. There is some text that says "No guests found" but it's off center and just plain text. 

Not sure if the mocks have this or not but we should clean it up now that people are legitimately using the doorperson functionality.

**Comment by jwietelmann** [comment]
Side note, I think there's also another message that looks like this that says "Hand on a second..." or whatever when the guest list is being searched

**Comment by brittanygay** [comment]
Picking this up to work on

**Comment by brittanygay** [comment]
I fixed the "hang on a sec..." text in an earlier PR, would post a screenshot but it happens too fast to get one. About to do the same style treatment for the "No guests found." message
