### ISSUE TITLE
Long ticket name pushes quantity selector off screen

### ISSUE THREAD

**Issue by daybreaker** [revelrylabs/bn-mobile-react#520]
![simulator screen shot - iphone 7 plus - 2019-02-18 at 12 18 12](https://user-images.githubusercontent.com/12603/52969867-82cb5800-3377-11e9-82e8-48017bc97b49.png)

**Comment by bryanjos** [comment]
For long ticket names, should we truncate the text?

**Comment by brittanygay** [comment]
@bryanjos instead of truncating the text here, I can put in a bug fix to make it wrap correctly so it doesn't overflow the screen width.

**Comment by brittanygay** [comment]
This looks like a design bug that I can put on my radar and pick up this week

**Comment by bryanjos** [comment]
Maybe I can try giving this a shot

**Comment by bryanjos** [comment]
Something similar happens on the Ticket Types screen but does not effect any functionality:

![Simulator Screen Shot - iPhone XR - 2019-03-12 at 16.24.32.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/573e0f9b779d430e00185e3d/125516c66e82c728ace21e0d46db9d97368e82bd80fbff70a74ff5912706147b2610e366308cd320b04c7e41373d5eb1515a5f45f5e48928bbb73e60db181becd7735d70d83e13bea4905ffd5ee075d80b97bcae8f1ec6ec3b73e08fdb1e3a190c4d89ff5c67a8994bca5ff659fd5f17f54d623cbb2f7c29058614672d636d27aef9dd52858361adbd152e56daae.png)
