### ISSUE TITLE
Guest List - A door person should be able to check-in an unredeemed ticket by swiping the list item

### ISSUE THREAD

**Issue by zmelamed** [revelrylabs/bn-mobile-react#522]
## Background
Rather than requiring a door person click through the list item to check-in a ticket, they should have the option of swiping the list time to the right, and if pulled to a specified trigger point the ticket should be checked in.

This makes it easy to quickly check-in multiple tickets on the list.

I found this but do your own digging if this doesn't satisfy our needs https://github.com/jemise111/react-native-swipe-list-view

![03.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59934f6113749d001f2f5c80/125516c66e82c728ace21e0d46b8c7d86fc093bb80e3ba40b01faad67c4471277f02f47f7484b77fe6472b515e0d46ac415a5844eee59b69f7e8682fd70541b8937f5566c7351badbd871fba00bd218d4883beba9801.png)

## Scenario: A doorman checks in a ticket by swiping on a list item
Given I have the guest list open
- [ ] When I swipe on a ticket list item
- [ ] Then I can easily check in tickets

**Comment by Mcscott142** [comment]
Updated AC a little

**Comment by bryanjos** [comment]
I don't know if I know how to figure this out without some help, but going to do some digging first to see if I can. Going to leave the ticket open in case anyone who knows exactly what to do decides to take it.

**Comment by bryanjos** [comment]
So I got swiping to the right to check-in to work, but there is still more work to do in updating the list after and resetting on error.

**Comment by bryanjos** [comment]
![simulator screen shot - iphone xr - 2019-02-19 at 16 40 02](https://user-images.githubusercontent.com/1257573/53052747-2a728400-3465-11e9-8508-28af1ac0b1dd.png)
![simulator screen shot - iphone xr - 2019-02-19 at 16 40 08](https://user-images.githubusercontent.com/1257573/53052749-2a728400-3465-11e9-8baa-667ff54ae280.png)
![simulator screen shot - iphone xr - 2019-02-19 at 16 40 13](https://user-images.githubusercontent.com/1257573/53052750-2a728400-3465-11e9-9649-401587a245cd.png)

**Comment by Mcscott142** [comment]
Swiping for check in and already redeemed tickets works great. We need to account for Tickets that can't be checked in yet because of future times etc. I think basically tickets with no redeem key @bryanjos

**Comment by zmelamed** [comment]
@Mcscott142 @bryanjos see https://github.com/revelrylabs/bn-mobile-react/pull/532#discussion_r258644048

**Comment by Mcscott142** [comment]
Opened #535 to change wording on Swipe. Moving this to UAT.
