### ISSUE TITLE
Guest List - Moving from the guest list detail view back to the guest list should not reset search filter

### ISSUE THREAD

**Issue by zmelamed** [revelrylabs/bn-mobile-react#523]
## Background
We want to clean up the way the Guest List is working and make it as easy a possible on the Doorperson to check in and scan tickets. 

via @zmelamed 
>I should be able to search for a name on the guest list or scroll to a name, click on the ticket to view the detail view, check that ticket in (or choose not to), and go back to the list view, and click in the next ticket for that guest without having to search and scroll again

## Scenario: A doorperson opens the guest list and searches for a name
Given I have searched for a name with multiple tickets on the guest list and navigated to the ticket detail
- [ ] When I check the guest in
- [ ] Or return to the guest list
- [ ] Then my original search is still intact on the list view

**Comment by Mcscott142** [comment]
Updated AC

**Comment by Mcscott142** [comment]
Updated AC and broke out scroll position to #533
