### ISSUE TITLE
Promo Code - After applying a promo code successfully a checkmark should appear and the button should change to "Remove..."

### ISSUE THREAD

**Issue by zmelamed** [revelrylabs/bn-mobile-react#524]
Promo codes need a success state

If a user applies a promo code successfully a checkmark should appear and the "Apply.." button should switch to a "Remove..." button that will remove the promo code and reload the ticket pricing without the promo code applied.

![image](https://user-images.githubusercontent.com/456953/52972984-76dc9780-3371-11e9-9389-68c7f8540b35.png)

**Comment by bryanjos** [comment]
Are there any test promo codes to use in developing this?

**Comment by daybreaker** [comment]
You can log in to the site as an admin, and create one on an event. They're called "Smart Holds" in the system

**Comment by bryanjos** [comment]
@brittanygay do you know if there is a check mark to use for something like the screenshot above?

**Comment by brittanygay** [comment]
@bryanjos we have all of the icon sets set up with a React Native package. If you want to pass your branch over to me when you're ready I can add it!

**Comment by brittanygay** [comment]
Pulling this in for a design pass
