### ISSUE TITLE
Doorman guest list checkin cuts off bottom of list

### ISSUE THREAD

**Issue by daybreaker** [revelrylabs/bn-mobile-react#528]

**Comment by daybreaker** [comment]
User "Colin Scott" has 4 tickets here, but this is as far as it scrolls. You can drag the list up to see the last user, but after releasing your finger, it drops back down below the tabs

![Simulator Screen Shot - iPhone 7 Plus - 2019-02-19 at 16.14.19.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5591a2b1e18ba80f0011f1c1/125516c66e82c728ace21e0d46db9d97368e82bd80fbff70a74ff5912706147b2610e366308cd320b04c7e41584f2ef0041b4f59ecfb892aafab3c72975d02fd80294f75c02310a8a68316ad1da860c910dfe3efce5ecafa3877e18f8919391a51498df85460a0994a9a50f64be34a55b60f2421b72862231acd54206e796d34aaf5d557828060a2bb142956c1e3e4f9045f.png)

Note: Possible that this is fixed after #518

**Comment by daybreaker** [comment]
Ok, issue still exists even after 518

**Comment by bryanjos** [comment]
This seems to be fixed so I'm moving to QA
