### ISSUE TITLE
Guest List - Retain Scroll Position

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#533]
## Background
We want to clean up the way the Guest List is working and make it as easy a possible on the Doorperson to check in and scan tickets. 

via @zmelamed 
>I should be able to search for a name on the guest list or scroll to a name, click on the ticket to view the detail view, check that ticket in (or choose not to), and go back to the list view, and click in the next ticket for that guest without having to search and scroll again

## Scenario: A doorperson opens the guest list and searches for a name
Given I have searched for a name with multiple tickets on the guest list, scrolled down the list and navigated to the ticket detail
- [ ] When I check the guest in
- [ ] Or return to the guest list
- [ ] Then my original search and scroll position is still intact on the list view

**Comment by bryanjos** [comment]
I tried working on this a couple of times last week, but couldn't come up with the right combination of things to do to get it working correctly yet.

**Comment by daybreaker** [comment]
From Friday:

This is a real brain burner. I feel like I’m right on the edge of figuring out an answer. Something centered around making each list item a component, and when we check someone in, we dont reload the entire guest list, we only update that specific list item, that way that list item component re-renders with the new “Checked In” status, but the main index list of guests has never been updated via state or props, so a re-render is never triggered, leaving it in the same position. Then we allow them to do a pull to refresh if they need to refresh the entire list.
