### ISSUE TITLE
Checkout - Declined card throws error then drops you into ticket wallet with loading spinner blocking app

### ISSUE THREAD

**Issue by zmelamed** [revelrylabs/bn-mobile-react#534]
Select Tix
Add credit card info that is valid but will be declined (find test card numbers to reproduce here: https://stripe.com/docs/testing#cards-responses)
Click Purchase Tix
Error message appears, user is dropped into ticket wallet with loading spinner still visible, app is blocked

Should throw validation error and keep you in the cart so you can update your card.

**Comment by Mcscott142** [comment]
Using Test card 4000000000000069 
1) Able to add Card 
2) Selecting purchase tickets gives me an alert
3) Then I'm directed to My Tickets with neverending loading circle on the screen
4) I have to exit the App and re-enter

One more issue, Adding an incorrect Expiration date has similar behavior with loading indicator but it doesn't return me to the checkout screen first.

**Comment by Mcscott142** [comment]
Now that I'm on the right branch this looks good. The error is a little weird but that comes from API right? so passing this one.
