### ISSUE TITLE
My Tickets - Filter Past Events on Event End Date

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#539]
Pull Past Events based on event_end_time if applicable, if not then use Event Start time +6 hours

**Comment by Mcscott142** [comment]
Sorry I'm just getting to the QA on this. Can confirm the events are pulling based on the end date now. I think we should probably sort the Past events with most recent first though, making a separate ticket for that. Pushing this one through.

**Comment by zmelamed** [comment]
Dev branch still shows tickets to active events in the Past events tab. This needs to be resolved before this weekend. Upcoming tab should include all events that end date/time has not yet been reached. Past Events should show events with an end date/time in the past.

**Comment by Mcscott142** [comment]
@zmelamed Can you provide me with a specific Event you're seeing in the wrong place so I can compare the data? I tested this with changing a few event end dates and they all moved to the Past Events tabs. I don't yet see any instances where Events are showing as past Events but are ongoing.
