### ISSUE TITLE
Designer - Loaders/Splash Screens - Animations for Loaders

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#54]
## Background 
In dropbox there are some concepts that could be used for loaders and splash screens. 

Links(These are also linked in the Google Drive): 
- https://www.dropbox.com/s/8fcp4irnrixlntd/Logo.mp4?dl=0
- https://www.dropbox.com/s/yecyav14dgtjrt7/Logo-Cropped-Transparent.mov?dl=0
- Folder: https://www.dropbox.com/sh/18mx0hrp861ctls/AACCiDeiCnZvCfFNGruljJyKa?dl=0

## Scenario: Adding Splash/Load screen animations
- [x] When I navigate through the application
- [x] Then I see splash screens and loaders similar in concept to the links above

**Comment by brittanygay** [comment]
I now  have the video and `react-native-video` installed and set up already. Also assigning to @daybreaker to take a look because there are some rendering issues.

**Comment by brittanygay** [comment]
Jumping back on this to finish up

**Comment by zekewell** [comment]
Checked this on iphone. It seems the splash screen is only loading upon initial launch of the application. 

Did not see splash screen or loaders in other locations.

**Comment by iamjoshfrank** [comment]
Same.
