### ISSUE TITLE
Get Bryan and Colin deploying the App

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#541]

**Comment by bryanjos** [comment]
Currently going through staging deploy script. Will make updates once completed without errors

**Comment by bryanjos** [comment]
Got up to 
```
[12:55:57]: Preparing apk at path 'app.apk' for upload...

[!] Google Api Error: apkUpgradeVersionConflict: APK specifies a version code that has already been used.
```

Going to update the version, but also need to get confirmation about being added to stores

**Comment by bryanjos** [comment]
I got to deploy to google.

Apple I got:

```
Potential server error received: 'insufficient privileges'. Retrying after 10 seconds (remaining: 2)
```

**Comment by daybreaker** [comment]
@bryanjos and @Mcscott142 - did either of yall complete a full deploy yet?

**Comment by bryanjos** [comment]
No still in same spot

**Comment by daybreaker** [comment]
blocked right now, until @zmelamed or someone can add @bryanjos as an App Manager in the App Store Connect

**Comment by Mcscott142** [comment]
Ok, I'm all good on this front. Just successfully deployed staging. I had 2 issues, one my `creds` folder was named incorrectly and two I provided the keystore information. All good now. 

@bryanjos Is still blocked on this and we'll want to get him Deploying ASAP. His permissions need to be updated in App Store Connect to App Manager @zmelamed or @Krakaw

**Comment by zmelamed** [comment]
permissions have been updated

**Comment by bryanjos** [comment]
Was successfully able to publish both Android and iOS. Closing
