### ISSUE TITLE
Check Responsiveness to different Screen Sizes

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#543]
## Background
Some inputs and buttons are not being handled well on smaller screen sizes and when Zooming in.

## Scenario: A user opens the app with a smaller screen size or Zooms in on a form
- [ ] When I am using a smaller screen size
- [ ] Or I zoom in
- [ ] Then the fields, buttons and text adjusts accordingly

### Screenshot example
![image from ios 6](https://user-images.githubusercontent.com/6877299/53369466-e540cd00-3910-11e9-9c9d-4e28445315b5.png)

**Comment by Mcscott142** [comment]
Via @zmelamed on Slack:
>Outside of that I still think we need to test and optimize UI across the app to respond to small devices (4" screens like the iPhone 5s) or devices in Zoomed/Accessibility mode.

@brittanygay Is this something you can poke at this week?

**Comment by brittanygay** [comment]
Pulling this in to work on next

**Comment by achord** [comment]
One option is to change the text size based on the character length of the button text.

E.g. https://codepen.io/borlyjenkins/pen/VRpogW

**Comment by brittanygay** [comment]
Thanks @achord! I've been looking into https://github.com/nirsky/react-native-size-matters and I'm testing to see if it works now.

If not I'm going to see how easy it might be to write that in js so we can use that in places where it's needed.

**Comment by brittanygay** [comment]
Waiting for the next deploy, then this will be ready for QA.
