### ISSUE TITLE
Sign Up Problems

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#544]
We had a report of a user having trouble signing up for the App with an iPhone X. 

John Hawkins was able to sign up via an iPhone X but reported the following:
>On the page where I typed my name/email, I clicked the button to submit and the keyboard went away but didn't do anything. I clicked the button a second time and then it went through.

Need to investigate further. 

Things to test:
- [ ] Large Profile pic edge case
- [ ] General Sign Up on iPhone X
  - [ ] Submit Button performance

Related Messages via Slack 
>Thanks, can someone with an iPhone X try and register, just got a report from one of our investors that he keeps getting stuck on the “make your tickets… yours” page.

>Has anyone tested on the iPhone X in zoomed mode like that? I wonder if its user error because they don’t realize they need to click the That’s Me... button or if the button is broken in iPhone X zoomed... or if it does have something to do with the image upload @Brad

**Comment by Mcscott142** [comment]
Also need to test for large profile pic edge cases

**Comment by daybreaker** [comment]
does this happen on the iphone x simulator too?
