### ISSUE TITLE
Attendee - Ticket Wallet - Multiple Ticket Side Scroll

### ISSUE THREAD

**Issue by thomasknoll** [revelrylabs/bn-mobile-react#56]
## Background 
When a user has multiple tickets, they can scroll from side to side to see each one of them with the QR code for entry. 

## Scenario: A user is viewing an event ticket where they have purchased multiple tickets
- [ ] When I side-scroll through the tickets
- [ ] Then I see each ticket with a QR code
- [ ] A count of the tickets e.g. "2 of 3"

## Mock
![ios_app_-_dev_version__1__sketch](https://user-images.githubusercontent.com/6877299/44348203-677e9f00-a45f-11e8-8868-e1259940e21d.png)

**Comment by Mcscott142** [comment]
Updated AC, marked score.

**Comment by Mcscott142** [comment]
This one is done.
