### ISSUE TITLE
Analytics/Monitoring - Add device info to headers of api calls

### ISSUE THREAD

**Issue by zmelamed** [revelrylabs/bn-mobile-react#570]
Attached to every big neon api request the following custom headers should be added to log device information from expo Constants https://docs.expo.io/versions/latest/sdk/constants/ -- You'll need to handle the some of the headers differently based on device type as android provides less information:

Per https://github.com/big-neon/bn-api-node#install you just add a simple key value json object and pass it into your BigNeon.Server implementation 
Line 51 of Server.js : `export const bigneonServer = new Bigneon.Server({prefix: apiURL, timeout: timeout}, headerJsonHere)`

Headers:

X-BN-DEVICE-NAME = Constants.deviceName
X-BN-DEVICE-MODEL =  Constants.platform.ios.model || Constants.deviceYearClass
X-BN-APP-BUILD = Constants.platform.ios.buildNumber || Constants.platform.android. versionCode
X-BN-USER-AGENT = Constants.getWebViewUserAgentAsync() 
X-BN-INSTALLATION_ID = Constants.installationId

**Comment by jwietelmann** [comment]
zach pr: closing as uat'd
