### ISSUE TITLE
App Rejected - iOS App requires purpose information related to why we need access to the photo library

### ISSUE THREAD

**Issue by zmelamed** [revelrylabs/bn-mobile-react#571]
https://docs.expo.io/versions/latest/distribution/app-stores/#system-permissions-dialogs-on-ios

Should be `"NSPhotoLibraryUsageDescription": "This will allow you to select a photo and upload it to Big Neon as a profile picture"`

**Comment by jwietelmann** [comment]
zach pr: closing as uat'd
