### ISSUE TITLE
Sign Up Issues - No feedback after clicking causing people to click multiple times on signup buttons

### ISSUE THREAD

**Issue by zmelamed** [revelrylabs/bn-mobile-react#580]
There seems to be an issue where when api requests take a few seconds through the signup flow users are clicking the signup button multiple times, thus getting a message that the account already exists because every time they click the buttons it attempts to create another account.

The buttons on the auth flows need to handle low connectivity/slow responses better by switching to a loading/in progress state that disables additional clicks until a server response is returned and informs the user that the request is in progress.

We need need to think more about non-ideal conditions in these flows and ensure that we provide good user feedback in all scenarios.

**Comment by daybreaker** [comment]
#555 added a modal to the last step, but I didnt add one to the middle step. 

Whoever picks this up should look at the PR #555 on how to add a modal and then add a setTimeout in the state provider for the error display, because if you dont, there's an ios UI bug that freezes the app when a modal is closed by an alert.

**Comment by bryanjos** [comment]
Can it be something as simple as disabling the button while the request is taking place?

**Comment by bryanjos** [comment]
Added a PR to prevent multiple requests. Does not handle UI updates but that's the next step

**Comment by Mcscott142** [comment]
I'm still allowed to click multiple times and I get the Alert that email already exists after it transitions to the next screen.

**Comment by bryanjos** [comment]
A draft PR exists for #583 that when completed should apply to this.

**Comment by Mcscott142** [comment]
I think we probably need to make the loading button consistent across the sign up process but opening another issue for that. Button looks good and I can't re-submit.
