### ISSUE TITLE
Guest List Check In / Loading crashes when loss of connectivity

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#583]
I came across a crash and a couple of issues when I interrupted my internet connection / cell service on both iOS and Android. Not sure what needs to be done about this. There will be times when Venues has connectivity issues and we'll need to address this. 

Reproduction Steps
1) Pull Up Scanner
2) Turn Off Internet / Cell Service
3) Check in a Guest via Guest List (Scan gives Network Error Message)

Error:
![screenshot_20190306-142943](https://user-images.githubusercontent.com/6877299/53915134-fb434180-4024-11e9-97c5-a1db816fa1ab.png)

**Comment by bryanjos** [comment]
So the problem is the guest list doesn't show or better indications of no connectivity?

**Comment by Mcscott142** [comment]
I think better indication of No Connectivity. Like when a Scan happens it says Network Error. We need the App not to straight up crash when there is a loss of connectivity. 

A separate issue I'll spin up, we probably need an "offline mode" where they can check in guests via downloaded Guest List when that happens.

**Comment by jwietelmann** [comment]
I feel like you're still inappropriately lumping things together.

* Bug: The app shouldn't just crash
* UI enhancement: I don't like the Network Error copy, and instead I want it to say "blah"
* UI enhancement: Offline indicator

**Comment by Mcscott142** [comment]
All I care about with this ticket is that the App doesn't crash. I will make tickets for the other things.

**Comment by jwietelmann** [comment]
Now the `apiErrorAlert` handles network activity errors, and the guest list search uses this error handler

**Comment by Mcscott142** [comment]
@jwietelmann I'm getting the Alert on iOS but not on Android. I get a Red Error screen. Using a Galaxy S6 Edge.

**Comment by bryanjos** [comment]
I tried to duplicate on a Google Pixel 1 and I got the expected message

https://photos.app.goo.gl/9PDN9Uv21phPt49G6
