### ISSUE TITLE
Busy/Loading Button - UX Enhancement

### ISSUE THREAD

**Issue by brittanygay** [revelrylabs/bn-mobile-react#587]
There are a lot of form double-submitting or waiting for form submits to finish, so it's time that we implement a loading state button.

The button needs to indicate the following:
- [ ] Show that it is disabled
- [ ] Indicates that activity is happening 

My go-to resource for loading states (maybe we can work off of this, but this uses scss so I'll try to find something for React Native):
https://matejkustec.github.io/SpinThatShit/

**Comment by brittanygay** [comment]
Assigning @Mcscott142 to approve/adjust the AC if needed

**Comment by jwietelmann** [comment]
@brittanygay here's a starter i worked up for you:

```javascript
import React from 'react'
import {TouchableHighlight} from 'react-native'

function BusyButtonIndicator() {
  return (
    // whatever you want here
  )
}

function BusyButton({children, isBusy, busyContent, ...touchableHighlightProps}) {
  return (
    <TouchableHighlight {...touchableHighlightProps}>
      {isBusy ? (busyContent || <BusyButtonIndicator />) : children}
    </TouchableHighlight>
  )
}
```

**Comment by Mcscott142** [comment]
Approved

**Comment by jwietelmann** [comment]
Explanation of above code:

* Use `BusyButton` where you would typically use `TouchableHighlight`
* All `TouchableHighlight` props can be used
* Additionally accept two other props:
  * `isBusy` - true/false
  * `busyContent` - optional component
* If `isBusy` is false, render normally
* If `isBusy` is true, do no respond to `onPress`
* If `isBusy` is true and there is not `busyContent` supplied, render a spinner
* If `isBusy` is true and there _is_ `busyContent` supplied, render that, whatever it is

**Comment by bryanjos** [comment]
I'll probably at least stub this out for #580 and then replace with whatever @brittanygay comes up with

**Comment by brittanygay** [comment]
Pulling this in to work on next

**Comment by brittanygay** [comment]
@jwietelmann @bryanjos as I'm working on this ticket, I'm noticing that we do have a spinner modal already implemented after a user signs up with their first and last name. (see screenshot). I'm thinking we should keep that as-is since that form submission takes a few extra seconds. 

I'm still going to go ahead and style the BusyButton for all other instances where we need it, but I did want to point this out.

![Screen Shot 2019-03-08 at 10.23.39 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56154cf43bdd627e00d5004a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77206454fb6b7191a379ef0c2952415c47bc30254d58eeb9cb74fce36f34985619e8836b5b72903a15f8e98618b654ba208a1d8db6bc884bc0fa2137a5dad11b61435c52dcbd4f3fb29842c259f34ee34d53a6103e60e077316e0a.png)

**Comment by brittanygay** [comment]
Updates have been merged. Once the next deploy is made this will be ready for QA.
