### ISSUE TITLE
Android Galaxy S6 - Guest List text overlapping

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#588]
The `Scan Tickets` back button and the `Guest List` Header are overlapping on a Galaxy S6 (Looks fine on iPhone 8). Screenshot below. 

![screenshot_20190307-122038](https://user-images.githubusercontent.com/6877299/53979742-2df84300-40d4-11e9-89b1-500c4e0066e1.png)

**Comment by brittanygay** [comment]
Working on this next

**Comment by Mcscott142** [comment]
This one is g2g, closing
