### ISSUE TITLE
Bug: Scanner keeps scanning when you're on the guest list screen

### ISSUE THREAD

**Issue by jwietelmann** [revelrylabs/bn-mobile-react#590]
Easiest way to reproduce is to point your phone camera at an invalid QR code, open the guest list, and notice that it repeatedly makes the scan failure vibration.

(I suspect the fix has something to do with either componentDidUnmount or react-navigation blur)

**Comment by bryanjos** [comment]
I think the reason is this line here: https://github.com/revelrylabs/bn-mobile-react/blob/develop/src/Accounts/eventScanner.js#L260
