### ISSUE TITLE
Doorperson - Scanner / Guest List - Offline Indicator 

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#592]
## Background 
There should be an indicator if the Application is offline. If the doorperson is having connectivity issues, currently they will be unable to check people in or scan someone in. We should let them know if this is the case. 

## Scenario: A Doorperson loses network connection
Given I have lost my network connection
- [ ] When I am in the Scanner
- [ ] Or searching the guest list 
- [ ] Then I know that I am not connected to the Internet

**Comment by bryanjos** [comment]
I think this should be pulled back. The PR I made only adds non-ui indicators for signifying changes in connectivity. There is still another part required for UI indicators

**Comment by Mcscott142** [comment]
Yep, my bad. Didn't mean to push this one over.

**Comment by bryanjos** [comment]
I am looking for any suggestions for what would be appropriate UI indicators that someone is offline. Anyone have any ideas?

**Comment by Mcscott142** [comment]
@brittanygay You have any input here?

**Comment by brittanygay** [comment]
Finding a solution for this next, then it will most likely need a design pass

**Comment by brittanygay** [comment]
Here's a quick mock of what we could do for the Network Error screen, assuming we don't want the user to have access to click out of it? If not, we can add a close button or make it a modal. What are your thoughts @Mcscott142 @bryanjos?


![BigNeon-Connection-Issue](https://user-images.githubusercontent.com/14582709/54219015-a1c39280-44bc-11e9-9ce1-b5b34cf200b2.jpg)

**Comment by bryanjos** [comment]
I think I'm ok with this if there is nothing they can do without a connection

**Comment by Mcscott142** [comment]
Moving this to Icebox, not sure it's 100% needed at this point with the alert we're already dropping.
