### ISSUE TITLE
Doorperson - Guest List - Loading State Pushes Content Down

### ISSUE THREAD

**Issue by brittanygay** [revelrylabs/bn-mobile-react#606]
When you first click on the Guest List button from the Event Scanner, the Loading State that says "Hang on a second" pushes the rest of the content down that's already available.

What _should_ be happening is to show the Loading State alone before any of the List content is available on the screen.

## Steps to Reproduce
Provide steps to reproduce the issue you encountered.

- [ ] Login as a Doorperson
- [ ] Go to the Doorperson tools
- [ ] Select an event
- [ ] On the scanner screen, click on "Guest List"
- [ ] Observe how the Loading State pushes the List down

Gif better indicating the issue (this happens very quickly but it's still happening):
![loading-state-bug](https://user-images.githubusercontent.com/14582709/54217004-cb7aba80-44b8-11e9-8bb5-dd1d51e52d1a.gif)

**Comment by brittanygay** [comment]
Assigning to @Mcscott142 to approve the AC

**Comment by jwietelmann** [comment]
I actually disagree with the proposed behavior. The loading indicator, IMO, should not block the current content. This will cause ugly flashing. It should either be a modal overlay type of thing, or it should occupy a piece of real estate that is always  the same height whether loading is in progress or not.

**Comment by jwietelmann** [comment]
My other idea is reserving a little space on the right of the search box for a spinner.

**Comment by brittanygay** [comment]
Pulling this in to find a solution

**Comment by brittanygay** [comment]
I like the idea of adding a spinner to the screen, instead of having the loading area push down the rest of the content. I'm going to stub this out to see how it looks, and then I'll assign to one of the devs to finish setting up functionality.

**Comment by brittanygay** [comment]
I was able to add the Loading Modal, but I'm out of time for the week so I have to put this back down. My branch is called `606-loading-bug` if anyone has time to pick this up. Below is a screenshot of what I was envisioning.

![Screen Shot 2019-03-08 at 10.23.39 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56154cf43bdd627e00d5004a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77206454fb6b7191a379ef0c2952415c47bc30254d58eeb9cb74fce36f34985619e8836b5b72903a15f8e98618b654ba208a1d8db6bc884bc0fa2137a5dad11b61435c52dcbd4f3fb29843c259f34ee34855a7173166e776356e0a.png)
