### ISSUE TITLE
Loading Indicator on Transfer button

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#609]
## Background
When tickets are being transferred we should add the Loading indicator we're currently using throughout the app so the button cannot be selected twice if the request takes longer than expected. 

## Scenario: A user transfers a ticket
- [ ] When I select tickets to transfer
- [ ] And I press the button to transfer those tickets
- [ ] Then I see the button indicate that my request is processing.

**Comment by bryanjos** [comment]
Just putting this here so we know what screen is being updated

![Simulator Screen Shot - iPhone XR - 2019-03-13 at 11 20 46](https://user-images.githubusercontent.com/1257573/54296021-20cece80-4582-11e9-9bf0-7c8faea7c0e9.png)
