### ISSUE TITLE
Attendee - Explore Page Heading - Header resize with scroll

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#61]
## Background
The Top Nav should re-size on scroll. See https://www.dropbox.com/s/t53np3mb1rknbq1/Explore-header.mov?dl=0

## Scenario: A user scrolls through events on the Explore page
- [ ] When I scroll through events
- [ ] Then I notice the Header changes size as I move down

https://www.dropbox.com/s/t53np3mb1rknbq1/Explore-header.mov?dl=0

**Comment by brittanygay** [comment]
Pulling this in to start on

**Comment by brittanygay** [comment]
@daybreaker I did some research and came across two tutorials that seem pretty straightforward:

https://medium.com/appandflow/react-native-collapsible-navbar-e51a049b560a

https://medium.com/appandflow/react-native-scrollview-animated-header-10a18cb9469e

I wanted to check with you to see if one of these might be the approach we should take? Let me know and we can move forward from there. Thanks!

**Comment by daybreaker** [comment]
I think the 2nd one with the animated header might be better. The first looks like it just hides the header which we dont want.

**Comment by brittanygay** [comment]
Thanks @daybreaker!

I just pushed up some initial styles for the nav with the basic setup. Passing over to @daybreaker to now take a look at the animation setup.

**Comment by brittanygay** [comment]
Going to continue looking into this to see if I can get some more set up before @daybreaker takes a look

**Comment by brittanygay** [comment]
**Update**:
I passed to @daybreaker and he was able to clean everything up and fix all of the errors. 

I pulled the branch back down afterwards and I was able to get the nav positioning and timing set up properly, but the animation transitions aren't working yet. I've been doing some research (see links below), and trying to set those up properly, but haven't quite gotten it yet.

I'll pick this back up on Monday to take a look with fresh eyes. @daybreaker it might help if we sync on this together on Monday so we can knock it out.

**Links to other references:**
https://medium.com/react-native-training/react-native-animations-using-the-animated-api-ebe8e0669fae

https://facebook.github.io/react-native/docs/animated.html

https://medium.com/dailyjs/how-i-linked-animated-headers-to-scroll-position-in-react-native-1a4906fca25b
(this example is set up a little differently ^)

**Comment by brittanygay** [comment]
@daybreaker I was able to fix the header scroll by changing the `HEADER_MIN_HEIGHT` to `-25`. I also fixed some of the animation timeframes so the header has a dropdown transition.

The only thing I wasn't able to set up was the animation text opacity and how the main header stays outside of the scrollview. 

Pushing up the branch now, let me know if you want to do any last edits before getting this merged!

**Comment by brittanygay** [comment]
PR has been reviewed and merged. More info and a gif can be found here: https://github.com/revelrylabs/bn-mobile-react/pull/90

@daybreaker and I spoke in the Slack channel and agreed to get this merged but to possibly create an enhancement ticket for the last few things we need to clean up cc @Mcscott142 

Once updates are deployed this will be ready for QA!
