### ISSUE TITLE
User Onboarding - Turn on iOS Notifications

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#612]
## Background 
Once Sign Up is completed on iOS a user should be prompted to turn notifications on.
<details>
<summary>Screenshot</summary>

![image (1)](https://user-images.githubusercontent.com/6877299/54234737-b19f9e80-44dd-11e9-87de-3c6c7ca938e5.png)

</details>

## Scenario: A User enables notifications on iOS
Given I have finished the sign-up process on iOS
- [ ] When I select Turn notifications on
- [ ] Then I receive a prompt for allowing notifications

 ## Scenario: A User does not enable notifications on iOS
Given I have finished the sign-up process on iOS
- [ ] When I select `Nah, hopefully I'll figure it out`
- [ ] Then I am directed to the discover page

**Comment by brittanygay** [comment]
Pulling this in to work on before #606

**Comment by brittanygay** [comment]
I just pushed up design updates for this screen. More info and screenshots here:
https://github.com/revelrylabs/bn-mobile-react/pull/615#issuecomment-472531950

This is now ready for review.
