### ISSUE TITLE
Android Scanning tickets causes App to restart

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#617]
This is not happening in Expo, only in the stage deploy for v34. Tested on Samsung Galaxy S6 Edge and Galaxy S5 

iOS Device scans fine. Android devices jump to Splash screen and reload the App. You can use the guest list to check people in, only scanning is the issue. 

1) Sign in with superuser account
2) Scan Valid or invalid ticket in any mode 
3) Splash screen comes up
4) Discover Page is loaded

**Comment by jwietelmann** [comment]
Making a note here that we tried adding the `VIBRATION` permission to `app.json` and are awaiting QA results.

**Comment by Mcscott142** [comment]
That did it. Tickets can be scanned and vibration is working. Closing this one. Tested v35 from google play store using Galaxy S5 and S6 Edge.
