### ISSUE TITLE
Event Images - Event images should have a light grey "skeleton" placeholder while loading

### ISSUE THREAD

**Issue by zmelamed** [revelrylabs/bn-mobile-react#619]
![Skeleton.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59934f6113749d001f2f5c80/125516c66e82c728ace21e0d46db9f9f2f8797a681abf301b44fff9e2c4533317346f62926d1b52ee8167f005b5847f941585e16f4f98929a1b62e6c981e5ab38532022d8c6853beb2901eb80bbb258e4d80b3bd884ec9ef3a21f5c6.png)

**Comment by brittanygay** [comment]
@bryanjos or @daybreaker I think I need some help setting this loading state up, not sure of the best way to get started on this. I can try to stub it out and then we can add functionality later?

**Comment by bryanjos** [comment]
Yeah you can stub it out. Because I have no idea how to add that functionality yet :)

**Comment by bryanjos** [comment]
@brittanygay looks like `defaultSource` on the images may be the way to go: https://facebook.github.io/react-native/docs/image#defaultsource

**Comment by daybreaker** [comment]
Also we need to go through the images we want stored and pre-cached and make sure they're up to date in `assets/index.js`

We'd want the defaultSource image to be pre-loaded so it shows up immediately

**Comment by brittanygay** [comment]
Pulling this in to look into next

**Comment by zmelamed** [comment]
This seems like one that should be quick to knock out considering the `defaultSource` option, can we get this taken care of

**Comment by brittanygay** [comment]
@bryanjos @daybreaker as I'm looking into this, I'm reading how `defaultSource` doesn't work well on Android. Should we find another solution? 

I'm also trying to stub this out but not _entirely_ sure how to set it up properly without getting errors.

Sources:
https://medium.com/technoetics/adding-image-placeholders-in-react-native-the-right-way-9140e78ac5c2

**Comment by zmelamed** [comment]
according to the facebook doc it only is an issue on android debug builds. 

Think it's worth testing the straightforward solution before trying something more complex... that article is from 2 yrs ago so may be improved since.

**Comment by Mcscott142** [comment]
@bryanjos @daybreaker Do we need to have Brittany to finish this one off?

**Comment by bryanjos** [comment]
If there is an asset to use as the default source image then that's enough for one of us to look into the rest

**Comment by bryanjos** [comment]
I'll just take it over in the mean time

**Comment by bryanjos** [comment]
I'll make the asset and do the thing
