### ISSUE TITLE
Attendee - Explore - Suggested Searches

### ISSUE THREAD

**Issue by bryanjos** [revelrylabs/bn-mobile-react#623]
related to #47

## Background 
A User may want to know of some suggested searches while searching for events

## Scenario: A User selects the search bar to find a specific artist, game etc. 
- [ ] When I select the search bar from the explore screen
- [ ] And I begin to type an artists name
- [ ] Then I see 
	- [ ] Suggested Searches

### Mock 

<details>
<summary>Suggested Search</summary>

![big_neon](https://user-images.githubusercontent.com/6877299/48151955-3fe1ea80-e288-11e8-86cc-9e8d4dfc4e9d.png)

</details>

**Comment by bryanjos** [comment]
Question: where are the suggested search values supposed to come from?

**Comment by Mcscott142** [comment]
@bryanjos What all comes in the event payload? I would think to start:

- Artist Name
- Genre - If that's available, might not be

**Comment by bryanjos** [comment]
I guess are the possible artists in big neon represented in the payload we get?

**Comment by Mcscott142** [comment]
We have Venues and Artists listed in the app. Use local results of what is already pulled in. Or are we already doing that? Maybe suggested search is the wrong term to use. I'm thinking of autosuggestion when typing.

**Comment by bryanjos** [comment]
I understand. I am just trying to figure out how it is expected to work and where the suggestions are supposed to come from.

I will get artist names from the retrieved list of events for now

**Comment by brittanygay** [comment]
Pulling this in for a design pass

**Comment by brittanygay** [comment]
@bryanjos I just pushed up my design edits, more info here: https://github.com/revelrylabs/bn-mobile-react/pull/637#issuecomment-475049485

Putting this back into review!
