### ISSUE TITLE
App Loading - When the explore view is loaded, top header and nav should show immediately

### ISSUE THREAD

**Issue by zmelamed** [revelrylabs/bn-mobile-react#629]
Right now the entire view (header, list,  and nav) doesn't display until the events are loaded from the API. 

This causes a blank waiting state that makes it feel like a website loading rather than an app, also blocking the rest of the app because there's no way to navigate to the ticket wallet until the events list loads, for instance.

The behavior should be to show the explore view with a loading/skeleton state only where the list of events will show up.

**Comment by Mcscott142** [comment]
Sounds like this and #619 may end up being the same thing @brittanygay @bryanjos @daybreaker

**Comment by bryanjos** [comment]
I think it's slightly different. I'm guessing this will be more about burying the conditional to hide or show the elements a little bit lower I think.

**Comment by zmelamed** [comment]
Yeah, #619 is a quick fix to just not have an empty white space for the images after the explore view eventually shows up, this one is about the order the explore view loads, the api call should not block the loading of the view. The designs included in #619 certainly can play a role here
