### ISSUE TITLE
Location Selection Issue on Prod

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#636]
Bug found in production App.

Video in Slack: https://revelry-public.slack.com/archives/CC1659FUZ/p1553010255010400

>When clicking on the menu, IF the menu is already set to Washington DC, clicking on the menu gives you a weird half-off-screen view of the menu.

**Comment by daybreaker** [comment]
The bug is caused by the name being too long in the header bar (not in the dropdown). 

Maybe we should truncate really long location names? The break seems to occur between location names of 18 and 20 characters in length.

**Comment by Mcscott142** [comment]
I agree with truncating
