### ISSUE TITLE
My Tickets - Brightness Adjustments 

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#642]
## Background
When clicking into my tickets it brightens the screen which is good, but when  exiting it lowers the brightness to a brightness that doesn't match where it was previously

## Scenario: A user opens a ticket
Given I select a ticket with a Barcode from My Tickets and the Brightness adjusts
- [ ] When I close the ticket
- [ ] Then the brightness goes back to my original level

**Comment by Mcscott142** [comment]
@bryanjos @daybreaker I know there were some issues around the brightness before. Is it possible to return to the original brightness? What were the caveats around this?

**Comment by bryanjos** [comment]
We aren't getting the brightness value back for some reason. Talking to Joel he suggested not changing it back. I say we can cut the feature entirely. If it works on iOS, we could just use it there. What do you all think?

**Comment by Mcscott142** [comment]
@zmelamed See above convo. Android is not giving us the brightness value back so we were setting a default. Should we:

- only have feature for iOS (seems to work for me)
- cut it entirely
- leave it as is? 
- something else?

**Comment by bryanjos** [comment]
Any updates on this?

**Comment by zmelamed** [comment]
Have it lower back down to .5 right now if we're going to peg it to something. The current value is too low to be the peg.

That will be good enough for now and we can come back to it at some point after we see peoples reaction night of.
