### ISSUE TITLE
Developer - Pre Load some Event Details after List View is populated

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#645]
## Background 
via Zach:
>Bigger project: If we have most of the info for the event detail pages when we're on the list view, I presume we could be able to pass the event details (or at least some of them) through to the event detail view so it doesn't have to load all the data from the API again before loading that view. 

>For something like the determining the state of the Purchase Tix button where would be important to pull ticket info from the API when that view loads, especially if the event list data may have been stale, it could show up in the loading button state that was recently created and then once the data is updated switch to the appropriate state. Just trying to make it feel more and more like a native app

AC filled in based on @daybreaker 's comment below: https://github.com/revelrylabs/bn-mobile-react/issues/645#issuecomment-475362260

## Scenario: Event details are passed on Event Index load
- [ ] When The Event Index is loaded
- [ ] Then pass in Event details to Event Show
- [ ] When Event is opened 
- [ ] Then new details from the API fill in

**Comment by Mcscott142** [comment]
This is a draft but also marking it score so if we poker, we'll talk about it a little bit.

**Comment by daybreaker** [comment]
We can pass in existing event details from the event index, then change the event load from `onWillFocus` to `onDidFocus` 

This way, the event will open with the info from the main index listing, and then fill in the new details that come in from the events/show API call.

This part is simple enough, but there may be unexpected issues with loading areas without content that we need to fix, either via developer or designer. Likely not very difficult though.

**Comment by Mcscott142** [comment]
@daybreaker updated AC, feel free to change if I didn't capture that correctly.

**Comment by Mcscott142** [comment]
Not exactly sure how to test. Events do seem to be loading with the quickness so I'm gonna pass through to UAT.

**Comment by Mcscott142** [comment]
@zmelamed Take a look to make sure this is the desired functionality you want. It pre-loads event details and then will populate any info we didn't have before. e.g. Page loads with all the info we had, things like ticket pricing populate after a moment of being on the screen.
