### ISSUE TITLE
Ticket QR not showing correctly on Android 

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#657]
Tested on Galaxy S6 Edge. Note: Ticket is fine on iOS.
Flock Of Seagulls Event happening today 3/22/19

The Artist Photo and Event Details are not showing. The screen is stretched with the QR code taking up the whole thing. As you scroll from ticket to ticket you can faintly see the details but when landing on the ticket it's only QR code. 

<details>
<summary>Scrolling screenshot</summary>

![Screenshot_20190322-101631](https://user-images.githubusercontent.com/6877299/54833743-b1956080-4c8c-11e9-892a-f8509f1e56e5.png)

</details>

<details>
<summary>Static Screenshot</summary>

![Screenshot_20190322-101519](https://user-images.githubusercontent.com/6877299/54833866-e73a4980-4c8c-11e9-8a1d-36327c0fdd87.png)

</details>

**Comment by bryanjos** [comment]
I was able to confirm on a Google Pixel 1 from Expo using the develop branch

**Comment by bryanjos** [comment]
I was able to confirm that in iOS this does not occur
