### ISSUE TITLE
Application - API - Handle Timeouts

### ISSUE THREAD

**Issue by bryanjos** [revelrylabs/bn-mobile-react#666]
Currently timeouts will cause a crash in the app. We do not know the best way to recover from them. 

One idea floated around was retries, but still need to know what to do after retries are exceeded as well.

How should API timeouts be handled?

**Comment by Mcscott142** [comment]
@zmelamed @Krakaw do y'all want to weigh in here?

**Comment by Krakaw** [comment]
What about using something like this: https://github.com/master-atul/react-native-exception-handler
Then depending on what endpoint timed out dropping them back to the index. So the event view timed out, drop back to events index so they can try again?
What about implementing https://facebook.github.io/react-native/docs/netinfo so we can see if they have any internet connection at all and alert them that they need a connection to continue?

**Comment by Krakaw** [comment]
We already have the `proxyGet` method wrapping the bn-api-node instance so we could do the check there as well?

**Comment by bryanjos** [comment]
> What about using something like this: https://github.com/master-atul/react-native-exception-handler
Then depending on what endpoint timed out dropping them back to the index. So the event view timed out, drop back to events index so they can try again?

That could work, but isn't there an issue with expo and using libraries that require linking?
Also, would have to be careful about accidentally creating an endless loop if the timeout happens on the index.

 > What about implementing https://facebook.github.io/react-native/docs/netinfo so we can see if they have any internet connection at all and alert them that they need a connection to continue?

We have the beginnings of that in place, but never propagated that to the UI. There is a catch in the error handler that checks for network errors and informs the user though.

**Comment by bryanjos** [comment]
Scratch what I said about expo. It is possible (i did it locally)
