### ISSUE TITLE
Explore - Re-Implement Search with Wildcarding

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#672]
semi related to #641 

## Background
We have temporarily removed the search function. We need to re-implement until we add some Wildcarding.

Comments from Zach via Slack Message:
>I'm realizing at the moment it's not wildcard searching, so when I went to test searching for the first event thats listed "The Moth StorySlam: Envy" and typed "Moth" it didn't show up, just want to define the logic around that a bit more so my team doesn't call it out

## Scenario: A user searches for an Event
- [ ] When I am directed to the Discover page 
- [ ] Then I see placeholder text that says
  - [ ] `Search for an event`
- [ ] When I search for a word in the Event title
- [ ] Then every event that contains that Word is returned

**Comment by Mcscott142** [comment]
Updated AC, Moved to Up Next

**Comment by bryanjos** [comment]
So search should look for strings that include the query and not begin with
