### ISSUE TITLE
Events - Tickets - Re-Add ticket Type descriptions

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#673]
## Background
When we added Ticket Type descriptions, we didn't take into account that some descriptions are VERY long. When they are too long it breaks the UI and users can no longer enter a Promo code. We can solve this by truncating the Ticket Type description. 
<details><summary>Screenshot</summary>

![Image from iOS (8)](https://user-images.githubusercontent.com/6877299/55080513-4a045a00-506c-11e9-9916-ea7a14c5748f.png)

</details>

## Scenario: A user selects a ticket type
Given a Ticket Type has a long description
- [ ] When I am selecting a ticket type 
- [ ] Then I can still see the Promo code
- [ ] And the ticket type description is fully readable

**Comment by Mcscott142** [comment]
Updated AC, moved to `Up Next`

**Comment by bryanjos** [comment]
This look ok?

![Simulator Screen Shot - iPhone XR - 2019-03-27 at 09 53 44](https://user-images.githubusercontent.com/1257573/55086369-4675d080-5076-11e9-9d46-64bad25ea88d.png)

**Comment by daybreaker** [comment]
This is the only place where they would see the ticket description before purchasing, so I feel like we should show all of it?

Can we just style the ticket desc box to not extend beyond the window?

**Comment by Mcscott142** [comment]
That works for me. They just need to be able to scroll and see the whole page.

**Comment by daybreaker** [comment]
@brittanygay could knock it out a lot faster than I could. Dont know how good Bryan is at RN styling :-P

**Comment by Mcscott142** [comment]
All good, I'll label design and we'll hold it for next week.

**Comment by Mcscott142** [comment]
Updated AC

**Comment by bryanjos** [comment]
@Mcscott142 putting back on the bench. I did some updates but need a designer to help get the promo code section to show up while keeping the top margin like it is.

**Comment by daybreaker** [comment]
I'll take a shot at it, so hopefully we dont have to wait until next week
