### ISSUE TITLE
Developer - Re-Implement Facebook login button

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#674]
## Background 
When the Apple Store accepts the latest production build, we need to re-implement the Facebook button so users can login via Facebook. 

## Scenario: Apple accepts latest build in App Store
- [ ] When Apple accepts the build
- [ ] Then I put the facebook button back

**Comment by Mcscott142** [comment]
Unblocking

**Comment by daybreaker** [comment]
ios uses web login, which pops up a WebView with the FB login screen. pushed to production, and tested. I was able to login.

This seems like an ok stop gap until SDK 33 is released (assuming it doesnt break something else we need like sdk 32 did)
