### ISSUE TITLE
Deployment Screencast

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#675]
Via Zach:

>if you have a screencast app (CloudApp is a really easy one) can you please screen record the deployment process to production/staging with relevant commentary. I want to make sure our team can easily do it if something were to go wrong after hours or weekends and we're in a crunch and that seems like the easiest way considering they're in south africa.

- [ ] Do a deployment with a screencast

**Comment by bryanjos** [comment]
With #709, is this needed anymore?

**Comment by Krakaw** [comment]
@bryanjos maybe you and I can make some time to run through the deployment process so we have some solid documentation on how we deploy staging / production

**Comment by bryanjos** [comment]
@Krakaw we can. Most of it is automated through CI now so it should be simple enough

**Comment by bryanjos** [comment]
@Krakaw let's pick a time today or tomorrow to meet and get this issue closed out.

**Comment by iamjoshfrank** [comment]
Same - @bryanjos and @Krakaw did this happen? if not, book it and do it so we can close this out. It's a chore, but at one time recently was a priority, so let's not let it sit open. Do it or close it.

**Comment by bryanjos** [comment]
Did not happen. Closing. It's been 18 days
