### ISSUE TITLE
Ticket Type - Sold Out Ticket Type

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#677]
## Background
When an event is sold out, we need to replace the ticket price with sold out and not allow the user to Select it. 

See Slack thread: https://revelry-public.slack.com/archives/CC1659FUZ/p1553708094102200

## Scenario: A user pulls up tickets for a sold out event
Given a Ticket Type is Sold out on an event
- [ ] When I select purchase tickets
- [ ] Then I see that the Ticket price has been replaced with Sold Out
- [ ] And I cannot select that Ticket Type

**Comment by bryanjos** [comment]
Updated

![Simulator Screen Shot - iPhone XR - 2019-03-27 at 19 04 24](https://user-images.githubusercontent.com/1257573/55120308-6b446500-50c3-11e9-9b42-b91c30c23c10.png)

**Comment by zmelamed** [comment]
Per my previous comment on the previous PR... the text size also needs to be reduced on that label to the size of the ticket name text 
and @Mcscott142 we need to fix that issue with long ticket names pushing the > to the right and being cut off asap. I also would like to adjust it to 0 decimal places to give us more room and clean it up, round up to the nearest dollar.

**Comment by bryanjos** [comment]
So I'll do the following here:
- Make the pricing text size the same as the ticket name text size
- Apply the work in progress fix to keep the text from pushing off the `>`



I can try removing the decimals, but also maybe do that in a separate PR because I would like a design review on that.

**Comment by bryanjos** [comment]
@zmelamed how does this look?

![Simulator Screen Shot - iPhone XR - 2019-03-28 at 11 45 15](https://user-images.githubusercontent.com/1257573/55176401-0fbfb900-514f-11e9-86be-1eef801da768.png)

**Comment by zmelamed** [comment]
only the sold out label should be the reduced size. sorry for the confusion on this

**Comment by bryanjos** [comment]
Ok I'll put this back until we have a designer

**Comment by bryanjos** [comment]
Actually I'll give it a try if it can get this across the finish line

**Comment by Mcscott142** [comment]
Looks good, opened #682 for a couple of tweaks.
