### ISSUE TITLE
Facebook Login loading time

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#683]
## Background
When I log in via Facebook through Android or iOS, there is a pretty substantial pause after confirming the login where I'm redirected to the Big Neon login screen and it sits there until I'm taken to the Explore page. 

Maybe we can have a loading indicator or something? I think a lot of people will try to hit the buttons again. 

Scenario: A user logs in via FB
Given
- [ ] When log in with Facebook
- [ ] Then I see a loading indicator instead of the homescreen before directed to Explore page

**Comment by daybreaker** [comment]
PR in, but waiting on FB login on staging to work.

**Comment by Mcscott142** [comment]
Much better. Moving to UAT.
