### ISSUE TITLE
Attendee - Account - Billing Page

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#69]
## Background
Users will need to connect credit cards or other forms of payment in order to purchase tickets or receive payment for them. 

## Scenario: A user selects Billing Information from the Main Account page
- [ ] When I am directed to the Billing Information page
- [ ] Then I see
	- [ ] A section for Credit Cards
	- [ ] A Section for Connected Accounts e.g. Venmo
	- [ ] An option to add another Payment form

## Mock 
![ios_app_-_dev_version__1__sketch](https://user-images.githubusercontent.com/6877299/44345766-d9ec8080-a459-11e8-80cb-240ccae50c13.png)

**Comment by brittanygay** [comment]
Pulling this in to start on until the other tickets are ready for me to work again.

**Comment by brittanygay** [comment]
Once updates are deployed this will be ready for QA
