### ISSUE TITLE
Account - Order History

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#695]
## Background
A section where users can see their ticket/order history.

<details><summary>Order History Link Mock</summary>

![Big_Neon](https://user-images.githubusercontent.com/6877299/55485846-e096c500-55f0-11e9-9026-4fdba04fca92.png)

</details>

<details><summary>Order History Page Mock</summary>

![Big_Neon](https://user-images.githubusercontent.com/6877299/55485876-ed1b1d80-55f0-11e9-997d-6149ae676bca.png)

</details>

## Scenario: A User selects Order History from the Main Account Page
- [ ] When I am directed to Order History
- [ ] Then I see
	- [ ] A list of order receipts with 
		- [ ] Band Name
		- [ ] Venue
		- [ ] Number of Tickets
		- [ ] Total $ amt paid

**Comment by bryanjos** [comment]
@Krakaw the venue is not in the response for orders so for now we are going to omit that information.

Actually, the band name technically isn't either and all we have is the event name. Which is what we are going to use.

**Comment by Mcscott142** [comment]
Moving to UAT, good for now. We'll want to change this up once we get better info in the payload.
