### ISSUE TITLE
Promo Code input needs to always be visible

### ISSUE THREAD

**Issue by daybreaker** [revelrylabs/bn-mobile-react#696]
_depends on #700_
When an event has no tickets, is sold out, etc, the screen needs to show the Promo Code box in case there are restricted tickets that can be unlocked.

**Comment by daybreaker** [comment]
When an event has no tickets, is sold out, etc, the screen needs to show the Promo Code box in case there are restricted tickets that can be unlocked.

**Comment by daybreaker** [comment]
For testing: Added an event with no tickets - Arcade Fire on April 8th - using Promo Code REV0403 to reveal promo-only ticket hold


Didnt test on Android, so may need more styling?

**Comment by Mcscott142** [comment]
Nothing happening when I apply promo code.

**Comment by Mcscott142** [comment]
Just saw #700, that's the culprit. Holding on testing till that's merged.

**Comment by bryanjos** [comment]
Tested on Android with the `Priority Parties` event on Dec 12. There are no tickets and the Promo Code UI is shown
