### ISSUE TITLE
Attendee - Account - NotificationPreferences

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#70]
## Background
A user should have the ability to set their notification preferences. 

## Scenario: A User selects Notification Preferences from the Main Account page
- [ ] When I am directed to Notification Preferences
- [ ] Then I see: 
	- [ ] A list of notification types
	- [ ] Selectable Icon for email
	- [ ] Selectable Icon for Phone

## Mock
![ios_app_-_dev_version__1__sketch](https://user-images.githubusercontent.com/6877299/44345990-757df100-a45a-11e8-9bed-8cfa3c6b6b63.png)

**Comment by brittanygay** [comment]
All sprint tickets that need my attention are almost complete. Keeping an eye on #57 to make sure it gets into Review, but all design updates are complete.

Pulling this in from the backlog to start working on since I have some time left, though this is not a sprint ticket for this week. CC @iamjoshfrank

**Comment by brittanygay** [comment]
Continuing to work on this ticket since this is now part of the current sprint.

**Comment by brittanygay** [comment]
I just pushed up my branch with the stubbed out screen: https://github.com/revelrylabs/bn-mobile-react/pull/87

Assigning to @daybreaker to check out the one item i listed in my PR that I need his help setting up. Once that's complete, I'll assign my PR for a design review and move this ticket into the Review col.

**Comment by brittanygay** [comment]
@daybreaker I just pulled down the branch and fixed all conflicts/checked everything out. It looks great!

Assigning to @blazebarsamian now for a design review.

**Comment by brittanygay** [comment]
PR has been approved and merged. This will now be ready for QA once updates are deployed.

**Comment by Mcscott142** [comment]
lgtm, closing.
