### ISSUE TITLE
The `get-own-property-symbols` dep can be removed when you upgrade to bn-api-node 2.0.0

### ISSUE THREAD

**Issue by Krakaw** [revelrylabs/bn-mobile-react#702]
https://github.com/revelrylabs/bn-mobile-react/blob/c9d155e7a247af7cc28cdee214f41cc27fbdd606/package.json#L33

**Comment by bryanjos** [comment]
I haven't noticed any issues with this so far by going through the app.

**Comment by daybreaker** [comment]
same
