### ISSUE TITLE
Ticket Type - Promo Code - Add Loading Indicator on Button

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#704]
## Background
It can take a few moments when Adding a Promo code for a Hidden ticket to be revealed or for a price update to take place. 

## Scenario: I add a Promo code to a ticket
- [ ] When I Add a Promo Code
- [ ] And select `Apply Promo Code` 
- [ ] Then I should see the button loading indicator

**Comment by bryanjos** [comment]
Tested on R.E.M concert with promo code `REV000` works as expected on Android
