### ISSUE TITLE
Ticket Type - Promo Code - Promo Code overlapping Empty State Screen

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#705]
See Event Arcade Fire on April 8th in staging env. This was on Samsung Edge S6. Seems ok on iOS. 

1) Apply Promo Code REV0403
2) Remove Promo Code
3) See that the Promo Code now overlaps the empty Ticket State 
4) I exited and came back into the event and it still looked this way

<details><summary>Screenshot</summary>

![Screenshot_20190405-092950](https://user-images.githubusercontent.com/6877299/55635429-423c6800-5786-11e9-8c19-b962730afc5d.png)

</details>

**Comment by bryanjos** [comment]
I didn't get exactly what's in the screenshot, but something close to it. I think a designer should take a look at it. It is an edge case situation.
