### ISSUE TITLE
Attendee - Account - Order History

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#71]
## Background
A section where users can see their ticket/order history.

## Scenario: A User selects Order History from the Main Account Page
- [ ] When I am directed to Order History
- [ ] Then I see
	- [ ] A list of order receipts with 
		- [ ] Band Name
		- [ ] Venue
		- [ ] Number of Tickets
		- [ ] Total $ amt paid

## Mock
![ios_app_-_dev_version__1__sketch](https://user-images.githubusercontent.com/6877299/44347722-32258180-a45e-11e8-9fd6-a9da2ee3f0e4.png)

**Comment by brittanygay** [comment]
I'm currently blocked on #70 and #61, so I'm pulling this in to work on until those tickets are passed back my way! 

**Note**:
This ticket is not in our current sprint but I'm getting a head start on it CC @Mcscott142
