### ISSUE TITLE
Guest List/Scanning - Android guestlist check-in performance issues

### ISSUE THREAD

**Issue by Krakaw** [revelrylabs/bn-mobile-react#718]
Connected to big-neon/bigneon#114
Expected Behavior:
- After swiping to checkin a users valid ticket on the event guest list, the check-in should succeed in < 1 sec and allow for the next ticket to be checked in

Actual Behavior:
- After swiping a valid ticket on Android Galaxy 7 it took nearly 5 seconds to return a success response and reset the view state to allow the next ticket to be swiped

**Screen Capture:** https://cl.ly/7fa89d8a2cc6

**Comment by bryanjos** [comment]
It sounds like we need to think this through a bit.

There are a couple of cases we have to think through. One of those being what happens if there is an error from the API, how to respond.

**Comment by bryanjos** [comment]
> the check-in should succeed in < 1 sec and allow for the next ticket to be checked in

Are we talking about the swipe completion, the api request, or all of them together? We have no control over how long the API takes.

**Comment by Krakaw** [comment]
All of them together, there could be some delays on the API side, we are busy benchmarking the endpoint and looking for improvements there.

**Comment by bryanjos** [comment]
Makes sense. The change in the PR will at least give users that ability to keep swiping guests, add a `processing` status, and will let them know if there is an error.

**Comment by Krakaw** [comment]
That will be a great addition, if someone is trying to double spend and it comes back with an error in 2-3 seconds there will still be enough time to grab the offender by the collar.

**Comment by bryanjos** [comment]
I saw something about having 500-10,000 and that seems like it needs to be engineered some more. The list there should be efficient enough to not blow memory and only account for items within the screen's view, BUT maybe not so helpful for the users.

I just realized though there is search so that will help

**Comment by Krakaw** [comment]
Also note: https://github.com/big-neon/bn-api/pull/1209 there is now a `?changes_since=2019-04-16T15:00:00` for the guest list endpoint. This will only show the changed tickets from the UTC timestamp provided.

**Comment by bryanjos** [comment]
Speaking of, our dependency bot has a change for moving to 2.0 of the api client. I'm still wondering what changes are made and what backwards incompatibilities we should look out for it we tried to integrate it?

**Comment by Krakaw** [comment]
The change was the internal mechanism that generated the endpoints. Otherwise nothing else has changed, it has been tested well now so you should have absolutely no problem upgrading. There is an added benefit of removing the `get-own-property-symbols` dependency.

**Comment by bryanjos** [comment]
Thanks! Will get to integrating it soon

**Comment by bryanjos** [comment]
Tested on Android and working as expected
