### ISSUE TITLE
Attendee - Account - QR Code 

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#72]
## Background
For Ticket transfers, a user will need their personal QR code. 

## Scenario: A User selects their QR code Icon on Main Account Page
- [ ] When I tap my QR code
- [ ] Then it appears on screen with a message
	> Show this to complete a ticket transfer

## Mock
![ios_app_-_dev_version__1__sketch](https://user-images.githubusercontent.com/6877299/44347955-d1e30f80-a45e-11e8-985f-d100af5ecba4.png)

**Comment by brittanygay** [comment]
Picking this up to work on now that @daybreaker has set up the screen

**Comment by brittanygay** [comment]
PR has been reviewed and merged. More info and screenshots here: https://github.com/revelrylabs/bn-mobile-react/pull/96

Once everything is deployed this will be ready for QA.
