### ISSUE TITLE
API endpoint requests

### ISSUE THREAD

**Issue by daybreaker** [revelrylabs/bn-mobile-react#725]
1) We get the list of Location filters from regions/index… is there a way to send a selected region to the events/index in the params, or maybe events/query could take a location id _and_ a search string? Right now, the mobile app and also the web app it seems, just use client side filtering for the region.

But with pagination (lets say we say a limit of 10 events), this will perform very weirdly. We show Page 0, then if a location filter is selected, it only filters the first 10. Then if enough events are filtered out to hit the fetchNextPage threshold, it’ll fetch Page 1, and only display events matching the region. Which could be 0. Then if its still below the threshold, it will fetch Page 2, and so on.

It would be more useful to just have a way to send a location, and just get a paginated set of events matching that location. (edited) 

2) Also, is there a way we could have some kind of events/suggestedNames endpoint? Right now, for the event search, our list of suggested names as you type just come from the set of existing events, which, with pagination, could only be 10 events and not all events. (edited)

**Comment by daybreaker** [comment]
@Krakaw ^

**Comment by Krakaw** [comment]
You can use `Bigneon.events.index({region_id: 'xxx'})`

**Comment by daybreaker** [comment]
Sounds good!

Is there a way we could get something like I mentioned in Question #2? We'll probably have to remove the suggested search as you type option until we get something like that.

**Comment by Krakaw** [comment]
Ahh like an autocomplete for the names of events?

**Comment by daybreaker** [comment]
Yeah, just something we could use to populate our "Suggested Search as you type" with names. 

Right now, we're collecting names of venues, events, and event artists. So something similar that take a query string and return an array of names (we can make sure it only triggers after typing at least 3 letters, or something), where those names, if one was selected, would return matching events when passed to the event query endpoint.

**Comment by daybreaker** [comment]
Although, now that I'm thinking more about this, we do only show a few suggested names...

Maybe we could just use events/query ourselves, then collect & display the names from those events. It wouldnt matter if its paginated & limited to 10, because we only show 3-5 suggestions anyway

I'm gonna try this first. I'll let you know how it goes.

**Comment by bryanjos** [comment]
I don't think this is needed anymore so I'm closing it
