### ISSUE TITLE
Error when adding tickets

### ISSUE THREAD

**Issue by bryanjos** [revelrylabs/bn-mobile-react#728]
Click the + on a ticket really quickly you'll see the error

**Comment by iamjoshfrank** [comment]
If this is still occurring, I'd say work it!

**Comment by bryanjos** [comment]
I created an issue from a slack comment and waited for details. Nothing came about

**Comment by iamjoshfrank** [comment]
So you've tried to reproduce and haven't been successful? If that's the case, mark it blocked and assign Zach.

**Comment by jpatricknola** [comment]
@bryan where in the flow of the app does this error occur?

**Comment by bryanjos** [comment]
Haha, I don't know. Not many details were given. @Krakaw do you have more details on this specific bug?

**Comment by jpatricknola** [comment]
![Screen Shot 2019-05-10 at 11.01.33 AM.png](https://images.zenhubusercontent.com/5cbf376ce0d3d508934b139c/1e69d7c2-2a87-4002-a3ac-fbf0ce61b6c6)

Im on this page but have been able to recreate the error by clicking + and - repeatedly it appears to work fine

**Comment by Krakaw** [comment]
It looks like it has been fixed by disabling the `+` button once you hit the ticket_limit which wasn't happening before.

**Comment by jpatricknola** [comment]
Right on thanks @Krakaw.   I will close and resolve this issue then
