### ISSUE TITLE
Update Push Notifications sent when user purchases a ticket

### ISSUE THREAD

**Issue by bryanjos** [revelrylabs/bn-mobile-react#729]
From Slack:

```
We can also look at Push Notifications that we'll send when you purchase a ticket (either on the web or the app)

The API sends the limit per user with the ticket types
```

**Comment by iamjoshfrank** [comment]
So ... this is a `draft`? Without context, I'm not sure I can get this ready to work. But here's my stab:

## Scenario: Purchase Ticket (Web), Receive Notification
Given I am a Big Neon user with the mobile app installed on my phone
- [ ] When I purchase a ticket through the web interface
- [ ] Then I receive a push notification on my phone
- [ ] And I can access the purchased ticket in my mobile app via the push notification

I don't know why we would send a push notification for a purchase made in the mobile app. Wouldn't the UX actually be:
- "purchase ticket > see ticket confirmation screen;" or
- "purchase ticket > redirect to equivalent of 'My Tickets';" or
- some other in-app userflow

**Comment by iamjoshfrank** [comment]
@zmelamed - see my comment above. if this is still needed and you can provide some more details, we can make this ready to work.

**Comment by bryanjos** [comment]
@iamjoshfrank I'm going to say we close this one. The mobile app has no control over sending messages.
