### ISSUE TITLE
Pagination: Filter by Location

### ISSUE THREAD

**Issue by daybreaker** [revelrylabs/bn-mobile-react#730]
Use region_id param in events index with a new API call when filtering by location, instead of client side JS filtering, to maintain paging

Also, add an "All Locations" option to clear the location filter

**Comment by Krakaw** [comment]
@bryanjos 
To populate the list of available regions.
`curl -X GET api.staging.bigneon.com/regions`
`server.regions.index()`

To get the events for that region 
`curl -X GET api.staging.bigneon.com/events\?region_id=00000000-0000-0000-0000-000000000000`
`server.events.index({region_id: regionId, q})`
Including a search with that:
`curl api.staging.bigneon.com/events\?region_id=00000000-0000-0000-0000-000000000000\&query=SubZero`
`server.events.index({region_id: regionId, query: 'SubZero'})`

**Comment by bryanjos** [comment]
Thanks!
