### ISSUE TITLE
Pagination: Use event query to build suggested search options

### ISSUE THREAD

**Issue by daybreaker** [revelrylabs/bn-mobile-react#731]
Right now "suggested name options" when searching events is based on collecting names of events and artists from existing events. A selected name then filters the existing set of events on the client side.

By adding pagination, we no longer have the full event data set, and need a new way to find suggested search names, as well as to filter events.

Option 1: Use the event query endpoint to search based on the entered text string to collect names from those, then use a selected name or phrase to send back as a query to the search endpoint

**Comment by daybreaker** [comment]
Status:

Retrieving events based on query string & using those events to show suggested names in the dropdown.

Needs to do:

1) Dont show names when < 3 chars 
2) add a "clear search" or "X" button to wipe the search/filter
3) only use the most recent API search, since typing triggers a new API search each time

**Comment by daybreaker** [comment]
@bryanjos I have a branch for this at `name-search-#731`

The status of it is in the previous comment. I'm out for the next few days so feel free to pick it up.

**Comment by bryanjos** [comment]
Doing this more, it feels like a landmine of confusion without #730

**Comment by bryanjos** [comment]
I think I'm going to put this one back for now until at least #730 is done.

**Comment by Krakaw** [comment]
I commented in #730
