### ISSUE TITLE
Event Name suggested search results are duplicated

### ISSUE THREAD

**Issue by daybreaker** [revelrylabs/bn-mobile-react#754]
When getting results with search as you type for suggested events, we get a duplicate key warning, as some events are duplicated in the results.

**Comment by bryanjos** [comment]
This most likely has to do with an event having the same name as an artist. I don't think we are deduping them but we can.

**Comment by bryanjos** [comment]
With only one event there I can't reproduce. Also, I checked and there should be unique names happening

**Comment by bryanjos** [comment]
@Krakaw is there a way for you to make more events? Or is it something I can do?

**Comment by bryanjos** [comment]
I was able to add an event for Open Mike Eagle. However, I wasn't able to reproduce the error on development or on the beta app. Sending to UAT to test
