### ISSUE TITLE
User - Account - See Big Neon Version

### ISSUE THREAD

**Issue by bryanjos** [revelrylabs/bn-mobile-react#770]
from #765 

## Background
Big Neon receives over-the-air (OTA) updates so the version shown in the App Store may not match the one users have. There may be times when, for debugging purposes, it would be nice to know the exact version.

## Scenario: User wants to see the current version
Given I am a User
- [ ] When I am on the Account tab
- [ ] Then I am able to see the current version of the Big Neon app somewhere

**Comment by iamjoshfrank** [comment]
Looks good to move. Moving this over to `Up Next` and slapping a `score` label on it.
