### ISSUE TITLE
Guest List - Can't scroll to last item in the guest list search results

### ISSUE THREAD

**Issue by zmelamed** [revelrylabs/bn-mobile-react#772]
When I type in a guest list search that returns many results I can't scroll to the last result to check them in

**Comment by jpatricknola** [comment]
@zmelamed is the bug happening on this screen?
![keithsontheguestlist](https://user-images.githubusercontent.com/6878242/57801548-8d4c8200-7719-11e9-886a-72f866005594.png)

**Comment by zmelamed** [comment]
No, type in "Keith" to search, it's the search results list

**Comment by bryanjos** [comment]
![Simulator Screen Shot - iPhone 8 - 2019-05-15 at 18 12 50](https://user-images.githubusercontent.com/1257573/57815451-1f19b680-773d-11e9-9992-3a51ddd01a6e.png)

**Comment by bryanjos** [comment]
This will be tricky to fix. It goes in conflict with the "swipe to checkin" feature. For that we use a swipe list view. Which uses a flatlist underneath. The keyboard aware scrollview would cause more problems that those 2 things solve.

The only thing I can think of to try to close the keyboard when the user starts scrolling.

https://github.com/jemise111/react-native-swipe-list-view/blob/master/docs/SwipeListView.md
https://facebook.github.io/react-native/docs/flatlist

If these things build upon each other like the docs make it out to seem, maybe this will work:
https://facebook.github.io/react-native/docs/scrollview#onscroll

**Comment by zmelamed** [comment]
@bryanjos it should close the keyboard when the user starts srolling per #773 ... if that fixes this then that is the way to go. Kill two birds
