### ISSUE TITLE
Door Person - Show check-in details for tickets already redeemed

### ISSUE THREAD

**Issue by zmelamed** [revelrylabs/bn-mobile-react#774]
When a person is already checked-in and an "Already Redeemed" message is displayed there should also be:
"Scanned by: [scanner name] [time since scan]"
Like:
"Scanned by Zachary M. 30 seconds ago"

**Comment by bryanjos** [comment]
@Krakaw or @zmelamed  does this information exist in the API? We aren't seeing enough information from the tickets we get from the API

**Comment by Krakaw** [comment]
In the response for the guest_list as well as the get request for redeem you should see `redeemed_by` and `redeemed_at` this will only be populated from now on after a redemption.

**Comment by bryanjos** [comment]
When we look at the response from the api we get nulls for `redeemed_by` and `redeemed_at`

```json
Object {
  "door_time": "2019-05-08T18:00:00",
  "email": "ks@tari.com",
  "event_id": "d82921d1-7c24-4838-a098-f0235a226af7",
  "event_name": "Huge ticket sales",
  "event_start": "2019-05-08T19:00:00",
  "first_name": "Keith",
  "id": "687c7f5e-03e8-4e59-9c19-de0c5b020c2e",
  "last_name": "Simon",
  "order_id": "cbc5d2e7-aa55-46d1-b371-4e66e59010f5",
  "order_item_id": "3ef12c99-bc99-418e-83da-70f0f622d6ec",
  "phone": null,
  "price_in_cents": 200,
  "redeem_date": "2019-05-08T18:00:00",
  "redeem_key": "MPQ2CPQFH",
  "redeemed_at": null,
  "redeemed_by": null,
  "refund_supported": true,
  "status": "Redeemed",
  "ticket_type": "General Admission",
  "updated_at": "2019-05-09T10:15:34.814010",
  "user_id": "bd977ab1-2b5e-42d5-bb71-92166b625862",
  "venue_id": "39fb32a6-82f5-4d59-a901-0c8ac09734ad",
  "venue_name": "Big Neon",
}
```

But when you redeem tickets now we get

```json
Object {
  "door_time": "2019-05-08T18:00:00",
  "email": "ks@tari.com",
  "event_id": "d82921d1-7c24-4838-a098-f0235a226af7",
  "event_name": "Huge ticket sales",
  "event_start": "2019-05-08T19:00:00",
  "first_name": "Keith",
  "id": "ffd06e50-eed0-4ead-a68f-704c7f2c2a68",
  "last_name": "Simon",
  "order_id": "cbc5d2e7-aa55-46d1-b371-4e66e59010f5",
  "order_item_id": "3ef12c99-bc99-418e-83da-70f0f622d6ec",
  "phone": null,
  "price_in_cents": 200,
  "redeem_date": "2019-05-08T18:00:00",
  "redeem_key": "GUKRXFW7T",
  "redeemed_at": "2019-05-16T16:28:36.466959",
  "redeemed_by": "System Administrator",
  "refund_supported": true,
  "status": "Redeemed",
  "ticket_type": "General Admission",
  "updated_at": "2019-05-16T16:28:36.466959",
  "user_id": "bd977ab1-2b5e-42d5-bb71-92166b625862",
  "venue_id": "39fb32a6-82f5-4d59-a901-0c8ac09734ad",
  "venue_name": "Big Neon",
}
```

So we can only display the information if the values are there. Just posting this hear so we know what it looks like

**Comment by zmelamed** [comment]
Is someone on your end have an idea how to treat this in UI or should we whip something up?

**Comment by bryanjos** [comment]
I will see what @CheetoMao has to say, but also, what screen are we talking about here? Is this when scanning a ticket?

**Comment by zmelamed** [comment]
Yeah sorry I didn't clarify... it's on the scan response screen and on the guest list ticket detail view (when you click on the ticket in the guest list)... the guest list ticket detail view is pretty straight forward, just add it as text on that view... the scan view we just want to make sure the text is readable below the "Already Redeemed" message that already appears. I'll mock something up quick for that and you guys can have your way with it

**Comment by zmelamed** [comment]
![image](https://user-images.githubusercontent.com/456953/57874202-e02f4380-77c4-11e9-89a4-865364836782.png)

**Comment by bryanjos** [comment]
Thanks! That clears up things

**Comment by zmelamed** [comment]
The version on the far right is the preference assuming it's the easiest to implement as well

**Comment by jpatricknola** [comment]
@Krakaw 

Sending a get request for redeem does indeed contain "redeemed_at" and "redeemed_by" in the response, but only when it is a successful request (meaning the ticket is being scanned for the first time).   However, the response does not contain these properties for an unsuccessful request (such as a ticket that has already been redeemed).   Instead we get an error message with the following data property {
  "error": "Ticket has already been redeemed.",
}

So the problem is that we are unable to get the "redeemed_at" and "redeemed_by" values for a ticket that has already been redeemed, by making a get request for redeem.    

I was thinking that one possible way to solve this problem would be to update the API endpoint for server.tickets.read(id) so that the response contains those two properties.   It would seem to be a sensible place to have this information, since a request to this endpoint returns info about the ticket status being redeemed or not.

**Comment by jpatricknola** [comment]
another possibility would be to update the error response for redeem get requests, so that along with the error message "Ticket has already been redeemed" it includes "redeemed_at" and "redeemed_by" values

**Comment by zmelamed** [comment]
@Krakaw can you help with this. Can you supply the info with the error payload? or give guidance on how they can be unblocked

**Comment by Krakaw** [comment]
I have added https://github.com/big-neon/bn-api/pull/1280
```json
{"error":"Ticket has already been redeemed.","redeemed_at":"2019-05-21T09:37:23.808100","redeemed_by":"System Administrator"}
```

**Comment by jpatricknola** [comment]
@krakow should we be seeing these changes now?    Looks like Im still getting the same error response without the redeemed_at and redeemed_by properties that you added  ![redeemed ticket.png](https://images.zenhubusercontent.com/5cbf376ce0d3d508934b139c/10f6cc16-6511-4532-a1eb-f4b5d8899011)

**Comment by Krakaw** [comment]
x-app-version is now 1.0.121 please try again.
`{"error":"Ticket has already been redeemed.","redeemed_at":"2019-05-21T16:06:27.232535","redeemed_by":"System Administrator"}`

**Comment by jpatricknola** [comment]
submitting a PR now for this ticket
![IMG_0041.jpg](https://images.zenhubusercontent.com/5cbf376ce0d3d508934b139c/43a2f62b-07c3-4588-8cd3-c4bdad3f405d)
