### ISSUE TITLE
iOS keyboard hides the focused input

### ISSUE THREAD

**Issue by CheetoMao** [revelrylabs/bn-mobile-react#780]
When I tap on the promo code input in iOS, the default keyboard slides up and hides the promo code input. This is frustrating because you can't see what your typing.

## Description
When I tap on the promo code input in iOS, the default keyboard slides up and hides the promo code input.

## Screenshots/Gifs
![event-enter-promo](https://user-images.githubusercontent.com/3287583/57858008-de11b880-77b5-11e9-8bd9-9186183c862e.png)

## Steps to Reproduce
Provide steps to reproduce the issue you encountered.

- [ ] I am viewing an event detail page and tap 'Purchase Tickets'
- [ ] I am taken to a view were I can 'Select Ticket Type' and enter a promo code
- [ ] I tap the promo code input
- [ ] the iOS keyboard slides up but the page stays at the same scroll position, causing the keyboard to hide the promo code input. 

## Platform/Device/Browser Information
- [ ] iOS 12.3 iPhone 6+

**Comment by iamjoshfrank** [comment]
Similar to #758, yeah?
