### ISSUE TITLE
Select location menu style issues onTouch

### ISSUE THREAD

**Issue by CheetoMao** [revelrylabs/bn-mobile-react#781]
When selecting a location from the dropdown, there are some confusing styles.

## Description
onTouch styles make text illegible (ie. black background, black text), also the background color doesn't extend the full width of the menu

## Screenshots/Gifs
![IMG_1396](https://user-images.githubusercontent.com/3287583/57859144-fbe01d00-77b7-11e9-80e1-f134690d0c8c.PNG)
![IMG_1395](https://user-images.githubusercontent.com/3287583/57859145-fbe01d00-77b7-11e9-8782-4a02d3920f70.PNG)

## Steps to Reproduce

- [ ] tap the locations menu in the topbar
- [ ] tap to select a location
- [ ] the background turns black (except for a small portion on the right)
- [ ] the text stays black 

- [ ] tap the locations menu in the topbar
- [ ] tap the words 'Where are you looking for events?'
- [ ] is this a link? Should this even have onTouch styles?

## Platform/Device/Browser Information
- iOS 12.3 iPhone 6+

**Comment by bryanjos** [comment]
Looking into this now. Haven't found the right prop to pass to make it better yet
