### ISSUE TITLE
Guest List - A door person should be able to search by First Name, Last Name, or Full name

### ISSUE THREAD

**Issue by zmelamed** [revelrylabs/bn-mobile-react#786]
Currently you can only search by first name, as soon as you enter a space to begin typing the last name the results disappear. Typing just the last name returns no results.

A door person should be able to find John Smith by typing "John", "john s", "john smith", or "Smith"

**Comment by bryanjos** [comment]
@zmelamed we are passing the value directly to the api so it Looks to be something that would have to be looked at there.

**Comment by zmelamed** [comment]
A gotcha, I thought it was searching the list locally... I'll move it to that repo

**Comment by jpatricknola** [comment]
marking this issue as closed
