### ISSUE TITLE
Attendee - Home/Explore page - Initial app loads with all images/assets present

### ISSUE THREAD

**Issue by daybreaker** [revelrylabs/bn-mobile-react#79]
## Background 
Currently, asset loading is visible when the user opens the app. There should be a way to preload and cache assets so these images and icons are already visible when the app loads.

## Scenario: Loading the App
- [ ] When I open the App
- [ ] Then I see all icons and static images are already loaded when the splash screen closes

**Comment by daybreaker** [comment]
https://docs.expo.io/versions/latest/guides/preloading-and-caching-assets
https://docs.expo.io/versions/latest/sdk/splash-screen.html

**Comment by daybreaker** [comment]
If this doesnt achieve our goals, we'll need a new ticket to Eject to non-Expo RN.

**Comment by daybreaker** [comment]
Working in ios, but not android simulator.

Need a physical device to test on tomorrow

**Comment by iamjoshfrank** [comment]
Removing this from the `Week 35` milestone b/c it wasn't in the original commitment (only the research ticket was committed to).

Still, if we can ship this ticket this week, all the better!

**Comment by daybreaker** [comment]
Not working on Android. Found a potential solution: https://blog.expo.io/expo-publishing-and-asset-concepts-2d8c60968927

Sadly I dont think I can get to it until next week

**Comment by Mcscott142** [comment]
Pushing this back to 9/10
