### ISSUE TITLE
Doorperson - Event - Access Guest List

### ISSUE THREAD

**Issue by iamjoshfrank** [revelrylabs/bn-mobile-react#796]
[via @bryanjos on 765:](https://github.com/revelrylabs/bn-mobile-react/issues/765#issuecomment-491919099)

> Doorperson: Make guest list screen available from the event screen. This way the doorperson does not have to go through 2 extra screens and clicks and get to the list

Any time we can reduce the number of clicks to make a person's workflow easier is a win.

**Current Event view for Doorperson**
![Screenshot_20190522-151243_Big Neon](https://user-images.githubusercontent.com/10236515/58205578-76bba300-7ca4-11e9-9084-60682682ab31.jpg)

## Scenario: Access Guest List
Given I am a Doorperson
- [ ] When I am viewing an event
- [ ] Then I can access the guest list with one tap

**Comment by iamjoshfrank** [comment]
Updated w/ screenshot of referenced view.

**Comment by bryanjos** [comment]
@jpatricknola I did some initial testing here and I think the navigation will have to be updated as well. 

Steps to reproduce:

* Open App
* Make sure to be logged in as the doorperson or admin
* Click on "Account" tab at the bottom
* Click on "Doorperson"
* Click on the "Huge Ticket Sales" event
* Click "Guest List"
* **Observe**: The back button says "scan tickets"/ **Expected**: The back button says "event" or the event's name
* Click "Scan Tickets"
* **Observe**: Taken to the "Scan Tickets" Screen / **Expected**: Taken back to the event dashboard


Along with this we can probably remove "guest list" from the scan page.

I'll make another ticket for these things to maybe get some feedback
