### ISSUE TITLE
Error - Creating QR code failed failed.

### ISSUE THREAD

**Issue by iamjoshfrank** [revelrylabs/bn-mobile-react#803]
## Description
Next, provide a description of the issue you encountered and the outcome you expected.
- [ ] Description: Error dialogue displayed when navigating to My Tickets after leaving check-in mode

## Screenshots/Gifs
Please provide a visual representation of the issue you encountered with screenshots or a gif. They should include the entire screen of the application, and should include the URL if the issue was found on a web app.
- [ ] Screenshots or gifs:
![Screenshot_20190522-152646_Big Neon](https://user-images.githubusercontent.com/10236515/58206805-0bbf9b80-7ca7-11e9-91dd-54c6488d6733.jpg)

## Steps to Reproduce
Provide steps to reproduce the issue you encountered.

**!Note** - I have not been able to recreate. Not sure if we can grab error logs from Sentry (if we're given access) for timestamp from screenshot to help correlate the two.

- [ ] I am logged in as this user (leave blank if not logged in): `superuser@test.com`
- [ ] I am on this page: My Tickets
- [ ] I performed these actions:
  - in Doorperson views
  - exited check-in mode
  - from Event, tapped My Tickets
  - selected first event listed in My Tickets
- [ ] And saw this happen:
  - taken to tickets carousel, error dialogue opened

## Platform/Device/Browser Information
Please provide platform, device , and browser (when applicable) that you were using when you encountered the issue.

i.e. *found on iOS iPhone 7+*, or *found on OSX High Sierra Chrome version 37.1*

- [ ] Platform: Android 8.0
- [ ] Device: Samsung S7 Edge
- [ ] Browser (if found on web application):

**Comment by iamjoshfrank** [comment]
assigning to myself to try to recreate

**Comment by bryanjos** [comment]
No need. I see the error. Fixing now
