### ISSUE TITLE
Doorperson - GuestList - Navigation Update

### ISSUE THREAD

**Issue by bryanjos** [revelrylabs/bn-mobile-react#809]
_requires #796_

## Background
With #796 we made it easier for a Doorperson to get to the guest list. We did not update the navigation. 

## Scenario: Doorperson on Guest List
Given I am a Doorperson
- [ ] When I am on an Event Dashboard Screen
- [ ] And I click to go to the Guest List Screen
- [ ] Then I see `< Event` or `< <Event Name>`
- [ ] And when I click the above
- [ ] Then I am taken back to Event Dashboard Screen

Some addtional screenshots of current screens to help

![Simulator Screen Shot - iPhone Xʀ - 2019-05-23 at 11 59 55](https://user-images.githubusercontent.com/1257573/58272424-197f2a80-7d54-11e9-9f65-42c415602c29.png)

![Simulator Screen Shot - iPhone Xʀ - 2019-05-23 at 12 11 54](https://user-images.githubusercontent.com/1257573/58272437-1edc7500-7d54-11e9-83b7-49c71f0b91c2.png)

![Simulator Screen Shot - iPhone Xʀ - 2019-05-23 at 12 11 59](https://user-images.githubusercontent.com/1257573/58272446-2439bf80-7d54-11e9-896d-e07c29d57e1f.png)

**Comment by bryanjos** [comment]
Assigned to @iamjoshfrank and @zmelamed to approve

**Comment by jpatricknola** [comment]
@bryanjos 

I am thinking the guest list button on scan tickets could still be useful in the case that the doorperson is scanning tickets and encounters people on the guest list.

I definitely agree the guest list navigation should link back to manage events page instead of scan tickets

**Comment by iamjoshfrank** [comment]
> I am thinking the guest list button on scan tickets could still be useful in the case that the doorperson is scanning tickets and encounters people on the guest list.

yes, agree.

**Comment by iamjoshfrank** [comment]
Updated by removing the second scenario.

I'm approving this.
