### ISSUE TITLE
Unable to open URL: mailto:fansupport@bigneon.com

### ISSUE THREAD

**Issue by bryanjos** [revelrylabs/bn-mobile-react#814]
https://sentry.io/organizations/big-neon-5x/issues/996506523/events/9d4c162a2bf449699e29e8138640b611/?project=1407235&statsPeriod=14d

## Description
Pressing "Contact Support" is supposed to open up the email app. I does not seem to be working

## Screenshots/Gifs
![Simulator Screen Shot - iPhone Xʀ - 2019-05-24 at 10 46 52](https://user-images.githubusercontent.com/1257573/58340472-915f5a80-7e11-11e9-8004-1451e3187d09.png)

## Steps to Reproduce
Provide steps to reproduce the issue you encountered.

- [ ] Login
- [ ] Click on the "Account" tab
- [ ] Click "Contact Support"
- [ ] **Observe**: Nothing happens. **Expected**: Mail app to open

## Platform/Device/Browser Information

- [ ] Platform: iOS
- [ ] Device: iPhone XR

**Comment by bryanjos** [comment]
Note: This **works** on Android

**Comment by jpatricknola** [comment]
@bryan it works on my iphone but i get that same error with Simulator for iphone

**Comment by jpatricknola** [comment]
![IMG_0129B31BE239-1](https://user-images.githubusercontent.com/6878242/58341628-48f56c00-7e14-11e9-8c65-2c5250348b8f.jpeg)

**Comment by jpatricknola** [comment]
^ the screen that opens when clicking contact support on iphone8

**Comment by bryanjos** [comment]
Ok then, I assume that means the error is development specific and works on devices. I say we close this and the issue in sentry as well

**Comment by iamjoshfrank** [comment]
> Ok then, I assume that means the error is development specific and works on devices in production.

Buuuttt wait...

Isn't the [Sentry Issue](https://sentry.io/organizations/big-neon-5x/issues/996506523/events/9d4c162a2bf449699e29e8138640b611/?project=1407235&statsPeriod=14d) tagged with `production`?

![Screen Shot 2019-05-24 at 11 52 48 AM](https://user-images.githubusercontent.com/10236515/58344142-8957e880-7e1a-11e9-8ebe-a6b6af7ecbe7.png)

**Comment by daybreaker** [comment]
Just pointing out mailto links dont work in ios simulator using Linking.openURL - its their bug, not a bug in Big Neon development.

**Comment by bryanjos** [comment]
Does look they might be coming from production. I'm trying to pinpoint exactly how many come up. The error looks to be grouped together with unrelated ones so I'm having a hard time

**Comment by bryanjos** [comment]
Looks like it's happened 6 times in 90 days. There is another related one about maps too: https://sentry.io/organizations/big-neon-5x/events/?project=1407235&query=Error%3A+Unable+to+open+URL&statsPeriod=90d
