### ISSUE TITLE
Event Page Cover Image Shows Partial Circle Artifact (Android)

### ISSUE THREAD

**Issue by iamjoshfrank** [revelrylabs/bn-mobile-react#82]
On Android, there is some sort of weird artifact on the cover image at the top of the page (looks like maybe the bottom of the "play" circle from an image clipped from YouTube, perhaps?). I'm not sure this warrants re-working, but wanted to call it out. See screenshot:

![screenshot_20180830-115633_big neon](https://user-images.githubusercontent.com/10236515/44866865-f81d6200-ac4b-11e8-9af2-bbd4c4031590.jpg)

**Comment by brittanygay** [comment]
This bug is fixed but I found a new bug on the Event Show screen for the icons. Making a new ticket and moving this to QA.
