### ISSUE TITLE
undefined is not an object (evaluating 'v.first_name')

### ISSUE THREAD

**Issue by bryanjos** [revelrylabs/bn-mobile-react#827]
https://sentry.io/organizations/big-neon-5x/issues/988576902/?project=1407235&query=is%3Aunresolved&statsPeriod=14d

## Description
Next, provide a description of the issue you encountered and the outcome you expected.
- [ ] Description:

## Screenshots/Gifs
Please provide a visual representation of the issue you encountered with screenshots or a gif. They should include the entire screen of the application, and should include the URL if the issue was found on a web app.
- [ ] Screenshots or gifs:

## Steps to Reproduce
Provide steps to reproduce the issue you encountered.

- [ ] I am logged in as this user (leave blank if not logged in):
- [ ] I am on this page:
- [ ] I performed these actions:
- [ ] And saw this happen:

## Platform/Device/Browser Information
Please provide platform, device , and browser (when applicable) that you were using when you encountered the issue.

i.e. *found on iOS iPhone 7+*, or *found on OSX High Sierra Chrome version 37.1*

- [ ] Platform:
- [ ] Device:
- [ ] Browser (if found on web application):

**Comment by iamjoshfrank** [comment]
@bryanjos what am I doing to test this??
