### ISSUE TITLE
Invariant Violation: Invariant Violation: React.Children.only expected to receive a single React element child

### ISSUE THREAD

**Issue by bryanjos** [revelrylabs/bn-mobile-react#830]
https://sentry.io/organizations/big-neon-5x/issues/1053356879/?project=1407235&query=is%3Aunresolved&statsPeriod=14d

**Comment by bryanjos** [comment]
The error gave a decent guess to where the error is but I could not figure out why it's being thrown. TouchableHighlight can only have one component in it. In all of the Touchable components in AuthIndex, they all have one component. I'm not sure where else to go with this

**Comment by jpatricknola** [comment]
@bryanjos do you think its related to #829?   Error message for that ticket says "Check the render method of AuthIndex"

**Comment by jpatricknola** [comment]
I notice that in the stack trace for #829 there is 

 TouchableHighlight (at Auth/index.js:72)

**Comment by bryanjos** [comment]
@jpatricknola very possible. I'm starting to think that stack trace may be leading us wrong

**Comment by bryanjos** [comment]
Tried a bunch of things, tested on iOS and Android and I have not been able to reproduce it

**Comment by bryanjos** [comment]
I have tried to reproduce the issue, read into what it could possibly be and have not been able to see it for myself. It also shows up with a very low amount of events in sentry. With that, I'm closing this.

**Comment by bryanjos** [comment]
I also resolved the issue in Sentry. We'll see if it comes up again
