### ISSUE TITLE
Cover Photo Overlaps Profile Avatar in Account (Android)

### ISSUE THREAD

**Issue by iamjoshfrank** [revelrylabs/bn-mobile-react#84]
_split from #48_

See Android screenshot:

![screenshot_1535662086](https://user-images.githubusercontent.com/12603/44882661-dd61e200-ac79-11e8-9cd9-a8968cb0ddb9.png)

**Comment by brittanygay** [comment]
Pulling this in to work on next

**Comment by brittanygay** [comment]
We removed the Profile Avatar until functionality is implemented. Putting this back into the backlog and working on other critical bugs that need my attention until this is ready to be implemented.
