### ISSUE TITLE
Back Navigation and Title Overlap on Edit Account (Android)

### ISSUE THREAD

**Issue by iamjoshfrank** [revelrylabs/bn-mobile-react#85]
_split from #57_

See screenshot on Android:

![screenshot_1535662082](https://user-images.githubusercontent.com/12603/44882666-e357c300-ac79-11e8-91e5-824f8050e272.png)

**Comment by brittanygay** [comment]
**Update**:
I'm still trying to find a solution to this bug, the header styles are a little tricky without messing up anything on iOS devices.

Resource: https://github.com/react-navigation/react-navigation/issues/758

**Comment by brittanygay** [comment]
After doing some research on Android Platform stuff, I legitimately can't figure out how to set this up on the `headerTitle` class in `/Accounts/routes.js`. 

All I need to do is add `android:paddingLeft="#"` on the `headerTitle`, but I'm going to need to pair with a developer. 

Putting this back down for now and moving onto another bug ticket so I don't waste anymore time.

**Comment by brittanygay** [comment]
Updates for the bug on Android have been approved and merged. This will be ready for QA after the next deploy
