### ISSUE TITLE
Clean up stylesheets

### ISSUE THREAD

**Issue by colinincentivize** [revelrylabs/bn-mobile-react#86]
@brittanygay needs to clean up the existing stylesheets a bit, in terms of consolidating some code and pulling in other styles from stylesheets as needed.

List of stylesheets that need some consolidating:

Event Details:
- [x] eventDetailsStyles.js
- [x] imageGridStyles.js

Shared:
- [x] eventStyles.js
- [x] formStyles.js
- [x] slideshowStyles.js

Tickets:
- [x] ticketShowStyles.js
- [x] ticketStyles.js

**Comment by Mcscott142** [comment]
lgtm, marking score

**Comment by brittanygay** [comment]
pulling this in to start on

**Comment by brittanygay** [comment]
Stylesheets have been updated, and PR has been reviewed/merged. 

@Mcscott142 there's nothing to really QA for this ticket, but I'm going assign to you incase you want to check anything. Thanks!
