### ISSUE TITLE
Location Alignment is off on Discover Page

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#92]
## Background
The alignment on the City with the logo and dropdown arrow is a little off. These elements should line up. 

## Scenario: User sees their location on Discover Page
- [ ] When I look at my location (city)
- [ ] Then I see that the Big Neon Logo, city and arrow drop down are all aligned

![slack_-_revelry](https://user-images.githubusercontent.com/6877299/45365871-16b41f00-b5a3-11e8-9b07-91aa8d9827c5.png)

**Comment by brittanygay** [comment]
Pulling this in to work on next.

**Comment by Mcscott142** [comment]
Will QA when we push new build.
