### ISSUE TITLE
Remove Scroll Arrows on Discover Page

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#93]
## Background
When we implement actual Data, users will be able to side scroll top-level events on the Discover page. For now the arrows on the Main Event are just causing confusion so let's remove them

## Scenario: A user visits the Discover Page
- [ ] When I look at the `Hot This Week` event
- [ ] Then I do NOT see Scroll arrows on the image

![slack_-_revelry](https://user-images.githubusercontent.com/6877299/45366198-e620b500-b5a3-11e8-9339-d28b1664ca5e.png)

**Comment by brittanygay** [comment]
Pulling this in to start on

**Comment by brittanygay** [comment]
My PR has been reviewed and merged. Once updates are deployed this will be ready for QA.
