### ISSUE TITLE
Attendee - Explore Page - Connect Location to API

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#97]
## Background
Users will find events based on Locations. We will start with specific cities listed and only allow users to select from those cities where Big Neon has Venues signed. 

## Scenario: A user changes their Location
Given I am logged in
- [ ] When I land on Explore
- [ ] Then I see All Events
- [ ] And `All Locations` selected in the Location dropdown
- [ ] When I select the dropdown
- [ ] And I select a specific City
- [ ] Then my events are filtered

**Comment by Mcscott142** [comment]
Marked SCORE, moved into Next Up

**Comment by jwietelmann** [comment]
Seems like locations are `regions` in the API but none of that is done? the `region_id`s on all my events' venues are `null`. Our locations in the app are hardcoded. And when I call `regions.index()` on the API client I get back an empty array.

cc @zmelamed

**Comment by Mcscott142** [comment]
cc @Krakaw, see above comment.

**Comment by Krakaw** [comment]
Connects big-neon/bn-api-node#245

**Comment by zmelamed** [comment]
The header label that appears when you scroll on the explore view needs to also update to reflect the selected region. Right now it's static "Los Angelas, CA"
