### ISSUE TITLE
Attendee - Event Page - Event Page Scroll

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/bn-mobile-react#99]
## Background
See video [here](https://vimeo.com/291552558) for design tweaks. Looks like the content of the page should have the appearance of covering the artist photo and that sections should have more rounded edges. 

## Scenario: Update Artists page designs
- [ ] Scroll functionality should have content appear to move over the artist's photo
- [ ] Round out the edges of the content section
- [ ] Make close icon bigger (see newest Sketch file here: https://drive.google.com/open?id=1BFFTWs_0Nxuh4QxS-JIe5q-KsEvCUdAK )
- [ ] Other updates to the Header (refer to Sketch file on Drive)

**Also a note from Zach about the Close Button:**
"Just to clarify, the close button should visibly match the design, but the actual area that is tappable should be beyond the edges of the "X". I imagine this could be achieved by either adding padding to the X component itself, or overlaying it with a transparent div that's bigger than it that actually reacts to the tap interaction"

**Comment by brittanygay** [comment]
Here are some links that may help with the scrolling animation setup:

https://facebook.github.io/react-native/docs/animations.html

https://codeburst.io/butter-smooth-animations-in-react-native-93a3b86adf1

https://github.com/oblador/react-native-animatable

I'll continue to post more resources as I come across them.

**Comment by brittanygay** [comment]
I finished some styling updates for the rounded corners, etc. More info and screenshots here: https://github.com/revelrylabs/bn-mobile-react/pull/120

Passing back over to @daybreaker to continue working on

**Comment by brittanygay** [comment]
Updated the AC, along with the Vimeo link. I've also added the newest Sketch file to the Drive here: https://drive.google.com/open?id=1BFFTWs_0Nxuh4QxS-JIe5q-KsEvCUdAK

**Comment by brittanygay** [comment]
Pulling this back in to check out after discussing with @daybreaker about some issues that arose.

**Comment by brittanygay** [comment]
I tried a few things and unfortunately was unsuccessful at fixing the bug we found. We will need to break this issue out into a new bug ticket. CC @daybreaker @Mcscott142

**Comment by Mcscott142** [comment]
Closed but opened but #124 around this
